import json, math
import numpy as np

def r(x, d=4):
    """Round for display in solutions, dropping trailing zeros."""
    if abs(x - round(x)) < 1e-9: return str(int(round(x)))
    s = f"{x:.{d}f}".rstrip('0').rstrip('.')
    return s

def num(prompt, answer, hints, why, tol=None, mistakes=(), unit=None):
    p = dict(type='number', prompt=prompt, answer=float(answer), hints=list(hints), why=why)
    if tol is not None: p['tol'] = tol
    if mistakes: p['mistakes'] = [dict(value=float(v), message=m) for v, m in mistakes]
    if unit: p['unit'] = unit
    return p

def vec(prompt, answer, hints, why, tol=None, mistakes=(), unordered=False):
    p = dict(type='vector', prompt=prompt, answer=[float(a) for a in answer], hints=list(hints), why=why)
    if tol is not None: p['tol'] = tol
    if unordered: p['unordered'] = True
    if mistakes: p['mistakes'] = [dict(value=[float(a) for a in v], message=m) for v, m in mistakes]
    return p

def choice(prompt, answer, wrong, hints, why, mistakes=None):
    p = dict(type='choice', prompt=prompt, answer=answer, wrong=list(wrong), hints=list(hints), why=why)
    if mistakes: p['mistakes'] = [dict(value=k, message=v) for k, v in mistakes.items()]
    return p

def step(text, tex=None):
    return dict(text=text, tex=tex) if tex else dict(text=text)

def problem(id, title, pages, statement, parts, solution, takeaway, tex=None):
    p = dict(id=id, title=title, pages=pages, statement=statement, parts=parts, solution=solution, takeaway=takeaway)
    if tex: p['tex'] = tex
    return p

SETS = {}
def homework(key, track, section, intro, problems):
    SETS[key] = dict(track=track, section=section, intro=intro, problems=problems)

def emit(path):
    body = json.dumps(SETS, indent=1, ensure_ascii=False)
    open(path, 'w').write(
        "// Homework for each section of the Math and ML tracks: multi-part problems with answer checking,\n"
        "// clues that unlock one at a time, and a full solution that unlocks after the student has tried at\n"
        "// least half of a problem's parts. Generated by a script that computes every answer; the numbers\n"
        "// and problems are our own.\n\n"
        "export const homework = " + body + ";\n")
