from lib import *
tex = lambda s: s

# ---------------- Foundations ----------------
p = np.array([0.9, 0.5, 0.8])
L = p.prod(); ll = np.log(p).sum()
homework('math/foundations', 'math', 'Foundations',
 'Functions, inverses, logarithms, and the vector tools (dot products and norms) that every later page uses.',
 [
 problem('compose', 'Composing and undoing functions', ['functions', 'inverse-composition'],
  'Let f(x) = 2x + 3 and g(x) = x^2.',
  [
   num('Compute (g ∘ f)(1).', 25,
       ['g ∘ f means "do f first, then g".', 'First find f(1), then square the result.', 'f(1) = 2·1 + 3 = 5. Now apply g to that number.'],
       '(g ∘ f)(1) = g(f(1)) = g(5) = 25. The order matters: (f ∘ g)(1) = f(1) = 5.',
       mistakes=[(5, 'That is (f ∘ g)(1): you applied g first. In g ∘ f the function written on the right acts first.')]),
   num('Find f⁻¹(11), the input that f sends to 11.', 4,
       ['The inverse undoes f: solve f(x) = 11 for x.', 'Undo the steps of f in reverse order: first subtract 3, then divide by 2.', '2x + 3 = 11 gives 2x = 8.'],
       'f⁻¹(y) = (y − 3)/2, so f⁻¹(11) = 4. Check: f(4) = 11.',
       mistakes=[(1/11, 'The inverse function is not the reciprocal 1/f. It undoes f: f(f⁻¹(y)) = y.'), (25, 'That is f(11). The inverse goes the other way: which x gives f(x) = 11?')]),
   choice('Does g(x) = x^2 have an inverse on all real numbers?', 'No: g(2) = g(−2) = 4, so an output does not tell you the input',
          ['Yes: its inverse is sqrt(x)', 'Yes: every function has an inverse', 'No: g is not linear'],
          ['A function has an inverse only if different inputs always give different outputs (one-to-one).', 'Try two inputs with the same square.'],
          'sqrt(x) only undoes x^2 for x ≥ 0. On all real numbers, 2 and −2 collide, so no inverse exists; restricting the domain to x ≥ 0 fixes it.',
          {'Yes: its inverse is sqrt(x)': 'sqrt(4) = 2, but g(−2) = 4 too: sqrt cannot recover −2. It is an inverse only on x ≥ 0.', 'No: g is not linear': 'Many nonlinear functions have inverses (e^x does). The real issue is that two inputs share an output.'}),
  ],
  [step('Composition applies the right-hand function first: (g ∘ f)(1) = g(f(1)) = g(5) = 25.'),
   step('To invert f, solve y = 2x + 3 for x: x = (y − 3)/2, so f⁻¹(11) = (11 − 3)/2 = 4.'),
   step('g(2) = g(−2) = 4, so g is not one-to-one on the real line and has no inverse there. On x ≥ 0 its inverse is sqrt(x).')],
  'Composition order and invertibility come back in matrices: (AB)x applies B first, and a matrix is invertible exactly when no two inputs share an output.'),
 problem('logs', 'Logs turn products into sums', ['exp-log'],
  'A classifier gives the true labels of three examples probabilities 0.9, 0.5 and 0.8.',
  [
   num('The likelihood is the product of the three probabilities. Compute it.', L,
       ['Multiply the three numbers.', '0.9 × 0.5 first, then × 0.8.'],
       f'0.9 × 0.5 × 0.8 = {r(L)}. With thousands of examples such products become tiny, which is why we take logs.'),
   num('Compute the log-likelihood, ln 0.9 + ln 0.5 + ln 0.8 (natural logs, 3 decimals).', ll,
       ['ln(ab) = ln a + ln b, so this equals the log of your previous answer.', f'Either add the three logs or take ln of {r(L)}.', 'ln 0.9 ≈ −0.105, ln 0.5 ≈ −0.693. Add ln 0.8.'],
       f'ln 0.9 + ln 0.5 + ln 0.8 = {r(ll,3)} = ln {r(L)}. Logs of probabilities are negative because the probabilities are below 1.',
       mistakes=[(-ll, 'Check the sign: the log of a number between 0 and 1 is negative.'), (np.log10(p).sum(), 'That uses base-10 logs. In ML "log" means the natural log, ln.')]),
   num('The average negative log-likelihood is the logistic loss. Compute −(log-likelihood)/3.', -ll/3,
       ['Flip the sign of the log-likelihood, then divide by the number of examples.'],
       f'{r(-ll/3,4)}. Minimizing this average loss is the same as maximizing the likelihood, because ln is increasing.'),
   num('The sigmoid undoes the logit. Compute logit(0.75) = ln(0.75/0.25).', np.log(3),
       ['The odds are 0.75/0.25.', 'The odds are 3 to 1. Take the natural log.'],
       'logit(0.75) = ln 3 ≈ 1.099, and σ(1.099) = 0.75.',
       mistakes=[(3, 'That is the odds. The logit is the log of the odds.'), (1/0.75, 'The logit is not 1/p. It is ln(p/(1 − p)).')]),
  ],
  [step(f'Likelihood: 0.9 · 0.5 · 0.8 = {r(L)}.'),
   step(f'Log-likelihood: ln 0.9 + ln 0.5 + ln 0.8 = −0.1054 − 0.6931 − 0.2231 = {r(ll,4)}.', r'\ln(0.9\cdot0.5\cdot0.8)=\ln0.9+\ln0.5+\ln0.8'),
   step(f'Average negative log-likelihood: {r(-ll,4)}/3 = {r(-ll/3,4)}.'),
   step('logit(0.75) = ln(0.75/0.25) = ln 3 ≈ 1.0986.')],
  'Every likelihood-based loss (logistic loss, cross-entropy) is this computation: take logs so the product becomes a sum, then minimize the average negative.'),
 problem('dot', 'Dot products, norms and angles', ['vectors-dot-product', 'norms'],
  'Let u = [1, 2, 2] and v = [2, 0, 1].',
  [
   num('Compute u · v.', 4, ['Multiply matching entries and add.', '1·2 + 2·0 + 2·1.'], 'u · v = 2 + 0 + 2 = 4.', tol=0),
   num('Compute the Euclidean length ||u||₂.', 3, ['Square the entries, add, take the square root.', '1 + 4 + 4 = 9.'], '||u||₂ = sqrt(9) = 3.',
       mistakes=[(9, 'That is ||u||² (the squared length). Take the square root.'), (5, 'That is the L1 norm, the sum of absolute values.')]),
   num('Compute ||u||₁ (the L1 norm).', 5, ['L1 adds absolute values.'], '|1| + |2| + |2| = 5.', tol=0),
   num('Compute the cosine of the angle between u and v (3 decimals).', 4/(3*np.sqrt(5)),
       ['cos(angle) = u · v / (||u|| ||v||).', 'You have u · v and ||u||. Find ||v|| = sqrt(4 + 0 + 1).', 'cos = 4 / (3 · sqrt 5).'],
       f'cos = 4/(3·sqrt 5) ≈ {r(4/(3*np.sqrt(5)),3)}, an angle of about {r(np.degrees(np.arccos(4/(3*np.sqrt(5)))),1)} degrees. Positive: the vectors point roughly the same way.'),
  ],
  [step('u · v = 1·2 + 2·0 + 2·1 = 4.'),
   step('||u||₂ = sqrt(1 + 4 + 4) = 3 and ||u||₁ = 1 + 2 + 2 = 5.'),
   step(f'||v||₂ = sqrt(5), so cos = 4/(3 sqrt 5) ≈ {r(4/(3*np.sqrt(5)),3)}.', r'\cos\angle(u,v)=\frac{u\cdot v}{\lVert u\rVert\,\lVert v\rVert}=\frac{4}{3\sqrt5}')],
  'A linear model\'s score θ · x is a dot product: large and positive when x points along θ. The norms return as penalties in ridge (L2) and lasso (L1).'),
 ])

# ---------------- Matrices and linear systems ----------------
A = np.array([[1,0,2],[-1,3,1]]); B = np.array([[3,1],[2,1],[1,0]]); AB = A@B
homework('math/matrices-and-linear-systems', 'math', 'Matrices and linear systems',
 'Matrix shapes and products, and solving linear systems by elimination.',
 [
 problem('shapes', 'Shapes and products', ['matrix-operations', 'matrix-multiplication-outer-product'],
  'A = [[1, 0, 2], [−1, 3, 1]] is 2 by 3 and B = [[3, 1], [2, 1], [1, 0]] is 3 by 2.',
  [
   choice('What is the shape of AB?', '2 by 2', ['3 by 3', '2 by 3', 'AB is not defined'],
          ['(m by n) times (n by p) gives m by p.', 'A is 2 by 3 and B is 3 by 2: the inner sizes (3 and 3) match.'],
          'The inner sizes cancel: (2 by 3)(3 by 2) = 2 by 2. BA would be 3 by 3.',
          {'3 by 3': 'That is the shape of BA. In AB the rows come from A and the columns from B.'}),
   vec('Compute AB. Enter its entries row by row, separated by commas (4 numbers).', AB.flatten(),
       ['Entry (i, j) is row i of A dotted with column j of B.', 'Entry (1,1) = [1, 0, 2] · [3, 2, 1].', 'Entry (1,1) = 3 + 0 + 2 = 5. Do the same for the other three.'],
       f'AB = [[{AB[0,0]}, {AB[0,1]}], [{AB[1,0]}, {AB[1,1]}]].', tol=0,
       mistakes=[([5, 4, 1, 2], 'Right numbers, wrong order: enter row 1 first (entries (1,1), (1,2)), then row 2.')]),
   num('The outer product of u = [1, 2] and v = [3, −1, 0] is the 2 by 3 matrix u vᵀ. What is its rank?', 1,
       ['Each row of u vᵀ is a multiple of vᵀ.', 'Row 1 is 1·vᵀ, row 2 is 2·vᵀ. How many independent rows?'],
       'Every row is a multiple of v, so the rank is 1. Outer products are the rank-one building blocks of matrix products and the SVD.', tol=0,
       mistakes=[(2, 'Row 2 is exactly twice row 1, so the rows are not independent.')]),
  ],
  [step('Shapes: (2 by 3)(3 by 2) = 2 by 2.'),
   step(f'Row 1 of A times the columns of B: [1,0,2]·[3,2,1] = 5 and [1,0,2]·[1,1,0] = 1. Row 2: [−1,3,1]·[3,2,1] = 4 and [−1,3,1]·[1,1,0] = 2. So AB = [[5, 1], [4, 2]].'),
   step('u vᵀ = [[3, −1, 0], [6, −2, 0]]: the second row is twice the first, so the rank is 1.')],
  'In ML, X θ multiplies an n by d data matrix by a d-vector, and XᵀX is d by d. Checking shapes catches most bugs before they happen.'),
 problem('eliminate', 'Solve by elimination', ['matrix-systems', 'gaussian-elimination'],
  'Solve the system  x + y + z = 6,  2x + y − z = 1,  x − y + 2z = 5.',
  [
   num('Eliminate x: replace row 2 by (row 2 − 2 · row 1). What is the right-hand side of the new row 2?', -11,
       ['Subtract twice the whole row 1, including its right-hand side.', 'New right-hand side = 1 − 2·6.'],
       'Row 2 − 2·row 1 = [0, −1, −3 | −11].', tol=0,
       mistakes=[(-5, 'You subtracted row 1 once. The multiplier is 2, because the x-coefficient in row 2 is 2.'), (11, 'Check the sign: 1 − 12 = −11.')]),
   vec('Finish the elimination and back-substitute. Enter x, y, z.', [1, 2, 3],
       ['Also eliminate x from row 3 (row 3 − row 1) to get [0, −2, 1 | −1].', 'Use the new row 2 to eliminate y from row 3: row 3 − 2·row 2.', 'You should get 7z = 21. Then back-substitute into −y − 3z = −11 and then into row 1.'],
       'z = 3, y = 2, x = 1.', tol=1e-6),
   choice('How can you be sure the answer is right without redoing the elimination?', 'Substitute it into all three original equations', ['Check that x + y + z = 6 only', 'Check that the numbers are integers', 'Compute the determinant'],
          ['A solution must satisfy every equation.'],
          '1 + 2 + 3 = 6, 2 + 2 − 3 = 1, 1 − 2 + 6 = 5. All three hold. np.linalg.solve plus a residual check A x − b ≈ 0 does the same in code.'),
  ],
  [step('Row 2 − 2·row 1: [0, −1, −3 | −11]. Row 3 − row 1: [0, −2, 1 | −1].'),
   step('Row 3 − 2·(new row 2): [0, 0, 7 | 21], so z = 3.'),
   step('−y − 3·3 = −11 gives y = 2; x + 2 + 3 = 6 gives x = 1.'),
   step('Check in all three original equations: 6, 1, 5. Correct.')],
  'Elimination is what np.linalg.solve does (as an LU factorization). The normal equation of least squares is solved exactly this way.'),
 problem('howmany', 'None, one, or infinitely many?', ['solution-structure'],
  'Consider x + 2y = 3 and 2x + 4y = c, for a number c.',
  [
   num('For which value of c does the system have infinitely many solutions?', 6,
       ['The left side of equation 2 is exactly twice the left side of equation 1.', 'For the equations to agree, the right side must also be doubled.'],
       'With c = 6 the second equation is just twice the first, so it adds no information: a whole line of solutions.', tol=0),
   choice('For c = 6, which vector spans the null space (the directions you can move without changing the left-hand sides)?', '[−2, 1]', ['[1, 2]', '[3, 0]', '[2, 1]'],
          ['Solve x + 2y = 0.', 'If y = 1, what must x be?'],
          'x + 2y = 0 gives x = −2y, so the null space is spanned by [−2, 1]. All solutions are [3, 0] + t[−2, 1].',
          {'[1, 2]': '[1, 2] is the row of coefficients, which is perpendicular to the null space: 1 + 4 ≠ 0.', '[3, 0]': '[3, 0] is a particular solution of the system itself, not a null-space direction.'}),
   choice('How many solutions are there for c = 5?', 'None', ['Exactly one', 'Infinitely many', 'Two'],
          ['Double the first equation and compare with the second.'],
          'Doubling the first gives 2x + 4y = 6, which contradicts 2x + 4y = 5: no solution.'),
  ],
  [step('Equation 2 has left side 2·(x + 2y). It is consistent only when c = 2·3 = 6.'),
   step('Then all solutions are x = 3 − 2t, y = t, that is [3, 0] + t[−2, 1]: a particular solution plus the null space.'),
   step('For any other c, such as 5, the two equations contradict each other and there is no solution.')],
  'This is why the normal equation can fail: if two features are exact copies, XᵀX is singular and there are infinitely many least-squares solutions.'),
 ])

# ---------------- Vector spaces ----------------
homework('math/vector-spaces', 'math', 'Vector spaces',
 'Span, independence, subspaces, bases and dimension.',
 [
 problem('independent', 'Independent or not?', ['span-linear-combinations', 'linear-independence', 'dimension'],
  'Let v1 = [1, 0, 1], v2 = [0, 1, 1] and v3 = [1, 1, 2].',
  [
   vec('Find numbers a and b with v3 = a·v1 + b·v2. Enter a, b.', [1, 1],
       ['Write a·v1 + b·v2 = [a, b, a + b] and match it with [1, 1, 2].'],
       'a = 1 and b = 1: v3 = v1 + v2.', tol=1e-6),
   num('What is the rank of the matrix with columns v1, v2, v3?', 2,
       ['The rank counts independent columns.', 'v3 adds nothing new, since it is v1 + v2. Are v1 and v2 independent?'],
       'v1 and v2 are not multiples of each other, and v3 depends on them: rank 2.', tol=0,
       mistakes=[(3, 'Three columns, but v3 = v1 + v2, so only two are independent.')]),
   choice('Is [1, 1, 0] in the span of v1, v2, v3?', 'No', ['Yes'],
          ['Every vector in the span is a·v1 + b·v2 = [a, b, a + b].', 'Its third entry must equal the sum of the first two.'],
          'For [1, 1, 0] you would need 1 + 1 = 0. The span is the plane x3 = x1 + x2, and [1, 1, 0] is not on it.'),
  ],
  [step('a·v1 + b·v2 = [a, b, a + b]. Matching [1, 1, 2] gives a = b = 1, so v3 = v1 + v2.'),
   step('The rank is 2: v1, v2 independent, v3 dependent. The span is a plane (dimension 2) in R³.'),
   step('Vectors in the span satisfy x3 = x1 + x2; [1, 1, 0] does not (0 ≠ 2), so it is not in the span.')],
  'A feature that is the sum of two other features adds no new direction: the design matrix loses rank and least squares can no longer pick unique weights.'),
 problem('coords', 'Coordinates in another basis', ['basis-coordinates'],
  'Use the basis b1 = [1, 1], b2 = [1, −1] of R².',
  [
   vec('Find the coordinates of x = [5, 1] in this basis (c1, c2 with x = c1·b1 + c2·b2).', [3, 2],
       ['Solve c1 + c2 = 5 and c1 − c2 = 1.', 'Add the two equations to get c1.', 'Or use orthogonality: c1 = (x · b1)/(b1 · b1).'],
       'c1 = 3 and c2 = 2: 3[1, 1] + 2[1, −1] = [5, 1].', tol=1e-6,
       mistakes=[([5, 1], 'Those are the coordinates in the standard basis. Find c1, c2 with c1·b1 + c2·b2 = x.'), ([2, 3], 'Check the order: c1 goes with b1 = [1, 1].')]),
   vec('Find the coordinates of [0, 2].', [1, -1],
       ['Solve c1 + c2 = 0 and c1 − c2 = 2.'], 'c1 = 1, c2 = −1: [1, 1] − [1, −1] = [0, 2].', tol=1e-6),
   choice('Why can [1, 1] and [2, 2] not be a basis of R²?', 'They are dependent: both lie on one line, so they do not span R²',
          ['They are not unit vectors', 'They are not perpendicular', 'A basis needs three vectors in R²'],
          ['A basis must span the space and be independent.'],
          'A basis only needs independence and spanning; unit length and perpendicularity are optional niceties.',
          {'They are not perpendicular': 'Bases need not be orthogonal: [1, 0] and [1, 1] form a basis. The problem is that [2, 2] = 2·[1, 1].'}),
  ],
  [step('c1 + c2 = 5 and c1 − c2 = 1 give c1 = 3, c2 = 2. Because b1 ⊥ b2 you can also use c1 = x·b1/(b1·b1) = 6/2 = 3.'),
   step('For [0, 2]: c1 + c2 = 0, c1 − c2 = 2, so c1 = 1, c2 = −1.'),
   step('[2, 2] = 2·[1, 1]: the two vectors are dependent and only span a line.')],
  'Changing basis is how PCA works: it re-expresses each data point in the coordinates of the principal directions.'),
 problem('subspace', 'Is it a subspace?', ['subspaces'],
  'Subsets of R³.',
  [
   choice('Which set is a subspace of R³?', 'All x with x1 + x2 + x3 = 0', ['All x with x1 + x2 + x3 = 1', 'All x with x1 ≥ 0', 'All x with x1·x2 = 0'],
          ['A subspace must contain 0 and be closed under adding vectors and scaling them.', 'Test each set with the zero vector first, then with scaling by −1 and with adding two members.'],
          'x1 + x2 + x3 = 0 contains 0 and is closed under addition and scaling. The others fail: = 1 misses 0; x1 ≥ 0 fails scaling by −1; x1·x2 = 0 fails addition ([1,0,0] + [0,1,0]).',
          {'All x with x1 ≥ 0': 'Scale [1, 0, 0] by −1: you leave the set.', 'All x with x1·x2 = 0': '[1, 0, 0] and [0, 1, 0] are both in it, but their sum [1, 1, 0] is not.', 'All x with x1 + x2 + x3 = 1': 'Does it contain the zero vector?'}),
   num('What is the dimension of {x : x1 + x2 + x3 = 0}?', 2,
       ['One linear equation removes one degree of freedom.', 'Choose x1 and x2 freely; then x3 is fixed.'],
       'It is a plane through the origin, the null space of [1 1 1]: dimension 3 − 1 = 2.', tol=0),
  ],
  [step('Check 0, addition and scaling. Only x1 + x2 + x3 = 0 passes all three.'),
   step('x3 = −x1 − x2 with x1, x2 free: basis [1, 0, −1], [0, 1, −1], dimension 2 (rank-nullity: 3 − 1).')],
  'Subspaces are the sets linear models live in: the column space of X holds every possible prediction vector.'),
 ])

# ---------------- Linear transformations ----------------
Mrot = np.array([[0,-1],[1,0]]); S = np.diag([2,1])
homework('math/linear-transformations', 'math', 'Linear transformations',
 'Maps that respect addition and scaling, their matrices, composition, and change of basis.',
 [
 problem('rotate', 'Build the matrix of a map', ['transformation-matrix', 'composition-of-transformations'],
  'R rotates the plane 90° counterclockwise. S doubles the x-coordinate: S(x, y) = (2x, y).',
  [
   vec('Enter the matrix of R row by row (4 numbers).', Mrot.flatten(),
       ['The columns of the matrix are R(e1) and R(e2).', 'Rotating e1 = [1, 0] by 90° counterclockwise gives [0, 1]; where does e2 = [0, 1] go?', 'R(e2) = [−1, 0]. Put R(e1) and R(e2) in as columns.'],
       'R = [[0, −1], [1, 0]]: columns R(e1) = [0, 1] and R(e2) = [−1, 0].', tol=0,
       mistakes=[([0, 1, -1, 0], 'You put R(e1) and R(e2) in as rows. They go in as columns (that is the clockwise rotation).')]),
   vec('Compute R([3, 2]).', Mrot@[3,2], ['Multiply the matrix by the vector.'], 'R[3, 2] = [−2, 3]: perpendicular to [3, 2] and the same length.', tol=0),
   vec('Compute (S ∘ R)([1, 1]), that is, rotate first, then stretch.', S@Mrot@[1,1],
       ['Apply R to [1, 1] first.', 'R[1, 1] = [−1, 1]. Now double the x-coordinate.'],
       '(S ∘ R)[1, 1] = S[−1, 1] = [−2, 1].', tol=0,
       mistakes=[(Mrot@S@[1,1], 'That is (R ∘ S)[1, 1]: you stretched first. S ∘ R rotates first.')]),
   choice('Do S and R commute (SR = RS)?', 'No: stretching then rotating differs from rotating then stretching', ['Yes: all 2 by 2 matrices commute', 'Yes, because both are linear'],
          ['Compute (R ∘ S)[1, 1] and compare with your previous answer.'],
          '(R ∘ S)[1, 1] = R[2, 1] = [−1, 2], not [−2, 1]. Matrix multiplication is not commutative.'),
  ],
  [step('Columns are the images of e1 and e2: R(e1) = [0, 1], R(e2) = [−1, 0], so R = [[0, −1], [1, 0]].'),
   step('R[3, 2] = [0·3 − 1·2, 1·3 + 0·2] = [−2, 3].'),
   step('(S ∘ R)[1, 1] = S[−1, 1] = [−2, 1], while (R ∘ S)[1, 1] = R[2, 1] = [−1, 2]: SR ≠ RS.')],
  'A neural network layer is a linear map followed by a nonlinearity; stacking layers composes maps, and the order matters.'),
 problem('linear', 'Linear or affine?', ['linear-transformations', 'affine-maps'],
  'A map T is linear when T(a u + b v) = a T(u) + b T(v) for all vectors and numbers.',
  [
   choice('Which map from R² to R² is linear?', 'T(x, y) = (x + y, 2y)', ['T(x, y) = (x + 1, y)', 'T(x, y) = (xy, y)', 'T(x, y) = (|x|, y)'],
          ['A quick test: a linear map sends 0 to 0.', 'Also test scaling: does T(−u) = −T(u)?'],
          'Only (x + y, 2y) is linear; its matrix is [[1, 1], [0, 2]]. Adding 1 moves 0; xy and |x| break scaling.',
          {'T(x, y) = (x + 1, y)': 'T(0, 0) = (1, 0) ≠ 0. This is affine (linear plus a shift), not linear.', 'T(x, y) = (|x|, y)': 'T(−1, 0) = (1, 0), but −T(1, 0) = (−1, 0).'}),
   vec('The affine map f(x) = A x + b has A = [[2, 0], [0, 3]] and b = [1, −1]. Compute f([1, 1]).', [3, 2],
       ['First A[1, 1], then add b.'], 'A[1, 1] = [2, 3]; adding b gives [3, 2].', tol=0),
   vec('Compute f([0, 0]).', [1, -1], ['A times the zero vector is zero.'], 'f(0) = b = [1, −1]. An affine map with b ≠ 0 does not fix the origin, so it is not linear. θ · x + θ₀ is affine for the same reason.', tol=0),
  ],
  [step('Test T(0) = 0 and T(a u) = a T(u): only (x + y, 2y) passes.'),
   step('f([1, 1]) = [2, 3] + [1, −1] = [3, 2]; f(0) = [1, −1].')],
  'Models with an intercept, θ · x + θ₀, are affine. Adding a constant feature 1 turns them into linear maps on [1, x], which is why design matrices get a column of ones.'),
 problem('eigbasis', 'A power made easy by a change of basis', ['change-of-basis', 'diagonalization'],
  'A = [[2, 1], [1, 2]]. Use the basis b1 = [1, 1], b2 = [1, −1].',
  [
   vec('Compute A b1 and A b2, and give the two multiples: A b1 = c·b1 and A b2 = d·b2. Enter c, d.', [3, 1],
       ['Multiply A by [1, 1]: you should get a multiple of [1, 1].'],
       'A b1 = [3, 3] = 3 b1 and A b2 = [1, −1] = 1 b2. In the basis b1, b2 the matrix of A is diag(3, 1).', tol=0),
   vec('Write [1, 0] in this basis. Enter its coordinates.', [0.5, 0.5],
       ['Solve c1[1, 1] + c2[1, −1] = [1, 0].'], '[1, 0] = ½ b1 + ½ b2.', tol=1e-6),
   vec('Use the two answers to compute A⁵ [1, 0] without multiplying matrices five times.', np.linalg.matrix_power(np.array([[2,1],[1,2]]),5)@[1,0],
       ['In the new basis, A multiplies the b1-coordinate by 3 and the b2-coordinate by 1.', 'After five steps: coordinates ½·3⁵ and ½·1⁵.', 'A⁵[1, 0] = (243/2) b1 + (1/2) b2. Convert back to standard coordinates.'],
       'A⁵[1, 0] = (243/2)[1, 1] + (1/2)[1, −1] = [122, 121].', tol=0),
  ],
  [step('A b1 = 3 b1 and A b2 = b2, so in this basis A is diag(3, 1).'),
   step('[1, 0] = ½ b1 + ½ b2.'),
   step('A⁵ scales the coordinates to ½·243 and ½·1, so A⁵[1, 0] = 121.5[1, 1] + 0.5[1, −1] = [122, 121].', r'A^5\begin{bmatrix}1\\0\end{bmatrix}=\tfrac{243}{2}\begin{bmatrix}1\\1\end{bmatrix}+\tfrac12\begin{bmatrix}1\\-1\end{bmatrix}=\begin{bmatrix}122\\121\end{bmatrix}')],
  'Choosing the eigenvector basis makes a matrix diagonal. The same trick explains how gradient descent, PageRank and PCA behave.'),
 ])

# ---------------- Rank, determinants and inverses ----------------
M = np.array([[2,1,0],[1,3,1],[0,1,2]])
homework('math/rank-determinants-and-inverses', 'math', 'Rank, determinants and inverses',
 'Rank and nullity, determinants as volume, and when a matrix can be inverted.',
 [
 problem('ranknull', 'Rank and nullity', ['rank-nullity'],
  'A = [[1, 2, 3], [2, 4, 6], [1, 0, 1]].',
  [
   num('What is the rank of A?', 2,
       ['Look for a row that is a multiple of another.', 'Row 2 = 2·row 1. Is row 3 a multiple of row 1?'],
       'Row 2 duplicates row 1; rows 1 and 3 are independent. Rank 2.', tol=0),
   num('What is the nullity (dimension of the null space)?', 1,
       ['Rank + nullity = number of columns.'], '3 − 2 = 1.', tol=0),
   choice('Which vector spans the null space?', '[−1, −1, 1]', ['[1, 2, 3]', '[1, 1, 1]', '[1, 0, −1]'],
          ['Solve x1 + 2x2 + 3x3 = 0 and x1 + x3 = 0.', 'The second equation gives x1 = −x3. Set x3 = 1.'],
          'A[−1, −1, 1] = [−1 − 2 + 3, −2 − 2 + 6, −1 + 1] = [0, 0, 0].',
          {'[1, 0, −1]': 'Row 1 gives 1 + 0 − 3 = −2 ≠ 0.', '[1, 1, 1]': 'Row 1 gives 6 ≠ 0.'}),
  ],
  [step('Row 2 = 2·row 1 and row 3 is not a multiple of row 1: rank 2.'),
   step('Nullity = 3 − 2 = 1.'),
   step('x1 + x3 = 0 and x1 + 2x2 + 3x3 = 0 with x3 = 1 give x1 = −1, x2 = −1: null space spanned by [−1, −1, 1].')],
  'A nonzero null space means different inputs give the same output. For a design matrix, it means different weight vectors make identical predictions.'),
 problem('det', 'The determinant as an area', ['determinant-geometry', 'invertible-transformations'],
  'A = [[3, 1], [1, 2]].',
  [
   num('Compute det A.', 5, ['For [[a, b], [c, d]], det = ad − bc.'], 'det A = 3·2 − 1·1 = 5.', tol=0,
       mistakes=[(7, 'That is ad + bc. The determinant subtracts: ad − bc.')]),
   num('A triangle of area 2 is mapped by A. What is the area of its image?', 10,
       ['|det A| is the factor by which A scales every area.'], 'Areas scale by |det A| = 5, so 2 becomes 10.', tol=0),
   num('Compute det(2A).', 20,
       ['Doubling the matrix doubles both rows.', 'Each doubled row doubles the determinant.'],
       'det(2A) = 2²·det A = 20 for a 2 by 2 matrix (in n dimensions, 2ⁿ).', tol=0,
       mistakes=[(10, 'Both rows are doubled, so the determinant is multiplied by 2·2 = 4, not 2.')]),
   num('Compute det(A⁻¹).', 0.2, ['det(A⁻¹) = 1/det A.'], 'The inverse undoes the area scaling: 1/5 = 0.2.'),
  ],
  [step('det A = 6 − 1 = 5, so areas are multiplied by 5: 2 becomes 10.'),
   step('det(2A) = 4·5 = 20 because each of the two rows is doubled.'),
   step('det(A⁻¹) = 1/5. If det A were 0, A would flatten the plane onto a line and could not be undone.')],
  'det A = 0 means some direction is squashed to nothing, the same as a nonzero null space and the same as no inverse.'),
 problem('cofactor', 'Cofactors, row operations and the inverse', ['determinants-cofactor-row-ops', 'invertible-transformations'],
  'M = [[2, 1, 0], [1, 3, 1], [0, 1, 2]].',
  [
   num('Compute det M by cofactor expansion along the first row.', round(np.linalg.det(M)),
       ['det M = 2·det[[3, 1], [1, 2]] − 1·det[[1, 1], [0, 2]] + 0·(...).', 'The two 2 by 2 determinants are 5 and 2.'],
       'det M = 2·5 − 1·2 + 0 = 8.', tol=0,
       mistakes=[(12, 'Remember the alternating signs: +, −, + along the first row.')]),
   num('What is the determinant after swapping rows 1 and 2?', -8, ['A row swap flips the sign.'], 'Swapping two rows multiplies the determinant by −1: −8.', tol=0),
   num('What is the determinant after adding 3 times row 1 to row 2?', 8, ['Adding a multiple of one row to another does not change the determinant.'], 'Still 8: this is why elimination preserves the determinant up to swaps.', tol=0),
   num('Compute the (1, 1) entry of M⁻¹ (3 decimals).', np.linalg.inv(M)[0,0],
       ['(M⁻¹)₁₁ = C₁₁ / det M, where C₁₁ is the cofactor of entry (1, 1).', 'C₁₁ = det[[3, 1], [1, 2]].'],
       '(M⁻¹)₁₁ = 5/8 = 0.625.'),
  ],
  [step('Expansion along row 1: 2(3·2 − 1·1) − 1(1·2 − 1·0) + 0 = 10 − 2 = 8.'),
   step('A row swap gives −8; adding a multiple of a row keeps 8.'),
   step('(M⁻¹)₁₁ = C₁₁/det M = 5/8 = 0.625. Check with np.linalg.inv(M)[0, 0].')],
  'In practice determinants are computed by elimination, tracking row swaps: the product of the pivots, with a sign for each swap.'),
 ])

# ---------------- Analytic geometry ----------------
X = np.array([[1,0],[1,1],[1,2]], float); y = np.array([1,2,4], float)
th = np.linalg.solve(X.T@X, X.T@y); res = y - X@th
homework('math/analytic-geometry-angles-and-projections', 'math', 'Analytic geometry: angles and projections',
 'Inner products, orthogonality, projections, and least squares as a projection.',
 [
 problem('project', 'Project onto a line', ['orthogonal-projections', 'orthogonality'],
  'Project b = [3, 0, 3] onto the line through a = [1, 2, 2].',
  [
   num('Compute a · b.', 9, ['Multiply matching entries and add.'], '3 + 0 + 6 = 9.', tol=0),
   vec('Compute the projection p = (a · b / a · a) a.', [1, 2, 2],
       ['a · a = 1 + 4 + 4.', 'The factor is 9/9 = 1.'], 'p = (9/9) a = [1, 2, 2].', tol=1e-6,
       mistakes=[([3, 6, 6], 'You forgot to divide by a · a = 9.')]),
   num('Compute the length of the residual b − p.', 3,
       ['b − p = [2, −2, 1].'], '||[2, −2, 1]|| = sqrt(4 + 4 + 1) = 3.'),
   choice('Why is b − p perpendicular to a?', 'p is the closest point to b on the line, so the leftover must be at a right angle to it',
          ['Because a has length 3', 'Because b has a zero entry', 'It is a coincidence of these numbers'],
          ['Compute (b − p) · a.'], '(b − p) · a = 2 − 4 + 2 = 0. The perpendicular leftover is what makes p the closest point, for any a and b.'),
  ],
  [step('a · b = 9 and a · a = 9, so p = 1·a = [1, 2, 2].'),
   step('b − p = [2, −2, 1], of length 3, and (b − p) · a = 0.')],
  'Least squares is this projection with the line replaced by the column space of X: the prediction vector is the closest point to y that the model can produce.'),
 problem('lsq', 'Least squares as a projection', ['orthogonal-projections', 'least-squares-normal-equation'],
  'Fit y = θ₀ + θ₁x to the points (0, 1), (1, 2), (2, 4). The design matrix has columns [1, 1, 1] and [0, 1, 2].',
  [
   vec('Compute XᵀX (4 numbers, row by row).', (X.T@X).flatten(),
       ['Entry (i, j) is column i of X dotted with column j.', 'The top-left entry is [1,1,1]·[1,1,1] = 3.'], 'XᵀX = [[3, 3], [3, 5]].', tol=0),
   vec('Solve XᵀX θ = Xᵀy. Enter θ₀, θ₁ (3 decimals).', th,
       ['Xᵀy = [1 + 2 + 4, 0 + 2 + 8] = [7, 10].', 'Solve 3θ₀ + 3θ₁ = 7 and 3θ₀ + 5θ₁ = 10: subtract to get θ₁.'],
       f'θ₁ = 3/2 = 1.5 and θ₀ = 5/6 ≈ {r(th[0],3)}.', tol=0.005),
   vec('Compute the residual vector y − Xθ (3 decimals).', res,
       ['The predictions are θ₀, θ₀ + θ₁ and θ₀ + 2θ₁.'], f'Residuals [{r(res[0],3)}, {r(res[1],3)}, {r(res[2],3)}].', tol=0.005),
   choice('The residuals add up to 0. Why?', 'The residual is perpendicular to the column of ones', ['The data are on a straight line', 'Least squares always gives zero error', 'There are three points'],
          ['The normal equation says Xᵀ(y − Xθ) = 0. What does its first row say?'],
          'The first row of Xᵀ is [1, 1, 1], so Xᵀ(y − Xθ) = 0 contains "sum of residuals = 0". Any model with an intercept has this property.'),
  ],
  [step('XᵀX = [[3, 3], [3, 5]] and Xᵀy = [7, 10].'),
   step(f'Solve: 2θ₁ = 3, θ₁ = 1.5, θ₀ = (7 − 4.5)/3 = 5/6 ≈ {r(th[0],4)}.', r'\begin{bmatrix}3&3\\3&5\end{bmatrix}\theta=\begin{bmatrix}7\\10\end{bmatrix}'),
   step(f'Predictions {r(X[0]@th,3)}, {r(X[1]@th,3)}, {r(X[2]@th,3)}; residuals {r(res[0],3)}, {r(res[1],3)}, {r(res[2],3)}.'),
   step('Check perpendicularity: residuals · [1,1,1] = 0 and residuals · [0,1,2] = −1/3 + 1/3 = 0.')],
  'The zero-sum residual is a quick sanity check for any regression with an intercept, and the perpendicular residual is the whole content of the normal equation.'),
 problem('gs', 'Gram-Schmidt and the orthogonal complement', ['gram-schmidt', 'orthogonal-complement'],
  'Orthogonalize b1 = [1, 1, 0] and b2 = [1, 0, 1].',
  [
   num('Keep u1 = b1. What multiple of u1 do you subtract from b2 (the coefficient b2·u1 / u1·u1)?', 0.5,
       ['b2 · u1 = 1 and u1 · u1 = 2.'], '1/2 = 0.5.'),
   vec('Compute u2 = b2 − 0.5·u1.', [0.5, -0.5, 1], ['[1, 0, 1] − [0.5, 0.5, 0].'], 'u2 = [0.5, −0.5, 1], and u1 · u2 = 0.5 − 0.5 + 0 = 0.', tol=1e-6),
   num('Compute ||u2|| (3 decimals).', np.sqrt(1.5), ['0.25 + 0.25 + 1.'], f'sqrt(1.5) ≈ {r(np.sqrt(1.5),3)}. Divide by it to get a unit vector.'),
   choice('Which vector spans the orthogonal complement of span{b1, b2} in R³?', '[1, −1, −1]', ['[1, 1, 1]', '[0.5, −0.5, 1]', '[1, −1, 0]'],
          ['You need a vector perpendicular to both b1 and b2.', 'Test each option with dot products against [1, 1, 0] and [1, 0, 1].'],
          '[1, −1, −1]·[1, 1, 0] = 0 and [1, −1, −1]·[1, 0, 1] = 0. The complement of a plane in R³ is a line.',
          {'[0.5, −0.5, 1]': 'That is u2, which lies inside the plane, not perpendicular to it.', '[1, −1, 0]': 'It is perpendicular to b1 but not to b2: 1 + 0 + 0 ≠ 0.'}),
  ],
  [step('u1 = [1, 1, 0]. Coefficient = (b2·u1)/(u1·u1) = 1/2.'),
   step('u2 = [1, 0, 1] − ½[1, 1, 0] = [0.5, −0.5, 1], with ||u2|| = sqrt(1.5) ≈ 1.225.'),
   step('A vector perpendicular to both is [1, −1, −1] (check both dot products are 0).')],
  'Gram-Schmidt is the QR decomposition, the numerically stable way to solve least squares (np.linalg.lstsq uses a related method).'),
 ])

# ---------------- Eigenvalues ----------------
homework('math/eigenvalues-and-eigenvectors', 'math', 'Eigenvalues and eigenvectors',
 'Eigenvalues and eigenvectors, trace and determinant, diagonalization, Markov chains, and symmetric matrices.',
 [
 problem('find', 'Find the eigenvalues', ['eigenvalues-eigenvectors', 'trace'],
  'A = [[4, 1], [2, 3]].',
  [
   vec('Enter trace A and det A.', [7, 10], ['Trace = sum of the diagonal; det = ad − bc.'], 'trace 7 and det 12 − 2 = 10.', tol=0),
   vec('Find both eigenvalues (any order).', [5, 2],
       ['They solve λ² − (trace)λ + det = 0.', 'λ² − 7λ + 10 = 0 factors as (λ − 5)(λ − 2).'],
       'λ = 5 and λ = 2. Check: 5 + 2 = 7 = trace and 5·2 = 10 = det.', tol=1e-6, unordered=True),
   choice('Which is an eigenvector for λ = 5?', '[1, 1]', ['[1, −2]', '[1, 0]', '[2, 1]'],
          ['Solve (A − 5I)v = 0, with A − 5I = [[−1, 1], [2, −2]].', 'The first row says −v1 + v2 = 0.'],
          'A[1, 1] = [5, 5] = 5[1, 1]. [1, −2] belongs to λ = 2.',
          {'[1, −2]': 'A[1, −2] = [2, −4] = 2[1, −2]: that one belongs to λ = 2.'}),
   vec('Compute A³ [1, 1] without multiplying matrices.', [125, 125], ['[1, 1] is an eigenvector with eigenvalue 5.'], 'A³[1, 1] = 5³[1, 1] = [125, 125].', tol=0),
  ],
  [step('trace 7, det 10, so λ² − 7λ + 10 = 0 and λ = 5, 2.'),
   step('A − 5I = [[−1, 1], [2, −2]] gives v = [1, 1]; A − 2I = [[2, 1], [2, 1]] gives v = [1, −2].'),
   step('A³[1, 1] = 125[1, 1].')],
  'Along an eigenvector, repeated multiplication is just repeated scaling. That is the key to Markov chains, gradient descent on quadratics and PCA.'),
 problem('markov', 'A two-state Markov chain', ['diagonalization', 'pagerank'],
  'Each day 90% of customers of shop A stay and 10% switch to B; 80% of B\'s customers stay and 20% switch to A. The matrix P = [[0.9, 0.2], [0.1, 0.8]] maps today\'s shares [a, b] to tomorrow\'s.',
  [
   vec('Find the eigenvalues of P (any order).', [1, 0.7],
       ['Each column sums to 1, so 1 is an eigenvalue.', 'The trace is the sum of the eigenvalues.'],
       'Eigenvalues 1 and 0.7 (trace 1.7, det 0.72 − 0.02 = 0.7).', unordered=True),
   vec('Find the long-run shares (the eigenvector for eigenvalue 1, scaled to sum to 1). 3 decimals.', [2/3, 1/3],
       ['Solve (P − I)v = 0: −0.1 v1 + 0.2 v2 = 0.', 'So v1 = 2 v2. Scale so that v1 + v2 = 1.'],
       'v = [2/3, 1/3]: in the long run A has two thirds of the customers.', tol=0.005),
   num('Starting from [1, 0], the distance to the long-run shares shrinks by a factor 0.7 each day. By what factor has it shrunk after 10 days (3 decimals)?', 0.7**10,
       ['The part along the second eigenvector is multiplied by 0.7 every day.'], f'0.7¹⁰ ≈ {r(0.7**10,3)}: after 10 days the shares are within 3% of the limit.'),
  ],
  [step('Columns sum to 1, so λ = 1; the trace 1.7 gives the other eigenvalue 0.7.'),
   step('(P − I)v = 0 gives v1 = 2v2, so the long-run shares are [2/3, 1/3].'),
   step('The other component shrinks like 0.7ᵏ; 0.7¹⁰ ≈ 0.028.')],
  'PageRank is the same computation with millions of pages: the eigenvector for eigenvalue 1, found by repeated multiplication.'),
 problem('symmetric', 'Symmetric matrices', ['spectral-theorem'],
  'S = [[2, 1], [1, 2]].',
  [
   vec('Find the eigenvalues of S (any order).', [3, 1], ['trace 4, det 3.'], 'λ = 3 (eigenvector [1, 1]) and λ = 1 (eigenvector [1, −1]).', tol=1e-6, unordered=True),
   choice('What is special about the eigenvectors [1, 1] and [1, −1]?', 'They are perpendicular, as the spectral theorem guarantees for symmetric matrices',
          ['They have length 1', 'They are the rows of S', 'Nothing: eigenvectors of any matrix are perpendicular'],
          ['Take their dot product.'], 'Their dot product is 0. For a symmetric matrix you can always choose an orthonormal eigenbasis: S = Q Λ Qᵀ.',
          {'Nothing: eigenvectors of any matrix are perpendicular': 'For A = [[4, 1], [2, 3]] above, [1, 1] and [1, −2] have dot product −1.'}),
   num('Compute xᵀ S x for x = [1, −1].', 2, ['S x = [1, −1].'], 'xᵀSx = [1, −1]·[1, −1] = 2 = λ·||x||² with λ = 1.', tol=0),
   choice('Is S positive definite (xᵀSx > 0 for every x ≠ 0)?', 'Yes: both eigenvalues are positive', ['No: it has an off-diagonal entry', 'Only if x has positive entries'],
          ['Write x in the eigenbasis: xᵀSx = 3c1² + 1c2².'], 'All eigenvalues positive means positive definite: a bowl-shaped quadratic with a unique minimum.'),
  ],
  [step('Eigenvalues 3 and 1 with eigenvectors [1, 1] and [1, −1], which are perpendicular.'),
   step('xᵀSx for x = [1, −1]: S x = [1, −1], so the value is 2.'),
   step('In the eigenbasis xᵀSx = 3c1² + c2² > 0 unless x = 0: positive definite.')],
  'Covariance matrices and Hessians are symmetric; their eigenvalues are the variances along principal directions and the curvatures of a loss.'),
 ])

# ---------------- Matrix decompositions ----------------
Asvd = np.array([[3,0],[4,5]], float); sv = np.linalg.svd(Asvd, compute_uv=False)
homework('math/matrix-decompositions', 'math', 'Matrix decompositions',
 'LU, Cholesky and the singular value decomposition.',
 [
 problem('lu', 'Solve with LU', ['lu-decomposition'],
  'A = [[2, 1], [4, 5]] and b = [3, 13].',
  [
   num('Eliminate below the first pivot. What multiplier l₂₁ do you use?', 2, ['l₂₁ = (entry to eliminate)/(pivot) = 4/2.'], 'l₂₁ = 2, so L = [[1, 0], [2, 1]].', tol=0),
   num('What is U₂₂, the second pivot?', 3, ['Row 2 − 2·row 1 = [4 − 4, 5 − 2].'], 'U = [[2, 1], [0, 3]], so U₂₂ = 3.', tol=0),
   vec('Solve L y = b, then U x = y. Enter x (3 decimals).', np.linalg.solve([[2,1],[4,5]],[3,13]),
       ['Forward: y1 = 3, y2 = 13 − 2·3.', 'y = [3, 7]. Back: 3x2 = 7.'], 'x2 = 7/3 and x1 = (3 − 7/3)/2 = 1/3.', tol=0.005),
  ],
  [step('l₂₁ = 4/2 = 2; U = [[2, 1], [0, 3]], L = [[1, 0], [2, 1]].'),
   step('L y = b: y = [3, 13 − 6] = [3, 7].'),
   step('U x = y: x2 = 7/3 ≈ 2.333, x1 = (3 − 7/3)/2 = 1/3 ≈ 0.333. Check A x = [3, 13].')],
  'Factor once, then solve cheaply for many right-hand sides: that is why libraries compute LU instead of an inverse.'),
 problem('chol', 'Cholesky of a covariance matrix', ['cholesky-decomposition'],
  'S = [[4, 2], [2, 5]] is symmetric positive definite. Find the lower-triangular L with S = L Lᵀ.',
  [
   num('L₁₁ = sqrt(S₁₁). Compute it.', 2, ['sqrt(4).'], 'L₁₁ = 2.', tol=0),
   num('L₂₁ = S₂₁ / L₁₁. Compute it.', 1, [], 'L₂₁ = 2/2 = 1.', tol=0),
   num('L₂₂ = sqrt(S₂₂ − L₂₁²). Compute it.', 2, ['5 − 1 = 4.'], 'L₂₂ = 2, so L = [[2, 0], [1, 2]].', tol=0),
   num('Use L to get det S.', 16, ['det(L Lᵀ) = det(L)², and det of a triangular matrix is the product of its diagonal.'], 'det S = (2·2)² = 16 = 4·5 − 2·2.', tol=0),
  ],
  [step('L₁₁ = 2, L₂₁ = 1, L₂₂ = sqrt(5 − 1) = 2; check L Lᵀ = [[4, 2], [2, 5]].'),
   step('det S = (L₁₁ L₂₂)² = 16.')],
  'Multiplying standard normal samples by L gives samples with covariance S: this is how correlated Gaussian data are simulated.'),
 problem('svd', 'SVD and compression', ['svd'],
  'A = [[3, 0], [4, 5]].',
  [
   vec('The singular values are the square roots of the eigenvalues of AᵀA = [[25, 20], [20, 25]]. Enter them, largest first (3 decimals).', sv,
       ['The eigenvalues of [[25, 20], [20, 25]] are 25 ± 20.', 'sqrt(45) and sqrt(5).'], f'σ₁ = sqrt 45 ≈ {r(sv[0],3)} and σ₂ = sqrt 5 ≈ {r(sv[1],3)}.', tol=0.005,
       mistakes=[([45, 5], 'Those are the eigenvalues of AᵀA. The singular values are their square roots.')]),
   num('Compute ||A||²_F, the sum of the squared entries.', 50, ['9 + 0 + 16 + 25.'], '50 = σ₁² + σ₂² = 45 + 5.', tol=0),
   num('The best rank-1 approximation keeps σ₁ only. What is its error ||A − A₁||_F (3 decimals)?', sv[1],
       ['The error is made of the dropped singular values.'], f'The error is σ₂ = sqrt 5 ≈ {r(sv[1],3)}.'),
   num('What fraction of ||A||²_F does the rank-1 approximation keep?', 0.9, ['σ₁²/(σ₁² + σ₂²).'], '45/50 = 0.9.'),
  ],
  [step('AᵀA has eigenvalues 45 and 5, so σ₁ = sqrt 45 ≈ 6.708 and σ₂ = sqrt 5 ≈ 2.236.'),
   step('||A||²_F = 9 + 16 + 25 = 50 = 45 + 5.'),
   step('Dropping σ₂ leaves error sqrt 5 and keeps 45/50 = 90% of the squared size.')],
  'Image compression and PCA both keep the largest singular values; the dropped ones measure exactly what is lost.'),
 ])

# ---------------- Vector calculus ----------------
homework('math/vector-calculus', 'math', 'Vector calculus',
 'Gradients, the chain rule, backpropagation, and second-order Taylor approximations.',
 [
 problem('grad', 'Gradients and directions', ['partial-derivatives-gradient'],
  'f(x, y) = x²y + 3y.',
  [
   vec('Compute the gradient ∇f at (1, 2).', [4, 4],
       ['∂f/∂x treats y as a constant: 2xy.', '∂f/∂y treats x as a constant: x² + 3.'], '∇f = [2xy, x² + 3] = [4, 4] at (1, 2).', tol=0),
   num('Compute the rate of change of f at (1, 2) in the direction u = [3, 4]/5.', 5.6,
       ['The directional derivative is ∇f · u.', 'u must be a unit vector; [3, 4]/5 is.'], '[4, 4]·[0.6, 0.8] = 2.4 + 3.2 = 5.6.',
       mistakes=[(28, 'Divide [3, 4] by its length 5 first: the direction must be a unit vector.')]),
   num('What is the largest possible rate of change at (1, 2), over all unit directions (3 decimals)?', np.sqrt(32),
       ['The steepest direction is the gradient itself.', 'The steepest rate is ||∇f||.'], f'||[4, 4]|| = sqrt 32 ≈ {r(np.sqrt(32),3)}, larger than 5.6.'),
  ],
  [step('∇f = [2xy, x² + 3] = [4, 4] at (1, 2).'),
   step('Directional derivative along [0.6, 0.8]: 2.4 + 3.2 = 5.6.'),
   step('Steepest ascent is along ∇f with rate ||∇f|| = sqrt 32 ≈ 5.657; gradient descent steps the opposite way.')],
  'Gradient descent uses exactly this fact: −∇f is the direction in which the loss falls fastest.'),
 problem('chain', 'Backpropagation through one neuron', ['jacobian-chain-rule', 'backpropagation', 'loss-gradients'],
  'z = w x + b, a = σ(z), L = (a − y)². Take x = 2, w = 0.5, b = −1, y = 1.',
  [
   num('Forward pass: compute L.', 0.25, ['z = 0.5·2 − 1 = 0.', 'σ(0) = 0.5.'], 'z = 0, a = 0.5, L = (0.5 − 1)² = 0.25.'),
   num('Compute ∂L/∂w.', -0.5,
       ['Chain rule: ∂L/∂w = ∂L/∂a · ∂a/∂z · ∂z/∂w.', '∂L/∂a = 2(a − y), ∂a/∂z = σ(z)(1 − σ(z)), ∂z/∂w = x.', '2(0.5 − 1) = −1; σ\'(0) = 0.25; x = 2. Multiply.'],
       '−1 · 0.25 · 2 = −0.5.',
       mistakes=[(-0.25, 'That is ∂L/∂b (∂z/∂b = 1). For w, multiply by ∂z/∂w = x = 2.'), (-2, 'Include ∂a/∂z = σ(0)(1 − σ(0)) = 0.25.')]),
   num('Compute ∂L/∂b.', -0.25, ['Same chain, but ∂z/∂b = 1.'], '−1 · 0.25 · 1 = −0.25.'),
   num('Take one gradient step with learning rate 0.4. What is the new w?', 0.7, ['w ← w − 0.4·∂L/∂w.'], '0.5 − 0.4·(−0.5) = 0.7: w grows, pushing a toward y = 1.',
       mistakes=[(0.3, 'Gradient descent subtracts the gradient: 0.5 − 0.4·(−0.5).')]),
  ],
  [step('Forward: z = 0, a = σ(0) = 0.5, L = 0.25.'),
   step('Backward: ∂L/∂a = 2(a − y) = −1, ∂a/∂z = 0.25, so ∂L/∂z = −0.25; ∂L/∂w = −0.25·x = −0.5 and ∂L/∂b = −0.25.', r'\frac{\partial L}{\partial w}=\frac{\partial L}{\partial a}\,\frac{\partial a}{\partial z}\,\frac{\partial z}{\partial w}=(-1)(0.25)(2)'),
   step('Update: w = 0.5 − 0.4(−0.5) = 0.7.')],
  'Backpropagation is this chain rule applied layer by layer, reusing ∂L/∂z from the layer above.'),
 problem('taylor', 'Taylor approximation and the Hessian', ['taylor-hessian'],
  'f(x, y) = x² + xy + 2y². Expand around (1, 1) and estimate f(1.1, 0.9).',
  [
   vec('Compute ∇f(1, 1).', [3, 5], ['∇f = [2x + y, x + 4y].'], '[3, 5].', tol=0),
   num('First-order estimate: f(1, 1) + ∇f · h with h = [0.1, −0.1].', 3.8, ['f(1, 1) = 4.', '∇f · h = 0.3 − 0.5.'], '4 − 0.2 = 3.8.'),
   num('Second-order estimate: add ½ hᵀ H h with Hessian H = [[2, 1], [1, 4]].', 3.82,
       ['H h = [0.2 − 0.1, 0.1 − 0.4] = [0.1, −0.3].', 'hᵀ H h = 0.01 + 0.03 = 0.04.'],
       '3.8 + 0.02 = 3.82, which is exact: a quadratic equals its second-order Taylor expansion.'),
   choice('The only stationary point is (0, 0). What is it?', 'A minimum: both eigenvalues of H are positive', ['A maximum', 'A saddle point', 'Cannot tell without more derivatives'],
          ['The eigenvalues of [[2, 1], [1, 4]] are 3 ± sqrt 2.'], 'Both eigenvalues (about 4.41 and 1.59) are positive, so H is positive definite and (0, 0) is a minimum.'),
  ],
  [step('∇f(1, 1) = [3, 5]; first order: 4 + 0.3 − 0.5 = 3.8.'),
   step('Second order: ½ hᵀHh = ½·0.04 = 0.02, giving 3.82 = f(1.1, 0.9).'),
   step('H has eigenvalues 3 ± sqrt 2 > 0, so (0, 0) is a minimum.')],
  'The Hessian\'s eigenvalues are the curvatures that set gradient descent\'s safe step size (below 2/L) and its speed (the condition number L/μ).'),
 ])

# ---------------- Probability and statistics ----------------
pd = 0.02*0.95/(0.02*0.95+0.98*0.04); pd2 = pd*0.95/(pd*0.95+(1-pd)*0.04)
homework('math/probability-and-statistics', 'math', 'Probability and statistics',
 'Bayes\' rule, expectation and variance, and maximum likelihood.',
 [
 problem('bayes', 'Screening with Bayes\' rule', ['probability-basics'],
  'A condition affects 2% of people. A test detects it 95% of the time (sensitivity) and gives false positives for 4% of healthy people.',
  [
   num('Compute P(positive) (4 decimals).', 0.02*0.95+0.98*0.04,
       ['Sum rule: P(+) = P(+ | sick)P(sick) + P(+ | healthy)P(healthy).', '0.95·0.02 + 0.04·0.98.'], '0.019 + 0.0392 = 0.0582.', tol=0.0005),
   num('Compute P(sick | positive) (3 decimals).', pd,
       ['Bayes: P(sick | +) = P(+ | sick)P(sick)/P(+).', '0.019/0.0582.'], f'{r(pd,3)}: two thirds of positives are false alarms, because healthy people are so common.',
       mistakes=[(0.95, 'That is P(+ | sick), the sensitivity. Bayes\' rule reverses the condition.')]),
   num('A second, independent test is also positive. Using your answer as the new prior, compute P(sick | two positives) (3 decimals).', pd2,
       ['Repeat Bayes\' rule with P(sick) replaced by your previous answer.', f'{r(pd,4)}·0.95 / ({r(pd,4)}·0.95 + {r(1-pd,4)}·0.04).'],
       f'{r(pd2,3)}: evidence accumulates by multiplying likelihoods.'),
  ],
  [step('P(+) = 0.95·0.02 + 0.04·0.98 = 0.0582.'),
   step(f'P(sick | +) = 0.019/0.0582 ≈ {r(pd,4)}.', r'P(\text{sick}\mid+)=\frac{P(+\mid\text{sick})\,P(\text{sick})}{P(+)}'),
   step(f'Second test: {r(pd,4)}·0.95/({r(pd,4)}·0.95 + {r(1-pd,4)}·0.04) ≈ {r(pd2,4)}.')],
  'Precision is P(actually positive | predicted positive): with rare positives, even a good classifier has low precision unless its false-positive rate is tiny.'),
 problem('expvar', 'Expectation and variance', ['expectation-variance'],
  'X is the result of one fair six-sided die.',
  [
   num('Compute E[X].', 3.5, ['Average of 1 to 6.'], '(1 + ... + 6)/6 = 3.5.'),
   num('Compute Var(X) (3 decimals).', 35/12, ['Var = E[X²] − (E[X])².', 'E[X²] = (1 + 4 + 9 + 16 + 25 + 36)/6 = 91/6.'], f'91/6 − 12.25 = 35/12 ≈ {r(35/12,3)}.',
       mistakes=[(3.5, 'That is the mean. Variance is E[X²] − (E[X])².')]),
   num('Compute Var(2X + 1) (3 decimals).', 4*35/12, ['Adding a constant does not change spread; scaling by 2 multiplies the variance by 4.'], f'4·35/12 ≈ {r(35/3,3)}.',
       mistakes=[(2*35/12+1, 'Var(aX + b) = a² Var(X): the +1 drops out and the 2 is squared.'), (2*35/12, 'The scale factor is squared: 2² = 4.')]),
   num('What is the standard deviation of the average of 25 rolls (3 decimals)?', np.sqrt(35/12/25), ['Var(average of n) = Var(X)/n.', 'Then take the square root.'], f'sqrt(2.917/25) ≈ {r(np.sqrt(35/12/25),3)}.'),
  ],
  [step('E[X] = 3.5, E[X²] = 91/6, Var(X) = 35/12 ≈ 2.917.'),
   step('Var(2X + 1) = 4 Var(X) ≈ 11.667.'),
   step('The average of 25 rolls has variance 2.917/25, standard deviation ≈ 0.342.')],
  'Averages are less variable than single values by a factor 1/n in variance. That is why larger validation sets and k-fold averaging give steadier estimates.'),
 problem('mle', 'Maximum likelihood', ['likelihood-mle'],
  'Ten coin flips give 7 heads.',
  [
   num('What value of μ = P(heads) maximizes the likelihood μ⁷(1 − μ)³?', 0.7,
       ['Take logs: ℓ(μ) = 7 ln μ + 3 ln(1 − μ).', 'Set dℓ/dμ = 7/μ − 3/(1 − μ) = 0.'], 'μ̂ = 7/10 = 0.7.'),
   num('Compute ℓ(0.7) − ℓ(0.5), how much higher the log-likelihood is at the maximum than at a fair coin (3 decimals).', (7*np.log(.7)+3*np.log(.3))-10*np.log(.5),
       ['ℓ(0.7) = 7 ln 0.7 + 3 ln 0.3 and ℓ(0.5) = 10 ln 0.5.'], f'{r(7*np.log(.7)+3*np.log(.3),3)} − ({r(10*np.log(.5),3)}) ≈ {r((7*np.log(.7)+3*np.log(.3))-10*np.log(.5),3)}.'),
   vec('For Gaussian data 2, 4, 9, give the maximum likelihood estimates of the mean and the variance.', [5, 26/3],
       ['The MLE of the mean is the sample average.', 'The MLE of the variance divides the sum of squared deviations by n, not n − 1.'],
       'Mean 5 and variance (9 + 1 + 16)/3 = 26/3 ≈ 8.667 (the unbiased estimate would divide by 2).', tol=0.005,
       mistakes=[([5, 13], 'Dividing by n − 1 gives the unbiased estimate. Maximum likelihood divides by n.')]),
  ],
  [step('dℓ/dμ = 7/μ − 3/(1 − μ) = 0 gives μ = 0.7.'),
   step(f'ℓ(0.7) ≈ {r(7*np.log(.7)+3*np.log(.3),4)}, ℓ(0.5) ≈ {r(10*np.log(.5),4)}, difference ≈ {r((7*np.log(.7)+3*np.log(.3))-10*np.log(.5),4)}.'),
   step('Gaussian MLE: mean 5, variance 26/3 ≈ 8.667.')],
  'Least squares is maximum likelihood with Gaussian noise, and the logistic loss is maximum likelihood with Bernoulli labels.'),
 ])

# ---------------- Dimensionality reduction ----------------
P4 = np.array([[3,1],[1,3],[-1,-3],[-3,-1]], float); C4 = P4.T@P4/4
homework('math/dimensionality-reduction', 'math', 'Dimensionality reduction',
 'Principal component analysis: covariance, eigenvectors, and how many components to keep.',
 [
 problem('pca', 'PCA by hand', ['pca', 'dimensionality-reduction'],
  'Four centred points: (3, 1), (1, 3), (−1, −3), (−3, −1). Use the covariance that divides by n = 4.',
  [
   vec('Compute the covariance matrix (4 numbers, row by row).', C4.flatten(),
       ['The mean is already 0, so C = (1/4) Σ x xᵀ.', 'C₁₁ = (9 + 1 + 1 + 9)/4; C₁₂ = (3 + 3 + 3 + 3)/4.'], 'C = [[5, 3], [3, 5]].', tol=0),
   vec('Find its eigenvalues, largest first.', [8, 2], ['trace 10, det 16.'], '8 (direction [1, 1]/sqrt 2) and 2 (direction [1, −1]/sqrt 2).', tol=1e-6),
   num('What fraction of the variance does the first principal component explain?', 0.8, ['λ₁/(λ₁ + λ₂).'], '8/10 = 0.8.'),
   num('Compute the first principal-component score of the point (3, 1) (3 decimals).', 4/np.sqrt(2),
       ['The score is the dot product with the unit vector [1, 1]/sqrt 2.'], f'(3 + 1)/sqrt 2 ≈ {r(4/np.sqrt(2),3)}.',
       mistakes=[(4, 'Use the unit vector [1, 1]/sqrt 2, not [1, 1].')]),
   num('Keeping one component, what is the average squared reconstruction error per point?', 2, ['It equals the dropped eigenvalue (with the 1/n covariance).'], 'The dropped eigenvalue, 2.'),
  ],
  [step('C = [[5, 3], [3, 5]], with eigenvalues 8 and 2 and eigenvectors [1, 1]/sqrt 2 and [1, −1]/sqrt 2.'),
   step('PC1 explains 8/10 = 80%. The score of (3, 1) is 4/sqrt 2 ≈ 2.828.'),
   step('The reconstruction from PC1 misses the [1, −1] component; its average squared size is the dropped eigenvalue 2.')],
  'PCA picks the directions of largest variance, and the eigenvalues tell you exactly how much is kept or lost.'),
 problem('howmanypc', 'How many components?', ['pca'],
  'A covariance matrix has eigenvalues 6, 2.5, 1, 0.3 and 0.2.',
  [
   num('What is the total variance?', 10, ['It is the trace: the sum of the eigenvalues.'], '10.', tol=0),
   num('What is the smallest number of components that keeps at least 90% of the variance?', 3,
       ['Add eigenvalues from the largest until you reach 9.'], '6 + 2.5 = 8.5 (85%) is not enough; adding 1 gives 9.5 (95%): 3 components.', tol=0),
   num('With 2 components, what is the average squared reconstruction error?', 1.5, ['Sum the dropped eigenvalues.'], '1 + 0.3 + 0.2 = 1.5.'),
   choice('Features are measured in very different units. What should you do before PCA?', 'Standardize them, otherwise the feature with the largest units dominates',
          ['Nothing: PCA is scale-invariant', 'Remove the mean only after PCA', 'Multiply all features by 10'],
          ['What happens to the variance of a feature in grams versus kilograms?'], 'Variance grows with the square of the units, so without standardizing PCA mostly finds the feature with the largest numbers.'),
  ],
  [step('Total variance = trace = 10.'),
   step('Cumulative: 60%, 85%, 95%: keep 3 components for 90%.'),
   step('Dropping 1, 0.3 and 0.2 loses 1.5 on average.'),
   step('Standardize first when units differ.')],
  'The same eigenvalue bookkeeping underlies scree plots and the explained-variance ratio in scikit-learn\'s PCA.'),
 ])
