from lib import *

# Design rules (from the student trial and the professors' review):
# - numbers differ from the pages' worked examples, so the method has to be redone, not copied;
# - prompts ask for the quantity, the formula lives in the clues (idea first, worked step last);
# - every problem has at least one predict / explain / transfer part;
# - predictable mistakes get feedback that diagnoses without giving the answer.

# ---------------- Foundations ----------------
p = np.array([0.9, 0.5, 0.8])
L = p.prod(); ll = np.log(p).sum(); ll4 = (ll + np.log(0.01))
homework('math/foundations', 'math', 'Foundations',
 'Functions, inverses, logarithms, and the vector tools (dot products and norms) that every later page uses.',
 [
 problem('compose', 'Composing and undoing functions', ['functions', 'inverse-composition'],
  'Let f(x) = 2x + 3 and g(x) = x².',
  [
   num('Compute (g ∘ f)(1).', 25,
       ['Which function acts first in g ∘ f? Read the Composition section of the page.', 'g ∘ f means "do f first, then g": find f(1), then apply g to it.'],
       '(g ∘ f)(1) = g(f(1)) = g(5) = 25. The order matters: (f ∘ g)(1) = f(1) = 5.', tol=0,
       mistakes=[(5, 'That is (f ∘ g)(1): you applied g first. In g ∘ f the function written on the right acts first.')]),
   num('Find f⁻¹(11), the input that f sends to 11.', 4,
       ['The inverse undoes f: you want the x with f(x) = 11.', 'Undo the steps of f in reverse order: first subtract 3, then divide by 2.'],
       'f⁻¹(y) = (y − 3)/2, so f⁻¹(11) = 4. Check: f(4) = 11.', tol=0,
       mistakes=[(1/11, 'The inverse function is not the reciprocal 1/y. It undoes f: f(f⁻¹(y)) = y.'), (25, 'That applies f to 11. The inverse goes the other way: which x gives f(x) = 11?')]),
   choice('Does g(x) = x² have an inverse on all real numbers?', 'No', ['Yes', 'Only if we use sqrt'],
          ['A function has an inverse only if different inputs always give different outputs. Try two inputs with the same square.'],
          'g(2) = g(−2) = 4, so an output does not tell you the input. sqrt(x) is an inverse only on x ≥ 0.',
          {'Yes': 'Which x gives g(x) = 4: 2 or −2? An inverse would have to return both.', 'Only if we use sqrt': 'sqrt(4) = 2, but g(−2) = 4 as well: sqrt cannot recover −2. It is an inverse only after restricting to x ≥ 0.'}),
  ],
  [step('Composition applies the right-hand function first: (g ∘ f)(1) = g(f(1)) = g(5) = 25.'),
   step('To invert f, solve y = 2x + 3 for x: x = (y − 3)/2, so f⁻¹(11) = 4.'),
   step('g(2) = g(−2) = 4, so g is not one-to-one on the real line and has no inverse there. On x ≥ 0 its inverse is sqrt(x).')],
  'Composition order and invertibility come back in matrices: (AB)x applies B first, and a matrix is invertible exactly when no two inputs share an output.'),
 problem('logs', 'Logs turn products into sums', ['exp-log'],
  'A classifier gives the true labels of three examples probabilities 0.9, 0.5 and 0.8.',
  [
   num('The likelihood is the product of the three probabilities. Compute it.', L,
       ['Multiply the three numbers.', '0.9 × 0.5 first, then multiply by 0.8.'],
       f'0.9 × 0.5 × 0.8 = {r(L)}. With thousands of examples such products become tiny, which is why we take logs.'),
   num('Compute the log-likelihood, the sum of the natural logs of the three probabilities (3 decimals).', ll,
       ['ln(ab) = ln a + ln b, so this equals the log of your previous answer.', 'ln 0.9 ≈ −0.105 and ln 0.5 ≈ −0.693; add ln 0.8.'],
       f'ln 0.9 + ln 0.5 + ln 0.8 = {r(ll,3)} = ln {r(L)}. Logs of probabilities are negative because the probabilities are below 1.',
       mistakes=[(-ll, 'Check the sign: the log of a number between 0 and 1 is negative.'), (np.log10(p).sum(), 'That uses base-10 logs. In ML "log" means the natural log, ln.')]),
   num('The average negative log-likelihood is the logistic loss. Compute it for the three examples (3 decimals).', -ll/3,
       ['"Negative" flips the sign of the log-likelihood; "average" divides by the number of examples.', 'Take minus your previous answer and divide by 3.'],
       f'{r(-ll/3,3)}. Minimizing this average loss is the same as maximizing the likelihood, because ln is increasing.',
       mistakes=[(-ll, 'That is the total negative log-likelihood. Divide by the 3 examples.'), (ll/3, 'Flip the sign: the loss is the negative log-likelihood, a positive number.')]),
   num('A fourth example gets probability 0.01 for its true label. Compute the new average negative log-likelihood over all four (3 decimals).', -ll4/4,
       ['Add the fourth example\'s −ln 0.01 to the total you had, then average over four.', '−ln 0.01 ≈ 4.605.'],
       f'The average jumps to {r(-ll4/4,3)}: one confident mistake more than quadruples the loss. Log loss punishes confident errors hard.',
       mistakes=[(-ll/3, 'Include the fourth example: add −ln 0.01 to the total and divide by 4.'), (-np.log(0.01), 'That is the fourth example alone. Average over all four.')]),
  ],
  [step(f'Likelihood: 0.9 · 0.5 · 0.8 = {r(L)}.'),
   step(f'Log-likelihood: ln 0.9 + ln 0.5 + ln 0.8 = −0.1054 − 0.6931 − 0.2231 = {r(ll,4)}.', r'\ln(0.9\cdot0.5\cdot0.8)=\ln0.9+\ln0.5+\ln0.8'),
   step(f'Average negative log-likelihood: {r(-ll,4)}/3 = {r(-ll/3,4)}.'),
   step(f'With the fourth example: ({r(-ll,4)} + 4.6052)/4 = {r(-ll4/4,4)}.')],
  'Every likelihood-based loss (logistic loss, cross-entropy) is this computation, and its steep −ln p near p = 0 is why a model is punished so hard for being confidently wrong.'),
 problem('dot', 'Dot products, norms and angles', ['vectors-dot-product', 'norms'],
  'Let u = [1, 2, 2] and v = [2, 0, 1].',
  [
   num('Compute u · v.', 4, ['Multiply matching entries.', 'Add the three products 1·2, 2·0 and 2·1.'], 'u · v = 2 + 0 + 2 = 4.', tol=0),
   num('Compute the Euclidean length ||u||₂.', 3, ['Square the entries and add them.', 'Take the square root of 1 + 4 + 4.'], '||u||₂ = sqrt(9) = 3.', tol=0,
       mistakes=[(9, 'That is ||u||² (the squared length). Take the square root.'), (5, 'That is the L1 norm, the sum of absolute values.')]),
   num('Compute ||u||₁ (the L1 norm).', 5, ['The L1 norm uses absolute values, not squares.', 'Add |1|, |2| and |2|.'], '|1| + |2| + |2| = 5.', tol=0,
       mistakes=[(3, 'That is the L2 norm. L1 adds the absolute values.')]),
   num('Compute the cosine of the angle between u and v (3 decimals).', 4/(3*np.sqrt(5)),
       ['The cosine is the dot product divided by both lengths.', 'You have u · v and ||u||; ||v|| = sqrt(4 + 0 + 1).'],
       f'cos = 4/(3·sqrt 5) ≈ {r(4/(3*np.sqrt(5)),3)}, an angle of about {r(np.degrees(np.arccos(4/(3*np.sqrt(5)))),1)} degrees. Positive: the vectors point roughly the same way.',
       mistakes=[(4/15, 'Use the Euclidean lengths ||u||₂ and ||v||₂, not ||v||² or an L1 norm.'), (4/3, 'Divide by both lengths, ||u|| and ||v||. A cosine is never above 1.')]),
  ],
  [step('u · v = 1·2 + 2·0 + 2·1 = 4.'),
   step('||u||₂ = sqrt(1 + 4 + 4) = 3 and ||u||₁ = 1 + 2 + 2 = 5.'),
   step(f'||v||₂ = sqrt 5, so cos = 4/(3 sqrt 5) ≈ {r(4/(3*np.sqrt(5)),3)}.', r'\cos\angle(u,v)=\frac{u\cdot v}{\lVert u\rVert\,\lVert v\rVert}=\frac{4}{3\sqrt5}')],
  'A linear model\'s score θ · x is a dot product: large and positive when x points along θ. The norms return as penalties in ridge (L2) and lasso (L1).'),
 ])

# ---------------- Matrices and linear systems ----------------
A = np.array([[1,0,2],[-1,3,1]]); B = np.array([[3,1],[2,1],[1,0]]); AB = A@B
homework('math/matrices-and-linear-systems', 'math', 'Matrices and linear systems',
 'Matrix shapes and products, and solving linear systems by elimination.',
 [
 problem('shapes', 'Shapes, products and rank one', ['matrix-operations', 'matrix-multiplication-outer-product', 'linear-independence'],
  'A = [[1, 0, 2], [−1, 3, 1]] is 2 by 3 and B = [[3, 1], [2, 1], [1, 0]] is 3 by 2.',
  [
   choice('What is the shape of AB?', '2 by 2', ['3 by 3', '2 by 3', 'AB is not defined'],
          ['(m by n) times (n by p) gives m by p: the inner sizes must match and cancel.'],
          'The inner sizes cancel: (2 by 3)(3 by 2) = 2 by 2. BA would be 3 by 3.',
          {'3 by 3': 'That is the shape of BA. In AB the rows come from A and the columns from B.', '2 by 3': 'The 3 in the middle cancels; the outer sizes remain.', 'AB is not defined': 'Compare A\'s number of columns with B\'s number of rows.'}),
   vec('Compute AB. Enter its entries row by row, separated by commas (4 numbers).', AB.flatten(),
       ['Entry (i, j) is row i of A dotted with column j of B.', 'Entry (1,1) = [1, 0, 2] · [3, 2, 1] = 5. Do the same for the other three.'],
       f'AB = [[{AB[0,0]}, {AB[0,1]}], [{AB[1,0]}, {AB[1,1]}]].', tol=0,
       mistakes=[([5, 4, 1, 2], 'Right numbers, wrong order: enter row 1 first (entries (1,1), (1,2)), then row 2.')]),
   num('The rank of a matrix is its number of independent rows. The outer product of u = [1, 2] and v = [3, −1, 0] is the 2 by 3 matrix u vᵀ. What is its rank?', 1,
       ['Write out u vᵀ: row i is uᵢ times vᵀ.', 'Row 2 is 2 times row 1. How many independent rows is that?'],
       'Every row is a multiple of vᵀ, so the rank is 1.', tol=0,
       mistakes=[(2, 'Row 2 = [6, −2, 0] is exactly twice row 1, so the rows are not independent.')]),
   num('Now add a second outer product w zᵀ with w = [0, 1] and z = [0, 0, 1]. What is the rank of u vᵀ + w zᵀ?', 2,
       ['Write out the sum. Only one entry changes.', 'The sum is [[3, −1, 0], [6, −2, 1]]. Is row 2 still a multiple of row 1?'],
       'Row 2 is no longer twice row 1, so the rank is 2. Each outer product adds at most one to the rank, which is why the SVD writes a matrix as a sum of rank-one pieces.', tol=0,
       mistakes=[(1, 'Check row 2 of the sum: [6, −2, 1] is not a multiple of [3, −1, 0].')]),
  ],
  [step('Shapes: (2 by 3)(3 by 2) = 2 by 2.'),
   step('Row 1 of A times the columns of B: 5 and 1. Row 2: 4 and 2. So AB = [[5, 1], [4, 2]].'),
   step('u vᵀ = [[3, −1, 0], [6, −2, 0]]: row 2 = 2·row 1, rank 1.'),
   step('Adding w zᵀ puts a 1 in position (2, 3): [[3, −1, 0], [6, −2, 1]] has rank 2.')],
  'In ML, X θ multiplies an n by d data matrix by a d-vector, and XᵀX is d by d. Checking shapes catches most bugs; rank tells you how many independent directions the data really have.'),
 problem('eliminate', 'Solve by elimination', ['matrix-systems', 'gaussian-elimination'],
  'Solve the system  x + y + z = 6,  2x + y − z = 1,  x − y + 2z = 5.',
  [
   num('Eliminate x from row 2 using row 1. What is the right-hand side of the new row 2?', -11,
       ['Choose the multiple of row 1 that cancels the x in row 2.', 'Subtract twice the whole of row 1 from row 2, including its right-hand side.'],
       'Row 2 − 2·row 1 = [0, −1, −3 | −11].', tol=0,
       mistakes=[(-5, 'You subtracted row 1 once. The multiplier is 2, because the x-coefficient in row 2 is 2.'), (11, 'Check the sign of 1 − 2·6.'), (13, 'You added instead of subtracting.')]),
   vec('Finish the elimination and back-substitute. Enter x, y, z.', [1, 2, 3],
       ['Also eliminate x from row 3, then use the new row 2 to eliminate y from row 3.', 'Row 3 − row 1 = [0, −2, 1 | −1]; subtracting 2·(new row 2) leaves 7z = 21. Back-substitute upwards.'],
       'z = 3, y = 2, x = 1.', tol=1e-6),
   choice('How can you be sure the answer is right without redoing the elimination?', 'Substitute it into all three original equations', ['Substitute it into the last row of the eliminated system', 'Check that the numbers are integers', 'Check that the determinant is not zero'],
          ['A solution must satisfy every equation you started with.'],
          '1 + 2 + 3 = 6, 2 + 2 − 3 = 1, 1 − 2 + 6 = 5. In code: np.linalg.solve plus a residual check A x − b ≈ 0.',
          {'Substitute it into the last row of the eliminated system': 'That only checks the last step; an arithmetic slip earlier would go unnoticed.', 'Check that the determinant is not zero': 'That shows a unique solution exists, not that yours is it.'}),
  ],
  [step('Row 2 − 2·row 1: [0, −1, −3 | −11]. Row 3 − row 1: [0, −2, 1 | −1].'),
   step('Row 3 − 2·(new row 2): [0, 0, 7 | 21], so z = 3.'),
   step('−y − 9 = −11 gives y = 2; x + 2 + 3 = 6 gives x = 1. Check in all three original equations.')],
  'Elimination is what np.linalg.solve does (as an LU factorization). The normal equation of least squares is solved exactly this way.'),
 problem('howmany', 'None, one, or infinitely many?', ['solution-structure'],
  'Consider x + 2y = 3 and 2x + 4y = c, for a number c.',
  [
   num('For which value of c does the system have infinitely many solutions?', 6,
       ['Compare the left-hand sides of the two equations.', 'The second left side is exactly twice the first. What must the right side be for the equations to agree?'],
       'With c = 6 the second equation is just twice the first, so it adds no information: a whole line of solutions.', tol=0,
       mistakes=[(3, 'The left side of equation 2 is doubled, so its right side must be doubled too.')]),
   choice('For c = 6, which vector spans the null space (the directions you can move without changing the left-hand sides)?', '[−2, 1]', ['[1, 2]', '[3, 0]', '[2, 1]'],
          ['Solve x + 2y = 0: if y = 1, what must x be?'],
          'x + 2y = 0 gives x = −2y, so the null space is spanned by [−2, 1]. All solutions are [3, 0] + t[−2, 1].',
          {'[1, 2]': '[1, 2] is the row of coefficients, which is perpendicular to the null space: 1 + 4 ≠ 0.', '[3, 0]': '[3, 0] solves the system itself; a null-space direction must give 0 on the left.', '[2, 1]': '2 + 2·1 = 4, not 0.'}),
   choice('How many solutions are there for c = 5?', 'None', ['Exactly one', 'Infinitely many', 'Two'],
          ['Double the first equation and compare with the second.'],
          'Doubling the first gives 2x + 4y = 6, which contradicts 2x + 4y = 5: no solution.',
          {'Infinitely many': 'The left sides are proportional, but the right sides are not: the equations contradict each other.', 'Exactly one': 'One solution needs the two lines to cross; these two are parallel.'}),
  ],
  [step('Equation 2 has left side 2·(x + 2y). It is consistent only when c = 2·3 = 6.'),
   step('Then all solutions are x = 3 − 2t, y = t, that is [3, 0] + t[−2, 1]: a particular solution plus the null space.'),
   step('For any other c, such as 5, the two equations contradict each other and there is no solution.')],
  'This is why the normal equation can fail: if two features are exact copies, XᵀX is singular and there are infinitely many least-squares solutions.'),
 ])

# ---------------- Vector spaces ----------------
homework('math/vector-spaces', 'math', 'Vector spaces',
 'Span, independence, subspaces, bases and dimension.',
 [
 problem('independent', 'Independent or not?', ['span-linear-combinations', 'linear-independence', 'dimension'],
  'Let v1 = [1, 0, 1], v2 = [0, 1, 1] and v3 = [1, 1, 2].',
  [
   vec('Find numbers a and b with v3 = a·v1 + b·v2. Enter a, b.', [1, 1],
       ['Write a·v1 + b·v2 as a single vector with entries in terms of a and b.', 'a·v1 + b·v2 = [a, b, a + b]; match it with [1, 1, 2].'],
       'a = 1 and b = 1: v3 = v1 + v2.', tol=1e-6),
   num('What is the rank of the matrix with columns v1, v2, v3?', 2,
       ['The rank counts independent columns.', 'v3 adds nothing new. Are v1 and v2 multiples of each other?'],
       'v1 and v2 are independent and v3 depends on them: rank 2.', tol=0,
       mistakes=[(3, 'Three columns, but you just showed that one of them is a combination of the others.')]),
   choice('Is [1, 1, 0] in the span of v1, v2, v3?', 'No', ['Yes'],
          ['Every vector in the span is a·v1 + b·v2 = [a, b, a + b]: its third entry equals the sum of the first two.'],
          'For [1, 1, 0] you would need 1 + 1 = 0. The span is the plane x3 = x1 + x2, and [1, 1, 0] is not on it.',
          {'Yes': 'Try to write it as [a, b, a + b]: the first two entries force a = b = 1, and then the third entry would have to be 2.'}),
  ],
  [step('a·v1 + b·v2 = [a, b, a + b]. Matching [1, 1, 2] gives a = b = 1, so v3 = v1 + v2.'),
   step('The rank is 2; the span is a plane (dimension 2) in R³.'),
   step('Vectors in the span satisfy x3 = x1 + x2; [1, 1, 0] does not, so it is not in the span.')],
  'A feature that is the sum of two other features adds no new direction: the design matrix loses rank and least squares can no longer pick unique weights.'),
 problem('coords', 'Coordinates in another basis', ['basis-coordinates'],
  'Coordinates of a vector x in a basis b1, b2 are the numbers c1, c2 with x = c1·b1 + c2·b2.',
  [
   vec('Use the basis b1 = [1, 1], b2 = [1, −1]. Find the coordinates of x = [5, 1].', [3, 2],
       ['Write the two equations for the two entries of c1·b1 + c2·b2 = x.', 'c1 + c2 = 5 and c1 − c2 = 1: add them to get c1.'],
       'c1 = 3 and c2 = 2: 3[1, 1] + 2[1, −1] = [5, 1].', tol=1e-6,
       mistakes=[([5, 1], 'Those are the coordinates in the standard basis. Find c1, c2 with c1·b1 + c2·b2 = x.'), ([2, 3], 'Check the order: c1 goes with b1 = [1, 1].')]),
   vec('Now use the basis b1 = [1, 0], b2 = [1, 1]. Find the coordinates of the same x = [5, 1].', [4, 1],
       ['Again write the two equations; this basis is not perpendicular, so solve the system.', 'The second entry gives c2 directly; then use the first entry.'],
       'c2 = 1 and c1 = 4: 4[1, 0] + 1[1, 1] = [5, 1].', tol=1e-6,
       mistakes=[([5, 3], 'The shortcut cᵢ = x·bᵢ/(bᵢ·bᵢ) only works for perpendicular bases; here b1·b2 = 1 ≠ 0. Solve the system.'), ([5, 1], 'Those are the standard coordinates.')]),
   choice('Why can [1, 1] and [2, 2] not be a basis of R²?', 'They are dependent, so together they only reach one line',
          ['They are not unit vectors', 'They are not perpendicular', 'A basis of R² needs three vectors'],
          ['A basis must span the space and be independent. Is [2, 2] a multiple of [1, 1]?'],
          'Unit length and perpendicularity are optional niceties; independence and spanning are what a basis needs.',
          {'They are not perpendicular': 'You just used the basis [1, 0], [1, 1], which is not perpendicular either. The problem is that [2, 2] = 2·[1, 1].', 'They are not unit vectors': 'Scaling a basis vector keeps it a basis. The problem is that [2, 2] = 2·[1, 1].', 'A basis of R² needs three vectors': 'R² has dimension 2: a basis has exactly two vectors.'}),
  ],
  [step('Basis [1, 1], [1, −1]: c1 + c2 = 5 and c1 − c2 = 1, so c = [3, 2]. Because b1 ⊥ b2, cᵢ = x·bᵢ/(bᵢ·bᵢ) also works.'),
   step('Basis [1, 0], [1, 1]: c2 = 1 from the second entry, c1 = 5 − 1 = 4. The dot-product shortcut fails here because the basis is not orthogonal.'),
   step('[2, 2] = 2·[1, 1]: the two vectors are dependent and only span a line.')],
  'Changing basis is how PCA works, and the easy dot-product formula for coordinates is one reason PCA uses an orthonormal basis.'),
 problem('subspace', 'Is it a subspace?', ['subspaces', 'dimension'],
  'Subsets of R³ and R⁴.',
  [
   choice('Which set is a subspace of R³?', 'All x with x1 + x2 + x3 = 0', ['All x with x1 + x2 + x3 = 1', 'All x with x1 ≥ 0', 'All x with x1·x2 = 0'],
          ['A subspace must contain 0 and be closed under adding vectors and scaling them. Test each set with the zero vector, with scaling by −1, and with adding two members.'],
          'x1 + x2 + x3 = 0 contains 0 and is closed under addition and scaling.',
          {'All x with x1 ≥ 0': 'Scale [1, 0, 0] by −1: you leave the set.', 'All x with x1·x2 = 0': '[1, 0, 0] and [0, 1, 0] are both in it, but their sum [1, 1, 0] is not.', 'All x with x1 + x2 + x3 = 1': 'Does it contain the zero vector?'}),
   num('What is the dimension of {x in R⁴ : x1 = 2x2 and x3 + x4 = 0}?', 2,
       ['Each independent linear equation removes one free choice.', 'Which coordinates can you choose freely, once the equations fix the others?'],
       'x2 and x4 are free; x1 = 2x2 and x3 = −x4 follow: dimension 4 − 2 = 2.', tol=0,
       mistakes=[(3, 'There are two independent equations, so two free choices are removed from the four.'), (1, 'Count the free choices: two coordinates can be chosen freely.')]),
  ],
  [step('Check 0, addition and scaling: only x1 + x2 + x3 = 0 passes all three.'),
   step('In R⁴, x2 and x4 are free, and x1, x3 are determined: basis [2, 1, 0, 0], [0, 0, −1, 1], dimension 2 (rank-nullity: 4 − 2).')],
  'Subspaces are the sets linear models live in: the column space of X holds every possible prediction vector.'),
 ])

# ---------------- Linear transformations ----------------
Rcw = np.array([[0,1],[-1,0]]); S = np.diag([2,1]); Ab = np.array([[3,1],[1,3]])
A5 = np.linalg.matrix_power(Ab,5)@[1,0]
homework('math/linear-transformations', 'math', 'Linear transformations',
 'Maps that respect addition and scaling, their matrices, composition, and change of basis.',
 [
 problem('rotate', 'Build the matrix of a map', ['transformation-matrix', 'composition-of-transformations'],
  'R rotates the plane 90° clockwise. S doubles the x-coordinate: S(x, y) = (2x, y).',
  [
   vec('Enter the matrix of R row by row (4 numbers).', Rcw.flatten(),
       ['The columns of the matrix are R(e1) and R(e2): where do [1, 0] and [0, 1] go?', 'Clockwise by 90°: [1, 0] goes to [0, −1] and [0, 1] goes to [1, 0]. Put these in as columns.'],
       'R = [[0, 1], [−1, 0]]: columns R(e1) = [0, −1] and R(e2) = [1, 0].', tol=0,
       mistakes=[([0, -1, 1, 0], 'That is the counterclockwise rotation, or you entered R(e1) and R(e2) as rows. R(e1) = [0, −1] is the first column.')]),
   vec('Compute R([3, 2]).', Rcw@[3,2], ['Multiply your matrix by the vector.', 'Row 1 of R dotted with [3, 2], then row 2.'], 'R[3, 2] = [2, −3]: perpendicular to [3, 2] and the same length.', tol=0,
       mistakes=[([-2, 3], 'That is the counterclockwise rotation. Check your R(e1).')]),
   vec('Compute (R ∘ S)([1, 1]).', Rcw@S@[1,1],
       ['In R ∘ S, which map acts first?', 'The right-hand map acts first: compute S[1, 1], then apply R.'],
       '(R ∘ S)[1, 1] = R[2, 1] = [1, −2].', tol=0,
       mistakes=[(S@Rcw@[1,1], 'That is (S ∘ R)[1, 1]: in R ∘ S the right-hand map S acts first.')]),
   choice('Do S and R commute (SR = RS)?', 'No', ['Yes', 'Only on the x-axis'],
          ['Compute (S ∘ R)[1, 1] and compare it with your previous answer.'],
          '(S ∘ R)[1, 1] = S[1, −1] = [2, −1], not [1, −2]. Matrix multiplication is not commutative.',
          {'Yes': 'Compute (S ∘ R)[1, 1] = S(R[1, 1]) and compare.', 'Only on the x-axis': 'SR = RS is a statement about matrices, true for every vector or for none; try [1, 0] too.'}),
  ],
  [step('Columns are the images of e1 and e2: R(e1) = [0, −1], R(e2) = [1, 0], so R = [[0, 1], [−1, 0]].'),
   step('R[3, 2] = [2, −3].'),
   step('(R ∘ S)[1, 1] = R[2, 1] = [1, −2], while (S ∘ R)[1, 1] = S[1, −1] = [2, −1]: RS ≠ SR.')],
  'A neural network layer is a linear map followed by a nonlinearity; stacking layers composes maps, and the order matters.'),
 problem('linear', 'Linear or affine?', ['linear-transformations', 'affine-maps'],
  'A map T is linear when T(a u + b v) = a T(u) + b T(v) for all vectors and numbers.',
  [
   choice('Which map from R² to R² is linear?', 'T(x, y) = (x + y, 2y)', ['T(x, y) = (x + 1, y)', 'T(x, y) = (xy, y)', 'T(x, y) = (|x|, y)'],
          ['A linear map sends 0 to 0 and satisfies T(−u) = −T(u). Test each option.'],
          'Only (x + y, 2y) is linear; its matrix is [[1, 1], [0, 2]].',
          {'T(x, y) = (x + 1, y)': 'T(0, 0) = (1, 0) ≠ 0. This is affine (linear plus a shift), not linear.', 'T(x, y) = (|x|, y)': 'T(−1, 0) = (1, 0), but −T(1, 0) = (−1, 0).', 'T(x, y) = (xy, y)': 'T(2·(1, 1)) = (4, 2), but 2·T(1, 1) = (2, 2).'}),
   vec('The affine map f(x) = A x + b has A = [[2, 0], [0, 3]] and b = [1, −1]. Compute f([1, 1]).', [3, 2],
       ['First multiply A by the vector.', 'A[1, 1] = [2, 3]; then add b.'], 'A[1, 1] = [2, 3]; adding b gives [3, 2].', tol=0,
       mistakes=[([2, 3], 'You forgot to add the shift b.')]),
   vec('Compute f([0, 0]).', [1, -1], ['A times the zero vector is zero.', 'What is left of A·0 + b?'], 'f(0) = b = [1, −1]. An affine map with b ≠ 0 does not fix the origin, so it is not linear. θ · x + θ₀ is affine for the same reason.', tol=0,
       mistakes=[([0, 0], 'Linear maps send 0 to 0, but f also adds b.')]),
  ],
  [step('Test T(0) = 0 and T(a u) = a T(u): only (x + y, 2y) passes.'),
   step('f([1, 1]) = [2, 3] + [1, −1] = [3, 2]; f(0) = [1, −1].')],
  'Models with an intercept, θ · x + θ₀, are affine. Adding a constant feature 1 turns them into linear maps on [1, x], which is why design matrices get a column of ones.'),
 problem('eigbasis', 'A power made easy by a change of basis', ['change-of-basis', 'eigenvalues-eigenvectors'],
  'A = [[3, 1], [1, 3]]. Use the basis b1 = [1, 1], b2 = [1, −1].',
  [
   vec('A b1 is a multiple c·b1 and A b2 is a multiple d·b2. Enter c, d.', [4, 2],
       ['Multiply A by [1, 1] and by [1, −1].', 'A[1, 1] = [4, 4]. Which multiple of [1, 1] is that?'],
       'A b1 = [4, 4] = 4 b1 and A b2 = [2, −2] = 2 b2. In the basis b1, b2 the matrix of A is diag(4, 2).', tol=0),
   vec('Write [1, 0] in this basis. Enter its coordinates.', [0.5, 0.5],
       ['Solve c1[1, 1] + c2[1, −1] = [1, 0].', 'c1 + c2 = 1 and c1 − c2 = 0.'], '[1, 0] = ½ b1 + ½ b2.', tol=1e-6),
   vec('Use the two answers to compute A⁵ [1, 0] without multiplying matrices five times.', A5,
       ['In the new basis, A multiplies the b1-coordinate by 4 and the b2-coordinate by 2.', 'After five steps the coordinates are ½·4⁵ and ½·2⁵; convert back with c1·b1 + c2·b2.'],
       f'A⁵[1, 0] = 512[1, 1] + 16[1, −1] = [{int(A5[0])}, {int(A5[1])}].', tol=0,
       mistakes=[([512, 16], 'Those are the coordinates in the basis b1, b2. Convert back: 512·[1, 1] + 16·[1, −1].'), ([1024, 32], 'Keep the factor ½ from the coordinates of [1, 0].')]),
   choice('As k grows, which direction does Aᵏ[1, 0] approach?', '[1, 1]', ['[1, −1]', '[1, 0]', 'It keeps changing direction'],
          ['Compare how fast the two coordinates grow: 4ᵏ against 2ᵏ.'],
          'The b1-coordinate grows like 4ᵏ, the b2-coordinate only like 2ᵏ: the direction tends to b1. This is power iteration, how PageRank finds its eigenvector.',
          {'[1, 0]': f'Already A⁵[1, 0] = [{int(A5[0])}, {int(A5[1])}] points almost along [1, 1].', '[1, −1]': 'That direction is multiplied by only 2 per step, the other by 4.'}),
  ],
  [step('A b1 = 4 b1 and A b2 = 2 b2, so in this basis A is diag(4, 2).'),
   step('[1, 0] = ½ b1 + ½ b2.'),
   step(f'A⁵ scales the coordinates to ½·1024 = 512 and ½·32 = 16, so A⁵[1, 0] = 512[1, 1] + 16[1, −1] = [{int(A5[0])}, {int(A5[1])}].', r'A^5\begin{bmatrix}1\\0\end{bmatrix}=\tfrac{4^5}{2}\begin{bmatrix}1\\1\end{bmatrix}+\tfrac{2^5}{2}\begin{bmatrix}1\\-1\end{bmatrix}'),
   step('The larger eigenvalue wins: Aᵏ[1, 0] turns towards b1 = [1, 1].')],
  'Choosing the eigenvector basis makes a matrix diagonal. The same trick explains how gradient descent, PageRank and PCA behave.'),
 ])

# ---------------- Rank, determinants and inverses ----------------
M = np.array([[2,1,0],[1,3,1],[0,1,2]])
homework('math/rank-determinants-and-inverses', 'math', 'Rank, determinants and inverses',
 'Rank and nullity, determinants as volume, and when a matrix can be inverted.',
 [
 problem('ranknull', 'Rank and nullity', ['rank-nullity'],
  'A = [[1, 2, 3], [2, 4, 6], [1, 0, 1]].',
  [
   num('What is the rank of A?', 2,
       ['Look for a row that is a multiple of another.', 'Row 2 = 2·row 1. Is row 3 a multiple of row 1?'],
       'Row 2 duplicates row 1; rows 1 and 3 are independent. Rank 2.', tol=0,
       mistakes=[(3, 'Row 2 = 2·row 1, so only two rows are independent.')]),
   num('What is the nullity (dimension of the null space)?', 1,
       ['Rank-nullity links the rank, the nullity and the number of columns.', 'Rank + nullity = number of columns.'], '3 − 2 = 1.', tol=0),
   choice('Which vector spans the null space?', '[−1, −1, 1]', ['[1, 2, 3]', '[1, 1, 1]', '[1, 0, −1]'],
          ['Solve A x = 0: rows 1 and 3 give x1 + 2x2 + 3x3 = 0 and x1 + x3 = 0. Set x3 = 1.'],
          'A[−1, −1, 1] = [−1 − 2 + 3, −2 − 2 + 6, −1 + 1] = [0, 0, 0].',
          {'[1, 0, −1]': 'Row 1 gives 1 + 0 − 3 = −2 ≠ 0.', '[1, 1, 1]': 'Row 1 gives 6 ≠ 0.', '[1, 2, 3]': 'That is row 1 itself; the null space is perpendicular to the rows.'}),
  ],
  [step('Row 2 = 2·row 1 and row 3 is not a multiple of row 1: rank 2.'),
   step('Nullity = 3 − 2 = 1.'),
   step('x1 + x3 = 0 and x1 + 2x2 + 3x3 = 0 with x3 = 1 give x1 = −1, x2 = −1.')],
  'A nonzero null space means different inputs give the same output. For a design matrix, it means different weight vectors make identical predictions.'),
 problem('det', 'The determinant as an area', ['determinant-geometry', 'invertible-transformations'],
  'A = [[3, 1], [1, 2]].',
  [
   num('Compute det A.', 5, ['For a 2 by 2 matrix [[a, b], [c, d]] the determinant combines the diagonal products.', 'det = ad − bc.'], 'det A = 3·2 − 1·1 = 5.', tol=0,
       mistakes=[(7, 'That is ad + bc. The determinant subtracts: ad − bc.')]),
   num('A triangle of area 2 is mapped by A. What is the area of its image?', 10,
       ['What does |det A| tell you about areas?', '|det A| is the factor by which A scales every area.'], 'Areas scale by |det A| = 5, so 2 becomes 10.', tol=0,
       mistakes=[(5, 'That is the scaling factor; the triangle started with area 2.')]),
   num('Compute det(2A).', 20,
       ['Doubling the matrix doubles each of its two rows.', 'Each doubled row doubles the determinant.'],
       'det(2A) = 2²·det A = 20 for a 2 by 2 matrix (in n dimensions, 2ⁿ).', tol=0,
       mistakes=[(10, 'Both rows are doubled, so the determinant is multiplied by 2 twice.')]),
   num('Compute det(A⁻¹).', 0.2, ['The inverse undoes the area scaling of A.', 'det(A⁻¹) = 1/det A.'], 'The inverse undoes the area scaling: 1/5 = 0.2.',
       mistakes=[(-5, 'The inverse does not flip the sign; it undoes the scaling.')]),
  ],
  [step('det A = 6 − 1 = 5, so areas are multiplied by 5: 2 becomes 10.'),
   step('det(2A) = 4·5 = 20 because each of the two rows is doubled.'),
   step('det(A⁻¹) = 1/5. If det A were 0, A would flatten the plane onto a line and could not be undone.')],
  'det A = 0 means some direction is squashed to nothing, the same as a nonzero null space and the same as no inverse.'),
 problem('cofactor', 'Cofactors, row operations and the inverse', ['determinants-cofactor-row-ops', 'invertible-transformations'],
  'A = [[2, 1, 0], [1, 3, 1], [0, 1, 2]].',
  [
   num('Compute det A by cofactor expansion along the first row.', round(np.linalg.det(M)),
       ['Each entry of row 1 times its 2 by 2 minor, with signs +, −, +.', 'det A = 2·det[[3, 1], [1, 2]] − 1·det[[1, 1], [0, 2]] + 0.'],
       'det A = 2·5 − 1·2 + 0 = 8.', tol=0,
       mistakes=[(12, 'Remember the alternating signs: +, −, + along the first row.')]),
   num('What is the determinant after swapping rows 1 and 2?', -8, ['What does a row swap do to the determinant?', 'A row swap flips the sign.'], 'Swapping two rows multiplies the determinant by −1: −8.', tol=0,
       mistakes=[(8, 'A row swap changes the sign of the determinant.')]),
   num('Compute det(−A).', -8, ['−A multiplies each row of A by −1. How many rows are there?', 'Each of the 3 rows contributes a factor −1.'], '(−1)³·8 = −8. For an n by n matrix, det(cA) = cⁿ det A.', tol=0,
       mistakes=[(8, 'Three rows each flip sign: (−1)³ = −1.')]),
   num('Compute the (1, 1) entry of A⁻¹ (3 decimals).', np.linalg.inv(M)[0,0],
       ['Gauss-Jordan on [A | I] works, but there is a shortcut: A⁻¹ = adj(A)/det A, where adj(A) is the transposed matrix of cofactors. For the (1, 1) entry this is C₁₁/det A.', 'C₁₁ = +det[[3, 1], [1, 2]] (sign + at position (1, 1)).'],
       '(A⁻¹)₁₁ = 5/8 = 0.625.',
       mistakes=[(5, 'That is the cofactor C₁₁ itself. Divide by det A.'), (1.6, 'Upside down: the entry is C₁₁/det A, not det A/C₁₁.'), (0.5, 'The inverse is not taken entry by entry: (A⁻¹)₁₁ ≠ 1/a₁₁.')]),
  ],
  [step('Expansion along row 1: 2(3·2 − 1·1) − 1(1·2 − 1·0) + 0 = 10 − 2 = 8.'),
   step('A row swap gives −8; det(−A) = (−1)³·8 = −8.'),
   step('A · adj(A) = det(A) · I, so A⁻¹ = adj(A)/det A with (A⁻¹)ᵢⱼ = Cⱼᵢ/det A (note the transpose). For (1, 1): 5/8 = 0.625.', r'A^{-1}=\frac{1}{\det A}\operatorname{adj}(A),\qquad (A^{-1})_{11}=\frac{C_{11}}{\det A}=\frac58')],
  'In practice determinants are computed by elimination, tracking row swaps; the cofactor formula explains why A⁻¹ exists exactly when det A ≠ 0.'),
 ])

# ---------------- Analytic geometry ----------------
X = np.array([[1,0],[1,1],[1,2]], float); y = np.array([1,2,4], float)
th = np.linalg.solve(X.T@X, X.T@y); res = y - X@th
a_ = np.array([1,2,2.]); b_ = np.array([3,0,6.]); p_ = (a_@b_)/(a_@a_)*a_; rr = b_-p_
homework('math/analytic-geometry-angles-and-projections', 'math', 'Analytic geometry: angles and projections',
 'Inner products, orthogonality, projections, and least squares as a projection.',
 [
 problem('project', 'Project onto a line', ['orthogonal-projections', 'orthogonality'],
  'Project b = [3, 0, 6] onto the line through a = [1, 2, 2].',
  [
   num('Compute a · b.', 15, ['Multiply matching entries.', 'Add 1·3, 2·0 and 2·6.'], '3 + 0 + 12 = 15.', tol=0),
   vec('Compute the projection p of b onto the line through a (3 decimals).', p_,
       ['p is a multiple t·a, chosen so that the leftover b − t·a is perpendicular to a.', '(b − t·a)·a = 0 gives t = (a·b)/(a·a); here a·a = 9.'],
       'p = (15/9) a = [5/3, 10/3, 10/3].', tol=0.002,
       mistakes=[([15, 30, 30], 'You forgot to divide by a · a = 9.'), ([5, 10, 10], 'You divided by ||a|| = 3. The formula divides by a · a = ||a||².')]),
   num('Compute the length of the residual b − p (3 decimals).', np.linalg.norm(rr),
       ['Subtract p from b entry by entry.', 'b − p = [4/3, −10/3, 8/3]; take its length.'], f'||b − p|| = sqrt 20 ≈ {r(np.linalg.norm(rr),3)}.',
       mistakes=[(20, 'That is the squared length. Take the square root.')]),
   choice('Why is b − p perpendicular to a?', 'p is the closest point to b on the line, and the shortest path to a line meets it at a right angle',
          ['Because a has length 3', 'Because b has a zero entry', 'It is a coincidence of these numbers'],
          ['Compute (b − p) · a, then ask whether that could fail for other a and b.'], '(b − p) · a = 4/3 − 20/3 + 16/3 = 0. The perpendicular leftover is exactly what makes p the closest point, for any a and b.',
          {'It is a coincidence of these numbers': 'Try other vectors: the construction t = (a·b)/(a·a) always makes (b − t a)·a = 0.'}),
  ],
  [step('a · b = 15 and a · a = 9, so p = (15/9)·a = [5/3, 10/3, 10/3].', r'p=\frac{a\cdot b}{a\cdot a}\,a'),
   step(f'b − p = [4/3, −10/3, 8/3], of length sqrt 20 ≈ {r(np.linalg.norm(rr),3)}, and (b − p) · a = 0.')],
  'Least squares is this projection with the line replaced by the column space of X: the prediction vector is the closest point to y that the model can produce.'),
 problem('lsq', 'Least squares as a projection', ['orthogonal-projections', 'least-squares-normal-equation'],
  'Fit y = θ₀ + θ₁x by least squares to the points (0, 1), (1, 2), (2, 4). The design matrix has columns [1, 1, 1] and [0, 1, 2].',
  [
   vec('Compute XᵀX (4 numbers, row by row).', (X.T@X).flatten(),
       ['Entry (i, j) is column i of X dotted with column j.', 'The top-left entry is [1,1,1]·[1,1,1] = 3.'], 'XᵀX = [[3, 3], [3, 5]].', tol=0),
   vec('Solve the normal equation for θ. Enter θ₀, θ₁ (3 decimals).', th,
       ['The normal equation is XᵀX θ = Xᵀy. Compute Xᵀy first.', 'Xᵀy = [7, 10]: solve 3θ₀ + 3θ₁ = 7 and 3θ₀ + 5θ₁ = 10 (subtract to get θ₁).'],
       f'θ₁ = 3/2 = 1.5 and θ₀ = 5/6 ≈ {r(th[0],3)}.', tol=0.002,
       mistakes=[([1.5, 5/6], 'Order: θ₀ (intercept) first, then θ₁ (slope).')]),
   vec('Compute the residual vector y − Xθ (3 decimals).', res,
       ['The predictions are θ₀, θ₀ + θ₁ and θ₀ + 2θ₁.', 'Subtract each prediction from 1, 2 and 4.'], f'Residuals [{r(res[0],3)}, {r(res[1],3)}, {r(res[2],3)}].', tol=0.002,
       mistakes=[(-res, 'Sign: the residual is y minus the prediction.')]),
   choice('The residuals add up to 0. Why?', 'The residual is perpendicular to the column of ones', ['The data are on a straight line', 'Least squares always gives zero total error', 'There are three points'],
          ['The normal equation says Xᵀ(y − Xθ) = 0. What does its first row say?'],
          'The first row of Xᵀ is [1, 1, 1], so Xᵀ(y − Xθ) = 0 contains "sum of residuals = 0". Any model with an intercept has this property.',
          {'Least squares always gives zero total error': 'The squared error here is not 0; only the plain sum of residuals is, and only when there is an intercept.', 'The data are on a straight line': 'They are not: the residuals are nonzero.'}),
  ],
  [step('XᵀX = [[3, 3], [3, 5]] and Xᵀy = [7, 10].'),
   step(f'Solve: 2θ₁ = 3, θ₁ = 1.5, θ₀ = (7 − 4.5)/3 = 5/6 ≈ {r(th[0],4)}.', r'\begin{bmatrix}3&3\\3&5\end{bmatrix}\theta=\begin{bmatrix}7\\10\end{bmatrix}'),
   step(f'Residuals {r(res[0],3)}, {r(res[1],3)}, {r(res[2],3)}; their sum is 0 and their dot product with [0, 1, 2] is 0.')],
  'The zero-sum residual is a quick sanity check for any regression with an intercept, and the perpendicular residual is the whole content of the normal equation.'),
 problem('gs', 'Gram-Schmidt and the orthogonal complement', ['gram-schmidt', 'orthogonal-complement'],
  'Orthogonalize b1 = [1, 1, 0] and b2 = [1, 0, 1].',
  [
   num('Keep u1 = b1. What multiple of u1 do you subtract from b2?', 0.5,
       ['You remove the part of b2 that lies along u1: its projection.', 'The multiple is (b2 · u1)/(u1 · u1).'], '(b2 · u1)/(u1 · u1) = 1/2.',
       mistakes=[(1, 'That is b2 · u1 alone; divide by u1 · u1 = 2.')]),
   vec('Compute u2 = b2 − (your coefficient from (a))·u1.', [0.5, -0.5, 1], ['Subtract the multiple of [1, 1, 0] from [1, 0, 1].', 'Check your answer: u1 · u2 should be 0.'], 'u2 = [0.5, −0.5, 1], and u1 · u2 = 0.', tol=1e-6,
       mistakes=[([0, -1, 1], 'You subtracted the whole of u1. Use the coefficient from (a).')]),
   num('Compute ||u2|| (3 decimals).', np.sqrt(1.5), ['Square the entries and add them.', '0.25 + 0.25 + 1, then the square root.'], f'sqrt(1.5) ≈ {r(np.sqrt(1.5),3)}. Divide by it to get a unit vector.',
       mistakes=[(1.5, 'That is ||u2||². Take the square root.')]),
   choice('Which vector spans the orthogonal complement of span{b1, b2} in R³?', '[1, −1, −1]', ['[1, 1, 1]', '[0.5, −0.5, 1]', '[1, −1, 0]'],
          ['You need a vector perpendicular to both b1 and b2: test each option with two dot products.'],
          '[1, −1, −1]·[1, 1, 0] = 0 and [1, −1, −1]·[1, 0, 1] = 0. The complement of a plane in R³ is a line.',
          {'[0.5, −0.5, 1]': 'That is u2, which lies inside the plane, not perpendicular to it.', '[1, −1, 0]': 'It is perpendicular to b1 but not to b2.', '[1, 1, 1]': 'Its dot product with b1 is 2, not 0.'}),
  ],
  [step('u1 = [1, 1, 0]. Coefficient = (b2·u1)/(u1·u1) = 1/2.'),
   step('u2 = [1, 0, 1] − ½[1, 1, 0] = [0.5, −0.5, 1], with ||u2|| = sqrt(1.5) ≈ 1.225.'),
   step('A vector perpendicular to both is [1, −1, −1] (both dot products are 0).')],
  'Gram-Schmidt is the QR decomposition, a numerically stable way to solve least squares.'),
 ])

# ---------------- Eigenvalues ----------------
Af = np.array([[5,2],[1,4]]); A3 = np.linalg.matrix_power(Af,3)@[2,1]
homework('math/eigenvalues-and-eigenvectors', 'math', 'Eigenvalues and eigenvectors',
 'Eigenvalues and eigenvectors, trace and determinant, diagonalization, Markov chains, and symmetric matrices.',
 [
 problem('find', 'Find the eigenvalues', ['eigenvalues-eigenvectors', 'trace'],
  'A = [[5, 2], [1, 4]].',
  [
   vec('Enter trace A and det A.', [9, 18], ['The trace is the sum of the diagonal.', 'det = ad − bc.'], 'trace 9 and det 20 − 2 = 18.', tol=0),
   vec('Find both eigenvalues (any order).', [6, 3],
       ['For a 2 by 2 matrix they solve λ² − (trace)λ + det = 0.', 'λ² − 9λ + 18 = 0; find two numbers with sum 9 and product 18.'],
       'λ = 6 and λ = 3. Check: 6 + 3 = 9 = trace and 6·3 = 18 = det.', tol=1e-6, unordered=True),
   choice('Which is an eigenvector for λ = 6?', '[2, 1]', ['[1, −1]', '[1, 2]', '[1, 1]'],
          ['Solve (A − 6I)v = 0 with A − 6I = [[−1, 2], [1, −2]], or test each option: is A v a multiple of v?'],
          'A[2, 1] = [12, 6] = 6[2, 1].',
          {'[1, −1]': 'A[1, −1] = [3, −3] = 3[1, −1]: that one belongs to λ = 3.', '[1, 2]': 'A[1, 2] = [9, 9], which is not a multiple of [1, 2].', '[1, 1]': 'A[1, 1] = [7, 5], which is not a multiple of [1, 1].'}),
   vec('Compute A³ [2, 1] without multiplying matrices.', A3, ['What does A do to an eigenvector?', 'Each multiplication by A scales [2, 1] by its eigenvalue.'], f'A³[2, 1] = 6³[2, 1] = [{int(A3[0])}, {int(A3[1])}].', tol=0,
       mistakes=[([72, 36], 'That is A²: three multiplications give 6³.')]),
  ],
  [step('trace 9, det 18, so λ² − 9λ + 18 = 0 and λ = 6, 3.'),
   step('A − 6I = [[−1, 2], [1, −2]] gives v = [2, 1]; A − 3I = [[2, 2], [1, 1]] gives v = [1, −1].'),
   step('A³[2, 1] = 216[2, 1] = [432, 216].')],
  'Along an eigenvector, repeated multiplication is just repeated scaling. That is the key to Markov chains, gradient descent on quadratics and PCA.'),
 problem('markov', 'A two-state Markov chain', ['diagonalization', 'pagerank'],
  'Each day 90% of customers of shop A stay and 10% switch to B; 80% of B\'s customers stay and 20% switch to A. The matrix P = [[0.9, 0.2], [0.1, 0.8]] maps today\'s shares [a, b] to tomorrow\'s.',
  [
   vec('Find the eigenvalues of P (any order).', [1, 0.7],
       ['Each column sums to 1. What does that make Pᵀ[1, 1]?', 'So 1 is an eigenvalue; the trace gives the other.'],
       'Eigenvalues 1 and 0.7 (trace 1.7, det 0.72 − 0.02 = 0.7).', unordered=True, tol=1e-6),
   vec('Find the long-run shares: the eigenvector for eigenvalue 1, scaled to sum to 1 (3 decimals).', [2/3, 1/3],
       ['Solve (P − I)v = 0.', 'The first row gives −0.1 v1 + 0.2 v2 = 0; then scale so that v1 + v2 = 1.'],
       'v = [2/3, 1/3]: in the long run A has two thirds of the customers.', tol=0.002,
       mistakes=[([0.5, 0.5], 'You solved vᵀP = vᵀ, treating rows as "from". Here column j holds where shop j\'s customers go, so solve P v = v.'), ([1/3, 2/3], 'Order: the first entry is shop A, which keeps 90% and gains 20% of B, so it ends up larger.')]),
   num('Which eigenvalue of P controls how fast the shares approach the long-run shares?', 0.7,
       ['Write the starting shares as (long-run shares) + (a multiple of the second eigenvector).', 'Each day, what happens to each of those two parts?'],
       'The eigenvalue-1 part is the limit and never changes; the other part is multiplied by 0.7 each day.', tol=1e-6,
       mistakes=[(1, 'The eigenvalue-1 part is the limit itself. What shrinks is the other part.')]),
   num('Starting from [1, 0], after how many whole days is the gap to the long-run shares below 1% of its starting size?', 13,
       ['The gap is multiplied by the same factor every day.', 'Find the smallest k with 0.7ᵏ < 0.01, using logarithms.'],
       '0.7¹² ≈ 0.0138 and 0.7¹³ ≈ 0.0097: 13 days. The closer the second eigenvalue is to 1, the slower the chain settles.', tol=0,
       mistakes=[(12, 'Check 0.7¹²: it is still above 0.01. Round up.'), (10, 'Check 0.7¹⁰: it is still above 1%.')]),
  ],
  [step('Columns sum to 1, so λ = 1; the trace 1.7 gives the other eigenvalue 0.7.'),
   step('(P − I)v = 0 gives v1 = 2v2, so the long-run shares are [2/3, 1/3].'),
   step('Write [1, 0] = [2/3, 1/3] + [1/3, −1/3]; the second part is an eigenvector for 0.7 and shrinks by 0.7 per day.'),
   step('0.7ᵏ < 0.01 needs k > ln 0.01/ln 0.7 ≈ 12.9, so 13 days.')],
  'PageRank is the same computation with millions of pages: the eigenvector for eigenvalue 1, and the second eigenvalue sets how fast the iteration converges.'),
 problem('symmetric', 'Symmetric matrices', ['spectral-theorem', 'taylor-hessian'],
  'S = [[5, 2], [2, 2]].',
  [
   vec('Find the eigenvalues of S (any order).', [6, 1], ['Use the trace and the determinant.', 'trace 7 and det 6: two numbers with that sum and product.'], 'λ = 6 (eigenvector [2, 1]) and λ = 1 (eigenvector [1, −2]).', tol=1e-6, unordered=True),
   choice('Take the eigenvectors [2, 1] (for 6) and [1, −2] (for 1). How are they related?', 'They are perpendicular', ['They are parallel', 'They have the same length and nothing more', 'They are unrelated'],
          ['Compute their dot product.'], '2·1 + 1·(−2) = 0. The spectral theorem guarantees this for every symmetric matrix: S = QΛQᵀ with an orthonormal Q.',
          {'They have the same length and nothing more': 'They do both have length sqrt 5, but compute their dot product.', 'They are unrelated': 'Compute their dot product.'}),
   num('Compute xᵀ S x for x = [1, −2].', 5, ['First compute S x.', 'x is an eigenvector: S x = 1·x, so xᵀSx = xᵀx.'], 'S x = [1, −2], so xᵀSx = 1 + 4 = 5 = λ·||x||² with λ = 1.', tol=0,
       mistakes=[(1, 'That is the eigenvalue; multiply by ||x||² = 5.')]),
   choice('Is S positive definite (xᵀSx > 0 for every x ≠ 0)?', 'Yes', ['No', 'It depends on x'],
          ['Write x = c1·[2, 1] + c2·[1, −2]. Because the eigenvectors are perpendicular, the cross terms vanish.', 'xᵀSx = 6·5c1² + 1·5c2², a sum of positive multiples of squares.'],
          'Positive eigenvalues make xᵀSx a positive sum of squares unless x = 0: S is positive definite, a bowl with a unique minimum.',
          {'No': 'An off-diagonal entry does not stop positive definiteness. Only the signs of the eigenvalues matter.', 'It depends on x': 'Definiteness is about every x ≠ 0 at once; write xᵀSx in the eigenbasis.'}),
  ],
  [step('trace 7, det 6: eigenvalues 6 and 1, eigenvectors [2, 1] and [1, −2], which are perpendicular.'),
   step('xᵀSx for x = [1, −2]: S x = x, so the value is ||x||² = 5.'),
   step('In the eigenbasis xᵀSx = 30c1² + 5c2² > 0 unless x = 0: positive definite.')],
  'Covariance matrices and Hessians are symmetric; their eigenvalues are the variances along principal directions and the curvatures of a loss, and positive definite means a bowl with one minimum.'),
 ])

# ---------------- Matrix decompositions ----------------
Asvd = np.array([[4,0],[3,5]], float); sv = np.linalg.svd(Asvd, compute_uv=False)
homework('math/matrix-decompositions', 'math', 'Matrix decompositions',
 'LU, Cholesky and the singular value decomposition.',
 [
 problem('lu', 'Solve with LU', ['lu-decomposition'],
  'A = [[3, 1], [6, 4]] and b = [5, 14].',
  [
   num('Eliminate below the first pivot. What multiplier l₂₁ do you use?', 2, ['The multiplier is (entry to eliminate)/(pivot).', 'l₂₁ = 6/3.'], 'l₂₁ = 2, so L = [[1, 0], [2, 1]].', tol=0,
       mistakes=[(0.5, 'Upside down: divide the entry to eliminate by the pivot.')]),
   num('What is U₂₂, the second pivot?', 2, ['Subtract l₂₁ times row 1 from row 2.', 'Row 2 − 2·row 1 = [6 − 6, 4 − 2].'], 'U = [[3, 1], [0, 2]], so U₂₂ = 2.', tol=0),
   vec('Solve L y = b, then U x = y. Enter x.', [1, 2],
       ['Forward substitution with L gives y; back substitution with U gives x.', 'y = [5, 14 − 2·5] = [5, 4]. Then 2x2 = 4 and 3x1 + x2 = 5.'], 'x2 = 2 and x1 = 1. Check: A[1, 2] = [5, 14].', tol=1e-6,
       mistakes=[([2, 1], 'Order: x1 first, then x2.')]),
  ],
  [step('l₂₁ = 6/3 = 2; U = [[3, 1], [0, 2]], L = [[1, 0], [2, 1]].'),
   step('L y = b: y = [5, 14 − 10] = [5, 4].'),
   step('U x = y: x2 = 4/2 = 2, x1 = (5 − 2)/3 = 1.')],
  'Factor once, then solve cheaply for many right-hand sides: that is why libraries compute LU instead of an inverse.'),
 problem('chol', 'Cholesky, and when it fails', ['cholesky-decomposition'],
  'Cholesky writes a symmetric positive definite S as L Lᵀ with L lower triangular.',
  [
   vec('Find L for S = [[9, 6], [6, 5]]. Enter L₁₁, L₂₁, L₂₂.', [3, 2, 1],
       ['Match the entries of L Lᵀ with S, starting at the top left: L₁₁² = S₁₁.', 'Then L₂₁ L₁₁ = S₂₁, and L₂₁² + L₂₂² = S₂₂.'],
       'L = [[3, 0], [2, 1]]; check L Lᵀ = [[9, 6], [6, 5]].', tol=1e-6),
   num('Use L to compute det S.', 9, ['det(L Lᵀ) = det(L)², and a triangular determinant is the product of its diagonal.', 'det L = 3·1.'], 'det S = (3·1)² = 9 = 45 − 36.', tol=0,
       mistakes=[(3, 'That is det L. det S = det(L)·det(Lᵀ).')]),
   choice('Try Cholesky on [[1, 2], [2, 1]]. What happens?', 'The square root for L₂₂ is of a negative number: the matrix is not positive definite', ['It works with L₂₂ = sqrt 3', 'It works because the matrix is symmetric', 'L₁₁ is zero'],
          ['L₁₁ = 1 and L₂₁ = 2; what is S₂₂ − L₂₁²?'],
          'L₂₂ = sqrt(1 − 4) is not real. Cholesky doubles as a test for positive definiteness; this matrix has eigenvalues 3 and −1.',
          {'It works because the matrix is symmetric': 'Symmetric is not enough; it must also be positive definite.', 'It works with L₂₂ = sqrt 3': 'Recompute: S₂₂ − L₂₁² = 1 − 4.'}),
  ],
  [step('L₁₁ = 3, L₂₁ = 6/3 = 2, L₂₂ = sqrt(5 − 4) = 1.'),
   step('det S = (L₁₁L₂₂)² = 9.'),
   step('For [[1, 2], [2, 1]]: L₂₂² = 1 − 4 < 0, so no real Cholesky factor exists.')],
  'Multiplying standard normal samples by L gives samples with covariance S; a failed Cholesky is the quickest sign that a "covariance" matrix is not valid.'),
 problem('svd', 'SVD and compression', ['svd'],
  'A = [[4, 0], [3, 5]].',
  [
   vec('Find the singular values, largest first (3 decimals).', sv,
       ['They are the square roots of the eigenvalues of AᵀA.', 'AᵀA = [[25, 15], [15, 25]]: use its trace and determinant.'], f'σ₁ = sqrt 40 ≈ {r(sv[0],3)} and σ₂ = sqrt 10 ≈ {r(sv[1],3)}.', tol=0.002,
       mistakes=[([40, 10], 'Those are the eigenvalues of AᵀA. The singular values are their square roots.')]),
   num('Compute ||A||²_F, the sum of the squared entries, and compare it with σ₁² + σ₂².', 50, ['Square each entry and add.', '16 + 0 + 9 + 25.'], '50 = σ₁² + σ₂² = 40 + 10.', tol=0),
   num('The best rank-1 approximation keeps only σ₁. What is its error ||A − A₁||_F (3 decimals)?', sv[1],
       ['The error is made of the dropped singular values.', '||A − A₁||²_F is the sum of the dropped σᵢ².'], f'The error is σ₂ = sqrt 10 ≈ {r(sv[1],3)}.',
       mistakes=[(10, 'That is ||A − A₁||²_F = σ₂². Take the square root.'), (sv[0], 'That is the singular value you keep, not the one you drop.')]),
   num('What fraction of ||A||²_F does the rank-1 approximation keep?', 0.8, ['Compare the kept σ₁² with the total.', 'σ₁²/(σ₁² + σ₂²).'], '40/50 = 0.8.',
       mistakes=[(sv[0]/(sv[0]+sv[1]), 'Use the squared singular values: the Frobenius norm adds squares.')]),
  ],
  [step('AᵀA has eigenvalues 40 and 10, so σ₁ = sqrt 40 ≈ 6.325 and σ₂ = sqrt 10 ≈ 3.162.'),
   step('||A||²_F = 16 + 9 + 25 = 50 = 40 + 10.'),
   step('Dropping σ₂ leaves error sqrt 10 and keeps 40/50 = 80% of the squared size.')],
  'Image compression and PCA both keep the largest singular values; the dropped ones measure exactly what is lost.'),
 ])

# ---------------- Vector calculus ----------------
homework('math/vector-calculus', 'math', 'Vector calculus',
 'Gradients, the chain rule, backpropagation, and second-order Taylor approximations.',
 [
 problem('grad', 'Gradients and directions', ['partial-derivatives-gradient'],
  'f(x, y) = x²y + 3y.',
  [
   vec('Compute the gradient ∇f at (2, 1).', [4, 7],
       ['Take each partial derivative, treating the other variable as a constant.', '∂f/∂x = 2xy and ∂f/∂y = x² + 3; plug in (2, 1).'], '∇f = [2xy, x² + 3] = [4, 7] at (2, 1).', tol=0,
       mistakes=[([7, 4], 'Order: ∂f/∂x first, then ∂f/∂y.')]),
   num('Compute the rate of change of f at (2, 1) in the direction of [3, 4].', 8,
       ['The directional derivative is ∇f · u for a unit vector u.', 'Divide [3, 4] by its length 5 first.'], '[4, 7]·[0.6, 0.8] = 2.4 + 5.6 = 8.', tol=1e-6,
       mistakes=[(40, 'Divide [3, 4] by its length 5 first: the direction must be a unit vector.')]),
   num('What is the largest possible rate of change at (2, 1), over all unit directions (3 decimals)?', np.sqrt(65),
       ['In which direction does f increase fastest?', 'Along the gradient itself; the rate is then ||∇f||.'], f'||[4, 7]|| = sqrt 65 ≈ {r(np.sqrt(65),3)}, more than the 8 you found along [3, 4].',
       mistakes=[(65, 'That is ||∇f||². Take the square root.')]),
  ],
  [step('∇f = [2xy, x² + 3] = [4, 7] at (2, 1).'),
   step('Directional derivative along [0.6, 0.8]: 2.4 + 5.6 = 8.'),
   step('Steepest ascent is along ∇f with rate ||∇f|| = sqrt 65 ≈ 8.062; gradient descent steps the opposite way.')],
  'Gradient descent uses exactly this fact: −∇f is the direction in which the loss falls fastest.'),
 problem('chain', 'Backpropagation through one neuron', ['derivatives', 'jacobian-chain-rule', 'backpropagation', 'loss-gradients'],
  'z = w x + b, a = σ(z), L = (a − y)². Take x = 2, w = 0.5, b = −1, y = 1.',
  [
   num('Forward pass: compute L.', 0.25, ['Compute z, then a = σ(z), then L.', 'z = 0.5·2 − 1 = 0, and σ(0) = 0.5.'], 'z = 0, a = 0.5, L = (0.5 − 1)² = 0.25.'),
   num('Compute ∂L/∂w.', -0.5,
       ['Chain rule: ∂L/∂w = ∂L/∂a · ∂a/∂z · ∂z/∂w. The Derivatives page gives σ\'(z) = σ(z)(1 − σ(z)).', '∂L/∂a = 2(a − y) = −1, ∂a/∂z = σ(0)(1 − σ(0)) = 0.25, ∂z/∂w = x. Multiply.'],
       '−1 · 0.25 · 2 = −0.5.',
       mistakes=[(-0.25, 'That is ∂L/∂b (∂z/∂b = 1). For w, multiply by ∂z/∂w = x.'), (-2, 'Include ∂a/∂z = σ(0)(1 − σ(0)).'), (-1, 'Include ∂a/∂z and ∂z/∂w, not only ∂L/∂a.')]),
   num('Compute ∂L/∂b.', -0.25, ['Same chain as for w, except for the last factor.', '∂z/∂b = 1.'], '−1 · 0.25 · 1 = −0.25.',
       mistakes=[(-0.5, 'That is ∂L/∂w. For b the last factor is ∂z/∂b = 1.')]),
   num('Take one gradient step with learning rate 0.4. What is the new w?', 0.7, ['Gradient descent moves against the gradient.', 'w ← w − 0.4·∂L/∂w.'], '0.5 − 0.4·(−0.5) = 0.7: w grows, pushing a toward y = 1.',
       mistakes=[(0.3, 'Gradient descent subtracts the gradient: w − 0.4·(−0.5).')]),
  ],
  [step('Forward: z = 0, a = σ(0) = 0.5, L = 0.25.'),
   step('Backward: ∂L/∂a = 2(a − y) = −1 and ∂a/∂z = σ(0)(1 − σ(0)) = 0.5·0.5 = 0.25, so ∂L/∂z = −0.25; ∂L/∂w = −0.25·x = −0.5 and ∂L/∂b = −0.25.', r'\frac{\partial L}{\partial w}=\frac{\partial L}{\partial a}\,\frac{\partial a}{\partial z}\,\frac{\partial z}{\partial w}=(-1)(0.25)(2)'),
   step('Update: w = 0.5 − 0.4(−0.5) = 0.7.')],
  'Backpropagation is this chain rule applied layer by layer, reusing ∂L/∂z from the layer above.'),
 problem('taylor', 'Taylor approximation and the Hessian', ['taylor-hessian'],
  'f(x, y) = x² + xy + 2y². Expand around (1, 1) and estimate f(1.1, 0.9).',
  [
   vec('Compute ∇f(1, 1).', [3, 5], ['Differentiate with respect to x and to y.', '∇f = [2x + y, x + 4y].'], '[3, 5].', tol=0),
   num('Compute the first-order estimate of f(1.1, 0.9).', 3.8, ['Start from f(1, 1) and add the gradient times the step h = [0.1, −0.1].', 'f(1, 1) = 4 and ∇f · h = 0.3 − 0.5.'], '4 − 0.2 = 3.8.', tol=1e-6),
   num('Compute the second-order estimate, using the Hessian H = [[2, 1], [1, 4]].', 3.82,
       ['The second-order term is ½ hᵀ H h.', 'H h = [0.1, −0.3], so hᵀ H h = 0.01 + 0.03.'],
       '3.8 + 0.02 = 3.82, which is exact: a quadratic equals its second-order Taylor expansion.', tol=1e-6,
       mistakes=[(3.84, 'You forgot the ½ in front of hᵀHh.'), (3.825, 'The off-diagonal entry counts twice in hᵀHh: 2·1·(0.1)(−0.1).')]),
   choice('The only stationary point is (0, 0). What is it?', 'A minimum', ['A maximum', 'A saddle point', 'Cannot tell without more derivatives'],
          ['The signs of the Hessian\'s eigenvalues decide. Use its trace and determinant to find their signs without computing them.'],
          'trace 6 > 0 and det 7 > 0, so both eigenvalues (3 ± sqrt 2) are positive: H is positive definite and (0, 0) is a minimum.',
          {'A saddle point': 'A saddle needs eigenvalues of opposite signs, which would make det H negative.', 'Cannot tell without more derivatives': 'For a quadratic the Hessian is the whole story.', 'A maximum': 'A maximum needs both eigenvalues negative, so a negative trace.'}),
  ],
  [step('∇f(1, 1) = [3, 5]; first order: 4 + 0.3 − 0.5 = 3.8.'),
   step('Second order: ½ hᵀHh = ½·0.04 = 0.02, giving 3.82 = f(1.1, 0.9).'),
   step('H has trace 6 and det 7, so both eigenvalues are positive: (0, 0) is a minimum.')],
  'The Hessian\'s eigenvalues are the curvatures that set gradient descent\'s safe step size (below 2/L) and its speed (the condition number L/μ).'),
 ])

# ---------------- Probability and statistics ----------------
pd = 0.02*0.95/(0.02*0.95+0.98*0.04); pd2 = pd*0.95/(pd*0.95+(1-pd)*0.04)
homework('math/probability-and-statistics', 'math', 'Probability and statistics',
 'Bayes\' rule, expectation and variance, and maximum likelihood.',
 [
 problem('bayes', 'Screening with Bayes\' rule', ['probability-basics'],
  'A condition affects 2% of people. A test detects it 95% of the time (sensitivity) and gives false positives for 4% of healthy people.',
  [
   choice('Before computing: someone tests positive. Roughly how likely are they to have the condition?', 'Less than 50%', ['About 95%', 'About 50%', 'About 4%'],
          ['Picture 1,000 people: about how many are sick and test positive, and how many are healthy and test positive?'],
          'About 19 sick positives against about 39 healthy positives: most positives are false alarms.',
          {'About 95%': 'That is P(positive | sick). The question asks for P(sick | positive).', 'About 4%': 'That is the false-positive rate. Compare the numbers of sick and healthy positives.'}),
   num('Compute P(positive) (4 decimals).', 0.02*0.95+0.98*0.04,
       ['A positive comes either from a sick person or from a healthy one: add the two cases.', 'P(+) = P(+ | sick)P(sick) + P(+ | healthy)P(healthy).'], '0.019 + 0.0392 = 0.0582.', tol=0.0002),
   num('Compute P(sick | positive) (3 decimals).', pd,
       ['Bayes\' rule reverses the condition.', 'P(sick | +) = P(+ | sick)P(sick)/P(+).'], f'{r(pd,3)}: two thirds of positives are false alarms, because healthy people are so common.',
       mistakes=[(0.95, 'That is P(+ | sick), the sensitivity. Bayes\' rule reverses the condition.'), (0.019, 'That is P(sick and +). Divide by P(+).')]),
   num('A second, independent test is also positive. Compute P(sick | two positives) (3 decimals).', pd2,
       ['After the first test, your previous answer is the new prior.', 'Apply Bayes\' rule again with P(sick) replaced by your previous answer.'],
       f'{r(pd2,3)}: evidence accumulates by multiplying likelihoods.',
       mistakes=[(0.95*0.95, 'That is P(two positives | sick). Use Bayes\' rule with the updated prior.')]),
  ],
  [step('P(+) = 0.95·0.02 + 0.04·0.98 = 0.0582.'),
   step(f'P(sick | +) = 0.019/0.0582 ≈ {r(pd,4)}.', r'P(\text{sick}\mid+)=\frac{P(+\mid\text{sick})\,P(\text{sick})}{P(+)}'),
   step(f'Second test: {r(pd,4)}·0.95/({r(pd,4)}·0.95 + {r(1-pd,4)}·0.04) ≈ {r(pd2,4)}.')],
  'Precision is P(actually positive | predicted positive): with rare positives, even a good classifier has low precision unless its false-positive rate is tiny.'),
 problem('expvar', 'Expectation and variance', ['expectation-variance'],
  'X is the result of one fair six-sided die.',
  [
   num('Compute E[X].', 3.5, ['Each face has probability 1/6.', 'Average the numbers 1 to 6.'], '(1 + ... + 6)/6 = 3.5.'),
   num('Compute Var(X) (3 decimals).', 35/12, ['Var = E[X²] − (E[X])².', 'E[X²] = (1 + 4 + 9 + 16 + 25 + 36)/6 = 91/6.'], f'91/6 − 12.25 = 35/12 ≈ {r(35/12,3)}.',
       mistakes=[(3.5, 'That is the mean. Variance is E[X²] − (E[X])².'), (91/6, 'That is E[X²]; subtract (E[X])².')]),
   num('Compute Var(2X + 1) (3 decimals).', 4*35/12, ['What does adding a constant do to the spread? What does scaling do?', 'Var(aX + b) = a² Var(X).'], f'4·35/12 ≈ {r(35/3,3)}.',
       mistakes=[(2*35/12+1, 'Var(aX + b) = a² Var(X): the +1 drops out and the 2 is squared.'), (2*35/12, 'The scale factor is squared.')]),
   num('How many rolls do you need so that the standard deviation of their average is at most 0.1?', 292,
       ['The variance of an average of n independent rolls is Var(X)/n.', 'Require sqrt(Var(X)/n) ≤ 0.1, that is Var(X)/n ≤ 0.01, and solve for n.'],
       'n ≥ 291.7, so 292 rolls. Halving the error needs four times the data.', tol=0,
       mistakes=[(30, 'You required Var/n ≤ 0.1. The standard deviation is the square root, so require Var/n ≤ 0.01.'), (18, 'The standard deviation shrinks like 1/sqrt n, not 1/n.'), (291, 'That many rolls gives slightly more than 0.1. Round up.')]),
  ],
  [step('E[X] = 3.5, E[X²] = 91/6, Var(X) = 35/12 ≈ 2.917.'),
   step('Var(2X + 1) = 4 Var(X) ≈ 11.667.'),
   step('sd of the average = sqrt(2.917/n) ≤ 0.1 needs n ≥ 291.7: 292 rolls.')],
  'Averages are less variable than single values by a factor 1/n in variance. That is why larger validation sets and k-fold averaging give steadier estimates, and why more precision is expensive.'),
 problem('mle', 'Maximum likelihood', ['likelihood-mle'],
  'Ten coin flips give 7 heads.',
  [
   num('What value of μ = P(heads) maximizes the likelihood of the ten flips?', 0.7,
       ['Write the likelihood μ⁷(1 − μ)³ and take its log.', 'Set the derivative of 7 ln μ + 3 ln(1 − μ) to zero.'], 'μ̂ = 7/10 = 0.7.', tol=1e-6),
   num('How much higher is the log-likelihood at μ̂ than at a fair coin μ = 0.5 (3 decimals)?', (7*np.log(.7)+3*np.log(.3))-10*np.log(.5),
       ['Compute ℓ(μ) = 7 ln μ + 3 ln(1 − μ) at both values.', 'ℓ(0.5) = 10 ln 0.5.'], f'{r(7*np.log(.7)+3*np.log(.3),3)} − ({r(10*np.log(.5),3)}) ≈ {r((7*np.log(.7)+3*np.log(.3))-10*np.log(.5),3)}.'),
   vec('For Gaussian data 2, 4, 9, give the maximum likelihood estimates of the mean and the variance.', [5, 26/3],
       ['The MLE of the mean is the sample average.', 'The MLE of the variance averages the squared deviations: it divides by n.'],
       'Mean 5 and variance (9 + 1 + 16)/3 = 26/3 ≈ 8.667 (the unbiased estimate would divide by 2).', tol=0.002,
       mistakes=[([5, 13], 'Dividing by n − 1 gives the unbiased estimate. Maximum likelihood divides by n.')]),
  ],
  [step('dℓ/dμ = 7/μ − 3/(1 − μ) = 0 gives μ = 0.7.'),
   step(f'ℓ(0.7) ≈ {r(7*np.log(.7)+3*np.log(.3),4)}, ℓ(0.5) ≈ {r(10*np.log(.5),4)}, difference ≈ {r((7*np.log(.7)+3*np.log(.3))-10*np.log(.5),4)}.'),
   step('Gaussian MLE: mean 5, variance 26/3 ≈ 8.667.', r'\hat\sigma^2_{\text{ML}}=\frac1n\sum_{t=1}^{n}(x_t-\bar x)^2')],
  'Least squares is maximum likelihood with Gaussian noise, and the logistic loss is maximum likelihood with Bernoulli labels.'),
 ])

# ---------------- Dimensionality reduction ----------------
P4 = np.array([[4,2],[2,4],[-2,-4],[-4,-2]], float); C4 = P4.T@P4/4
homework('math/dimensionality-reduction', 'math', 'Dimensionality reduction',
 'Principal component analysis: covariance, eigenvectors, and how many components to keep.',
 [
 problem('pca', 'PCA by hand', ['pca', 'dimensionality-reduction'],
  'Four centred points: (4, 2), (2, 4), (−2, −4), (−4, −2). Use the covariance that divides by n = 4.',
  [
   vec('Compute the covariance matrix (4 numbers, row by row).', C4.flatten(),
       ['The mean is already 0, so C = (1/n) Σ x xᵀ.', 'C₁₁ averages the squared first coordinates; C₁₂ averages the products of the two coordinates.'], 'C = [[10, 8], [8, 10]].', tol=0,
       mistakes=[((P4.T@P4/3).flatten(), 'This part divides by n = 4, not n − 1.')]),
   vec('Find its eigenvalues, largest first.', [18, 2], ['Use the trace and the determinant.', 'trace 20, det 100 − 64 = 36.'], '18 (direction [1, 1]/sqrt 2) and 2 (direction [1, −1]/sqrt 2).', tol=1e-6,
       mistakes=[([2, 18], 'Largest first.')]),
   num('What fraction of the variance does the first principal component explain?', 0.9, ['Compare the first eigenvalue with the total variance.', 'λ₁/(λ₁ + λ₂).'], '18/20 = 0.9.', tol=1e-6),
   num('Compute the first principal-component score of the point (4, 2), using the unit direction u₁ = [1, 1]/sqrt 2 (3 decimals).', 6/np.sqrt(2),
       ['The score is the coordinate along u₁.', 'Take the dot product with [1, 1]/sqrt 2.'], f'(4 + 2)/sqrt 2 ≈ {r(6/np.sqrt(2),3)}.',
       mistakes=[(6, 'Use the unit vector [1, 1]/sqrt 2, not [1, 1].'), (-6/np.sqrt(2), 'Your direction is −u₁, equally valid in general; this part fixes u₁ = [1, 1]/sqrt 2.')]),
   vec('Now measure the first coordinate in units 10 times smaller, so every x-value is multiplied by 10. Enter the new covariance matrix (row by row).', [1000, 80, 80, 10],
       ['What happens to a variance when a variable is multiplied by 10? And to a covariance?', 'Var(10X) = 100 Var(X) and Cov(10X, Y) = 10 Cov(X, Y).'],
       'C = [[1000, 80], [80, 10]]: now PC1 is almost the x-axis. A change of units, not the data, decided the principal direction, which is why we standardize first.', tol=0,
       mistakes=[([100, 80, 80, 10], 'Variance scales with the square of the factor.'), ([100, 8, 8, 10], 'Variance scales by the square of the factor, covariance by the factor.')]),
  ],
  [step('C = [[10, 8], [8, 10]], with eigenvalues 18 and 2 and eigenvectors [1, 1]/sqrt 2 and [1, −1]/sqrt 2.'),
   step('PC1 explains 18/20 = 90%. The score of (4, 2) is 6/sqrt 2 ≈ 4.243.'),
   step('Rescaling x by 10 gives C = [[1000, 80], [80, 10]], whose top eigenvector is nearly [1, 0]: PCA follows units unless you standardize.')],
  'PCA picks the directions of largest variance, and the eigenvalues tell you exactly how much is kept or lost, in whatever units you chose.'),
 problem('howmanypc', 'How many components?', ['pca'],
  'A covariance matrix has eigenvalues 6, 2.5, 1, 0.3 and 0.2.',
  [
   num('What is the total variance?', 10, ['The total variance is the trace.', 'The trace is the sum of the eigenvalues.'], '10.', tol=0),
   num('What is the smallest number of components that keeps at least 90% of the variance?', 3,
       ['Add eigenvalues from the largest until you reach 90% of the total.', '90% of 10 is 9.'], '6 + 2.5 = 8.5 (85%) is not enough; adding 1 gives 9.5 (95%): 3 components.', tol=0,
       mistakes=[(2, 'Two components keep 8.5 of 10, which is 85%.')]),
   num('With 2 components, what is the average squared reconstruction error?', 1.5, ['The error comes from the directions you drop.', 'Sum the dropped eigenvalues.'], '1 + 0.3 + 0.2 = 1.5.', tol=1e-6,
       mistakes=[(8.5, 'That is the variance you keep. The error is what you drop.')]),
  ],
  [step('Total variance = trace = 10.'),
   step('Cumulative: 60%, 85%, 95%: keep 3 components for 90%.'),
   step('Dropping 1, 0.3 and 0.2 loses 1.5 on average.')],
  'The same eigenvalue bookkeeping underlies scree plots and the explained-variance ratio in scikit-learn\'s PCA.'),
 ])
