from lib import *
sig = lambda s: 1/(1+np.exp(-s))

# Design rules (from the student trial and the professors' review): prompts ask for quantities and the
# formulas live in the clues; distractors are as specific as the answer; predictable convention errors
# get feedback that diagnoses without giving the answer; each set has a predict or transfer part.

# ---------------- The learning problem ----------------
homework('ml/the-learning-problem', 'ml', 'The learning problem',
 'Framing a prediction task: the kind of learning, the features, and a workflow that does not fool you.',
 [
 problem('kinds', 'Name the problem', ['ml-landscape'],
  'For each task, pick the kind of machine learning.',
  [
   choice('Predict next month\'s electricity use (in kWh) of a household from past bills.', 'Supervised regression', ['Supervised classification', 'Unsupervised clustering', 'Reinforcement learning'],
          ['Is there a known answer in the training data? Is it a number or a category?'], 'Past bills give labelled examples, and the target is an amount: regression.',
          {'Supervised classification': 'kWh is an amount on a continuous scale, not one of a few categories.'}),
   choice('Decide whether an email is spam, using emails that people already marked.', 'Supervised classification', ['Supervised regression (predict a spam score from 0 to 1)', 'Unsupervised clustering', 'Reinforcement learning'],
          ['What are the labels people gave: amounts or categories?'], 'The labels are two categories, so this is (binary) classification, even if the model outputs a probability along the way.',
          {'Supervised regression (predict a spam score from 0 to 1)': 'A classifier may output a probability, but the labels it learns from are the categories "spam" and "not spam".', 'Unsupervised clustering': 'People already marked the emails: those are labels.'}),
   choice('Group shoppers into segments when nobody has labelled any segment.', 'Unsupervised clustering', ['Supervised classification', 'Supervised regression', 'Reinforcement learning'],
          ['Are there labels at all?'], 'With no labels, we look for structure: clustering.',
          {'Supervised classification': 'Classification needs labelled examples of each segment; here there are none.'}),
   choice('Route support tickets to one of 5 teams, numbered 1 to 5, using 2,000 tickets that staff already routed.', 'Supervised classification', ['Supervised regression', 'Unsupervised clustering', 'Reinforcement learning'],
          ['Is team 4 "twice" team 2? What would a prediction of 2.5 mean?'], 'The numbers 1 to 5 are names, not amounts: labelled categories, so classification.',
          {'Supervised regression': 'The team numbers are names, not amounts: predicting 2.5 would mean nothing.', 'Unsupervised clustering': 'There are 5 groups, but staff already labelled every ticket.'}),
  ],
  [step('Ask two questions: are there labels, and is the label an amount or a category? Rewards for actions mean reinforcement learning.'),
   step('Electricity: labelled amount (regression). Spam: labelled category (classification). Segments: no labels (clustering). Tickets: labelled categories that happen to be written as numbers (classification).')],
  'Naming the problem type fixes the loss (squared error for regression, logistic or hinge for classification) and the metrics you report.'),
 problem('features', 'Turning raw data into features', ['feature-representation'],
  'A table has two numeric columns (area, age) and one categorical column, colour, with values red, green, blue and white.',
  [
   vec('One-hot encode colour = green, with the columns in the order red, green, blue, white.', [0, 1, 0, 0],
       ['One-hot uses one column per category.', 'Put a 1 in the column of the actual value and 0 everywhere else.'], '[0, 1, 0, 0].', tol=0),
   num('How many feature columns are there after one-hot encoding colour with one column per colour (none dropped), not counting an intercept?', 6,
       ['The two numeric columns stay as they are.', 'Colour becomes one column per category.'], '2 + 4 = 6.', tol=0,
       mistakes=[(3, 'Colour does not stay one column: it becomes one column per colour.'), (5, 'Dropping one colour is an option (see the last part), but this part keeps all four.')]),
   choice('Why not encode the colours as 1, 2, 3, 4?', 'A linear model would treat the codes as amounts, with an order and spacing the colours do not have',
          ['Four columns use less memory than one', 'A model cannot read numbers that stand for categories', 'It makes no difference for a linear model'],
          ['What does θ · x do with a feature whose value goes up from 1 to 4?'], 'A single number imposes a fake order and fake distances (white would be "four times red"). One-hot lets each category have its own weight.',
          {'It makes no difference for a linear model': 'With a single code the model can only add θ·code: green is forced to lie halfway between red and blue.'}),
   num('The model also has an intercept, a column of 1s. The four colour indicators always add up to 1. How many of them can it keep without the columns becoming linearly dependent?', 3,
       ['Add up the four indicator columns. Which other column do you get?', 'red + green + blue + white is a column of 1s, the same as the intercept.'],
       'Keep 3: one colour becomes the baseline absorbed by the intercept (or drop the intercept instead).', tol=0,
       mistakes=[(4, 'The four indicators add up to the intercept column, so one of the five columns is redundant.')]),
  ],
  [step('green → [0, 1, 0, 0].'),
   step('Columns: area, age, and four colour indicators: 6.'),
   step('Integer codes impose an order and spacing that the categories do not have.'),
   step('With an intercept, the four indicators are linearly dependent on it; keep 3 (the dropped one is the baseline).')],
  'Feature design often matters more than the model, and dependent columns are exactly the rank problem that breaks the normal equation.'),
 problem('workflow', 'A workflow that does not fool you', ['ml-workflow', 'train-validation-test'],
  'You have 1,000 labelled examples and split them 70% / 15% / 15% into training, validation and test sets.',
  [
   num('How many examples are in the training set?', 700, ['70% of the examples.', '0.7 × 1,000.'], '70% of 1,000.', tol=0),
   choice('You want to standardize the features. Where should the means and standard deviations come from?', 'The training set only',
          ['All 1,000 examples, so the means and standard deviations are as accurate as possible', 'Each set separately, so every set is centred at exactly 0', 'The training and validation sets together, keeping only the test set out'],
          ['Anything computed from data you later evaluate on lets that data leak into the model.'],
          'Statistics from the training set only, applied unchanged to validation and test rows; anything else leaks information and makes the scores too optimistic.',
          {'All 1,000 examples, so the means and standard deviations are as accurate as possible': 'That includes the test rows, so their information leaks into training (data leakage).', 'Each set separately, so every set is centred at exactly 0': 'Then the same raw value is scaled differently in each set, and the model sees shifted inputs.', 'The training and validation sets together, keeping only the test set out': 'Validation rows then shape the scaling, so the validation score used for choosing is optimistic.'}),
   choice('You tried 20 settings and chose the one with the best validation score. Which score should you report?', 'The test score of the chosen setting',
          ['The best validation score, since it was measured on data the model was not trained on', 'The average of the 20 validation scores, which is less noisy than any single one', 'The training score of the chosen setting, measured on the most data'],
          ['The validation set was used to choose. Is its best score an honest estimate?'], 'Only data never used for choosing gives an honest estimate, and you compute it once.',
          {'The best validation score, since it was measured on data the model was not trained on': 'You chose this setting because its validation score was the best of 20, so that score is biased upwards.', 'The average of the 20 validation scores, which is less noisy than any single one': 'That averages settings you did not choose; it says nothing about the chosen model.'}),
  ],
  [step('Training: 700, validation: 150, test: 150.'),
   step('Fit scaling on the training rows only.'),
   step('Report the test score once, after all choices are made.')],
  'Every end-to-end project on this site follows this order: lock the test set, choose on validation or cross-validation, report the test score once.'),
 ])

# ---------------- Linear classification ----------------
homework('ml/linear-classification', 'ml', 'Linear classification',
 'Linear classifiers, the perceptron, and its mistake bound.',
 [
 problem('hyperplane', 'Classify with a hyperplane', ['linear-classifier', 'max-margin-svm'],
  'A classifier predicts sign(θ · x + θ₀) with θ = [2, −1] and θ₀ = −1.',
  [
   num('Predict the label of x = [1, 0] (enter +1 or −1).', 1, ['Compute the score θ · x + θ₀.', 'Score = 2·1 − 1·0 − 1; its sign is the label.'], 'Score 1 > 0, so +1.', tol=0),
   num('Predict the label of x = [0, 1].', -1, ['Compute the score θ · x + θ₀.', 'Score = 0 − 1 − 1.'], 'Score −2 < 0, so −1.', tol=0),
   num('Compute the distance from x = [1, 0] to the decision boundary (3 decimals).', 1/np.sqrt(5),
       ['The score is not yet a distance: it changes if you rescale θ and θ₀, while the boundary does not move.', 'Distance = |θ · x + θ₀| / ||θ||.'], f'1/sqrt 5 ≈ {r(1/np.sqrt(5),3)}.',
       mistakes=[(1, 'That is the score θ · x + θ₀, not a distance: doubling θ and θ₀ would double it. What can you divide by so that the result does not change?')]),
   choice('If you double θ and θ₀, what changes?', 'Only the scores, which double; the boundary and all distances stay the same', ['The distance to the boundary doubles', 'The boundary moves', 'All predictions flip'],
          ['Does 2(θ · x + θ₀) = 0 describe a different set of points? What happens to |score|/||θ||?'], 'The boundary {θ · x + θ₀ = 0} is unchanged, and so is the distance |score|/||θ||. This is why margins are measured after dividing by ||θ||.',
          {'The distance to the boundary doubles': 'The score doubles, but so does ||θ||. Distance is |score|/||θ||: what happens to the ratio?', 'The boundary moves': 'The boundary is where θ · x + θ₀ = 0. Is 2(θ · x + θ₀) = 0 a different set of points?', 'All predictions flip': 'Doubling does not change any sign.'}),
  ],
  [step('Scores: [1, 0] → 1 (class +1); [0, 1] → −2 (class −1).'),
   step('Distance of [1, 0]: |1|/sqrt 5 ≈ 0.447.'),
   step('Scaling (θ, θ₀) by 2 doubles the scores but keeps the boundary and distances.')],
  'Because scaling θ changes nothing, the SVM fixes the scale by asking for scores of at least 1 and then makes ||θ|| small.'),
 problem('perceptron', 'Run the perceptron by hand', ['perceptron', 'linear-classifier-through-origin'],
  'Data through the origin: x1 = [1, 2] with y = +1 and x2 = [2, −1] with y = −1. Start with θ = [0, 0] and use the perceptron rule of the page.',
  [
   vec('Visit x1. What is θ afterwards?', [1, 2], ['When does the perceptron update, and how?', 'y(θ · x1) = 0 ≤ 0 counts as a mistake; update θ ← θ + y x1.'], 'θ = [1, 2].', tol=0),
   vec('Now visit x2. What is θ afterwards?', [-1, 3],
       ['Check y(θ · x2) with θ = [1, 2].', 'θ · x2 = 2 − 2 = 0, so it is a mistake. Update with y = −1.'], '[1, 2] − [2, −1] = [−1, 3].', tol=0,
       mistakes=[([1, 2], 'θ · x2 = 0, and the rule updates when y(θ · x) ≤ 0, including 0.'), ([3, 1], 'y = −1, so the update subtracts x2.')]),
   num('Keep going through the data. How many mistakes in total before a full pass with no mistakes?', 2,
       ['Run a second pass with θ = [−1, 3].', 'Compute y(θ · x) for both points.'], 'Second pass: y(θ · x1) = 5 > 0 and y(θ · x2) = 5 > 0, so no more updates: 2 mistakes.', tol=0),
   vec('Start again from θ = [0, 0] but visit x2 first, then x1. What is θ after this pass?', [-1, 3],
       ['Is x2 a mistake at θ = 0? Then check x1 with the new θ.', 'x2 first: θ = −[2, −1] = [−2, 1]; then check y(θ · x1).'],
       'The same θ = [−1, 3]: both points were mistakes, and θ is the sum of y x over the mistakes. In general the order can change the answer.', tol=0,
       mistakes=[([-2, 1], 'Check x1 with θ = [−2, 1]: −2 + 2 = 0 ≤ 0, so it is also a mistake.')]),
  ],
  [step('x1: 0 ≤ 0, update to [1, 2].'),
   step('x2: θ · x2 = 0, update to [1, 2] − [2, −1] = [−1, 3].'),
   step('Pass 2: both margins are 5 > 0. Converged after 2 mistakes.'),
   step('Reverse order: [−2, 1] after x2, then x1 is a mistake too: [−1, 3].')],
  'The perceptron only moves when it is wrong, and each move adds or subtracts one example. The final θ is a sum of the mistaken examples.'),
 problem('bound', 'Check the mistake bound', ['perceptron-convergence', 'linear-separability'],
  'For the same two points, use θ* = [−1, 3] (the perceptron\'s answer) as a separator.',
  [
   num('Compute R², the largest squared length of a data point.', 5, ['Compute ||x||² for both points.', '||[1, 2]||² and ||[2, −1]||².'], 'Both are 5, so R² = 5.', tol=0),
   num('Compute the margin γ of θ* on this data (3 decimals).', 5/np.sqrt(10),
       ['The margin is the smallest signed distance of a point to the boundary.', 'γ = min over points of y(θ* · x)/||θ*||; both points have y(θ* · x) = 5.'], f'5/sqrt 10 ≈ {r(5/np.sqrt(10),3)}.',
       mistakes=[(5, 'Divide by ||θ*|| to turn the score into a distance.')]),
   num('What does the perceptron convergence theorem give as the bound on the number of mistakes?', 2,
       ['The bound compares the data radius with the margin.', 'It is (R/γ)².'],
       'The bound is 2, and the perceptron made exactly 2 mistakes: the bound is tight here.',
       mistakes=[(np.sqrt(2), 'That is R/γ. The bound is its square: (R/γ)² = R²/γ².'), (np.sqrt(10), 'You squared R but not γ: divide R² by γ².')]),
   num('Multiply both points by 10 (θ* unchanged). Before computing, predict: what is the new bound?', 2,
       ['R grows by a factor 10. What happens to every y(θ* · x)?', 'γ also grows by a factor 10.'],
       'Still 2: the bound depends only on the shape of the data (margin relative to radius), not on its scale or on the dimension.', tol=0,
       mistakes=[(200, 'R² grows by 100, but so does γ².'), (20, 'Both R and γ scale by 10; their ratio is unchanged.')]),
  ],
  [step('R² = 5; y(θ*·x) = 5 for both points and ||θ*|| = sqrt 10, so γ = 5/sqrt 10 ≈ 1.581.'),
   step('(R/γ)² = 5/2.5 = 2 mistakes at most, matching what we saw.'),
   step('Scaling the data by 10 multiplies R and γ by 10, so the bound stays 2.')],
  'The bound says: a wide margin relative to the data radius means few mistakes, whatever the scale and the dimension.'),
 ])

# ---------------- Losses and convexity ----------------
homework('ml/losses-and-convexity', 'ml', 'Losses and convexity',
 'Zero-one and hinge loss, the max-margin objective, and convexity.',
 [
 problem('losses', 'Zero-one versus hinge', ['empirical-risk-zero-one', 'hinge-loss', 'surrogate-losses'],
  'θ = [1, −1], no offset. Data: ([2, 0], +1), ([1, 1], +1), ([0, 1], −1), ([1, 0], −1). Let z = y(θ · x) be the signed margin.',
  [
   vec('Compute z for the four points, in order.', [2, 0, 1, -1], ['z is the label times the score.', 'Point 3: score −1 and y = −1.'], 'z = [2, 0, 1, −1].', tol=0),
   num('Compute the zero-one risk.', 0.5, ['A point is a mistake when z ≤ 0.', 'Count those points and divide by 4.'], 'Points 2 and 4: 2/4 = 0.5.', tol=1e-6,
       mistakes=[(0.25, 'z = 0 counts as a mistake: the point is on the boundary.')]),
   num('Compute the average hinge loss.', 0.75, ['The hinge loss of a point is max(0, 1 − z).', 'Compute it for z = 2, 0, 1, −1 and average.'], '(0 + 1 + 0 + 2)/4 = 0.75.', tol=1e-6,
       mistakes=[(0.5, 'That is the zero-one risk. The hinge loss is max(0, 1 − z).')]),
   vec('Add a fifth point x = [0.5, 0] with y = +1. Give its z, its zero-one loss and its hinge loss.', [0.5, 0, 0.5],
       ['Is it on the correct side of the boundary? Is its margin at least 1?', 'z = 0.5: correct side, but inside the margin.'],
       'z = 0.5, zero-one loss 0, hinge loss 0.5. Only the hinge loss notices points that are right but too close, and that pressure is what widens the margin.', tol=1e-6,
       mistakes=[([0.5, 1, 0.5], 'z > 0 means correctly classified: zero-one loss 0.'), ([0.5, 0, 0], 'Correct, but z < 1: the hinge still charges 1 − z.')]),
  ],
  [step('z = [2, 0, 1, −1].'),
   step('Zero-one: two points with z ≤ 0, risk 0.5.'),
   step('Hinge: [0, 1, 0, 2], average 0.75. The hinge loss is a convex upper bound on the zero-one loss.'),
   step('The fifth point: z = 0.5, zero-one 0, hinge 0.5.')],
  'The zero-one loss is flat almost everywhere, so it gives no gradient; the hinge loss is convex and says how wrong, or how nearly wrong, each point is.'),
 problem('svm', 'The max-margin objective', ['max-margin-svm'],
  'Same data (the first four points) and θ = [1, −1] as the previous problem.',
  [
   num('Compute the SVM objective with λ = 0.1.', 0.85, ['The objective is the penalty plus the average hinge loss; the page writes the penalty as (λ/2)||θ||².', '||θ||² = 2, so the penalty is 0.05·2; add the average hinge loss from the previous problem.'], '0.1 + 0.75 = 0.85.', tol=1e-6,
       mistakes=[(0.95, 'The penalty is (λ/2)||θ||², not λ||θ||².'), (0.1, 'That is only the penalty; add the average hinge loss.')]),
   num('Compute the margin width (3 decimals).', 2/np.sqrt(2), ['The margin lines are where the score equals +1 and −1.', 'Their distance apart is 2/||θ||.'], f'2/sqrt 2 ≈ {r(np.sqrt(2),3)}.',
       mistakes=[(1/np.sqrt(2), 'That is the distance from the boundary to one margin line; the width spans both sides.')]),
   choice('Increasing λ makes the optimal θ...', 'smaller, so the margin gets wider and more points may violate it', ['larger, so the margin gets narrower', 'unchanged, because λ only rescales the objective', 'exactly zero for any λ > 0'],
          ['λ multiplies ||θ||² in the objective.'], 'A stronger penalty shrinks ||θ||, and the margin 2/||θ|| widens, at the cost of more hinge loss.',
          {'unchanged, because λ only rescales the objective': 'λ scales only the penalty term, not the hinge term, so it changes the balance between them.'}),
  ],
  [step('Objective = 0.05·2 + 0.75 = 0.85.'),
   step('Margin width 2/||θ|| = sqrt 2 ≈ 1.414.'),
   step('Larger λ favours small ||θ||: wider margin, more violations tolerated.')],
  'λ trades a wide margin (simplicity) against fitting every point, the same trade as ridge regression.'),
 problem('convex', 'Is it convex?', ['convex-functions'],
  'A function is convex if the chord between any two points on its graph lies on or above the graph.',
  [
   choice('Which function is NOT convex on the real line?', 'x³', ['x²', '|x|', 'max(0, 1 − x)'],
          ['Check the second derivative where it exists; corners are allowed.'], 'x³ curves downward for x < 0 (its second derivative 6x is negative there). |x| and the hinge have corners but still lie below their chords.',
          {'|x|': '|x| has a corner at 0 but lies below every chord: convex.', 'max(0, 1 − x)': 'The maximum of two linear functions is convex.'}),
   num('For f(x) = x², how far does the midpoint of the chord from x = 1 to x = 3 lie above the graph?', 1,
       ['The chord\'s midpoint has height (f(1) + f(3))/2.', 'Subtract the graph\'s height at the midpoint x = 2.'], '(1 + 9)/2 − 4 = 1 ≥ 0, as convexity requires.', tol=1e-6,
       mistakes=[(5, 'That is the height of the chord\'s midpoint; subtract f(2).')]),
   choice('Why does convexity matter for training?', 'Every local minimum is a global minimum, so gradient descent cannot get stuck in a worse valley',
          ['Gradient descent then reaches the minimum in one step', 'The minimizer is always unique', 'Convex losses are always differentiable'],
          ['Think about what can go wrong when a loss has several valleys.'], 'For a convex loss, any point where the (sub)gradient is zero is a global minimum.',
          {'The minimizer is always unique': 'Not always: the average hinge loss can be flat along a whole segment. Convexity rules out worse valleys, not ties.', 'Convex losses are always differentiable': '|x| is convex but has a corner at 0; that is why subgradients exist.', 'Gradient descent then reaches the minimum in one step': 'It still needs many steps; convexity only guarantees it is heading for the right place.'}),
  ],
  [step('x³ has negative second derivative for x < 0, so it is not convex.'),
   step('Chord midpoint minus graph: 5 − 4 = 1 ≥ 0.'),
   step('Convex losses have no bad local minima.')],
  'Squared, hinge and logistic losses are convex in θ for linear models; neural network losses are not, which is why their training is harder.'),
 ])

# ---------------- Optimization ----------------
k1 = int(np.ceil(np.log(1e-3)/np.log(0.6))); k2 = int(np.ceil(np.log(1e-6)/np.log(1-1/40))); k3 = int(np.ceil(np.log(1e-6)/np.log(1-1/80)))
homework('ml/optimization', 'ml', 'Optimization',
 'Gradient descent and its step size, conditioning, stochastic subgradient steps, and constraints.',
 [
 problem('step', 'Choose the step size', ['gradient-descent-method'],
  'Minimize J(θ) = 2(θ − 1)² by gradient descent from θ = 3.',
  [
   num('With α = 0.1, compute θ after one step.', 2.2, ['Compute J\'(θ) at θ = 3.', 'J\'(θ) = 4(θ − 1); step θ − α J\'(θ).'], '3 − 0.1·8 = 2.2.', tol=1e-6,
       mistakes=[(3.8, 'Gradient descent moves against the gradient: subtract α J\'(θ).')]),
   num('Each step multiplies the distance to the minimum by the same factor. What is it for α = 0.1?', 0.6,
       ['Write the update for θ − 1 instead of θ.', 'θ − 1 ← (θ − 1) − α·4(θ − 1) = (1 − 4α)(θ − 1).'], '1 − 4α = 0.6.', tol=1e-6),
   num('Above which α does gradient descent diverge?', 0.5, ['It diverges when the factor from (b) has absolute value above 1.', 'Solve |1 − 4α| > 1 for α > 0.'], 'α > 0.5 = 2/L, where L = 4 is the curvature.', tol=1e-6,
       mistakes=[(0.25, 'That is the step that jumps to the minimum in one move (factor 0). Divergence starts when the factor passes −1.')]),
   num('With α = 0.1, how many steps until the distance is strictly below 1/1000 of its start?', k1,
       ['You need the smallest k with (factor)ᵏ < 0.001.', 'k > ln(0.001)/ln(0.6).'], f'ln 0.001/ln 0.6 ≈ {r(np.log(1e-3)/np.log(0.6),2)}, so k = {k1}.', tol=0,
       mistakes=[(k1-1, 'Check that power: it is still above 0.001. Round up.')]),
  ],
  [step('J\'(3) = 8, so θ = 3 − 0.8 = 2.2.'),
   step('Distance factor 1 − 4α = 0.6; divergence when |1 − 4α| > 1, that is α > 2/L = 0.5.'),
   step(f'0.6ᵏ < 10⁻³ needs k > 13.5, so {k1} steps.')],
  'The step size is set by the largest curvature L, and the speed by how the curvatures compare, as the next problem shows.'),
 problem('kappa', 'Conditioning decides the speed', ['gradient-descent-method', 'momentum'],
  'A quadratic loss has Hessian eigenvalues L = 20 and μ = 0.5. Use the step α = 1/L.',
  [
   num('Compute the condition number κ.', 40, ['κ compares the largest and smallest curvature.', 'κ = L/μ.'], '40.', tol=0),
   num('How many steps until the error along the slowest direction is below 10⁻⁶ of its start?', k2,
       ['Along an eigen-direction with curvature λ, each step multiplies the error by 1 − αλ. Which direction is slowest?', 'The slowest factor is 1 − μ/L = 1 − 1/40; solve (1 − 1/40)ᵏ < 10⁻⁶.'], f'k = {k2}, roughly κ ln(10⁶) ≈ 553.', tol=1,
       mistakes=[(int(np.ceil(np.log(1e-6)/np.log(1-20/20.5))), 'That uses the fast direction. The slow direction has the smallest curvature μ.')]),
   num('Now μ = 0.25 (κ = 80). Before computing, predict the rough effect, then give the number of steps.', k3,
       ['About how does the step count depend on κ?', 'Solve (1 − 1/80)ᵏ < 10⁻⁶.'], f'k = {k3}: doubling κ roughly doubles the steps, about κ ln(1/ε).', tol=2,
       mistakes=[(k2, 'That is the old count; κ doubled.')]),
   choice('Which change would reduce the number of steps the most?', 'Rescaling the features so the curvatures become similar', ['Using α = 3/L', 'Starting closer to zero', 'Collecting more data'],
          ['What would κ be if both curvatures were equal?'], 'With κ close to 1 gradient descent needs only a few steps. Momentum helps too, bringing the dependence down to about sqrt κ.',
          {'Using α = 3/L': 'Any α above 2/L diverges along the steepest direction.', 'Starting closer to zero': 'The number of steps depends on the ratio of errors, not on where you start.'}),
  ],
  [step('κ = 20/0.5 = 40.'),
   step(f'The slow direction shrinks by 1 − 1/40 per step: (0.975)ᵏ < 10⁻⁶ gives k = {k2}.'),
   step(f'With κ = 80: k = {k3}, about twice as many.'),
   step('Standardizing features lowers κ; momentum reduces the dependence to about sqrt κ.')],
  'The diabetes project measured this: κ = 464 predicted about 6,400 steps, and it took 5,883.'),
 problem('ssgd', 'One stochastic subgradient step', ['stochastic-subgradient-descent', 'subgradients'],
  'Train an SVM with the stochastic subgradient rule of the SSGD page, with λ = 0.1 and step η = 0.5. The current θ is [0.5, 0].',
  [
   num('The random example is x = [1, 1] with y = −1. Compute y(θ · x).', -0.5, ['Score first, then multiply by the label.', 'θ · x = 0.5.'], '−1·0.5 = −0.5.', tol=1e-6),
   vec('Compute the new θ (3 decimals).', [0.95*0.5-0.5, -0.5],
       ['The rule has two cases, depending on whether y(θ · x) ≤ 1. Which applies here?', 'Here θ ← (1 − ηλ)θ + η y x.'], '0.95·[0.5, 0] − 0.5·[1, 1] = [−0.025, −0.5].', tol=0.001,
       mistakes=[([0.475, 0], 'This example is inside the margin (−0.5 ≤ 1), so the hinge term η y x also acts.'), ([0, -0.5], 'Do not forget the shrink factor (1 − ηλ) on the old θ.')]),
   vec('Instead, suppose the example had y(θ · x) = 2. Starting again from θ = [0.5, 0], compute the new θ (3 decimals).', [0.475, 0],
       ['2 > 1: which case of the rule applies?', 'Only the shrink factor (1 − ηλ) acts.'],
       '(1 − ηλ) comes from the regularizer and acts on every step; η y x comes from the hinge loss and acts only on points inside the margin.', tol=0.001,
       mistakes=[([0.5, 0], 'The factor (1 − ηλ) still applies: it is the gradient step of (λ/2)||θ||².')]),
   choice('At z = y(θ · x) = 1 exactly, the hinge loss max(0, 1 − z) has a corner. Which slopes (with respect to z) are valid subgradients there?', 'Any value between −1 and 0', ['Only 0', 'Only −1', 'Any real number'],
          ['What is the slope just left of the corner, and just right of it?'], 'Left of the corner the slope is −1, right of it 0; at a corner of a convex function every slope in between is a subgradient.',
          {'Only 0': 'That is the slope to the right of the corner only.', 'Only −1': 'That is the slope to the left of the corner only.', 'Any real number': 'A subgradient line must stay below the graph; slopes outside [−1, 0] cut through it.'}),
  ],
  [step('y(θ · x) = −0.5 ≤ 1: the hinge is active.'),
   step('θ = 0.95[0.5, 0] + 0.5(−1)[1, 1] = [−0.025, −0.5].'),
   step('With y(θ · x) = 2 only the shrink acts: [0.475, 0].'),
   step('At the corner, subgradients fill the interval [−1, 0].')],
  'SSGD is cheap because each step uses one example; the (1 − ηλ) factor is the regularizer shrinking the weights every time.'),
 problem('lagrange', 'Minimize with a constraint', ['lagrange-multipliers'],
  'Minimize f(x, y) = x² + y² subject to x + 2y = 5. Use the page\'s convention ∇f + λ∇h = 0 with h(x, y) = x + 2y − 5.',
  [
   vec('Find the minimizer (x, y).', [1, 2],
       ['Write ∇f + λ∇h = 0 component by component, together with the constraint.', '2x + λ = 0 and 2y + 2λ = 0 give x = −λ/2 and y = −λ; substitute into the constraint.'],
       'x + 2y = −λ/2 − 2λ = 5 gives λ = −2, so (x, y) = (1, 2).', tol=1e-6),
   num('What is λ with this convention?', -2, ['Use either component equation with your x and y.', 'From 2x + λ = 0.'], 'λ = −2. (With the convention ∇f = λ∇h you would get +2; the sign depends on the convention.)', tol=0,
       mistakes=[(2, 'That is the value for the convention ∇f = λ∇h. With ∇f + λ∇h = 0 the sign flips.')]),
   num('What is the minimum value of f?', 5, ['Evaluate f at the minimizer.', 'x² + y² at (1, 2).'], '1 + 4 = 5: the squared distance from the origin to the line.', tol=0,
       mistakes=[(np.sqrt(5), 'f is the squared distance, x² + y², not the distance.')]),
  ],
  [step('2x + λ = 0, 2y + 2λ = 0, x + 2y = 5.'),
   step('x = −λ/2, y = −λ; −λ/2 − 2λ = 5 gives λ = −2, so (1, 2).'),
   step('f(1, 2) = 5. Geometrically, (1, 2) is the point on the line closest to the origin, in the direction of the normal [1, 2].')],
  'The hard-margin SVM is solved with exactly these conditions, extended to inequality constraints.'),
 ])

# ---------------- Regression ----------------
xs = np.array([0,1,2,3.]); ys = np.array([1,3,4,8.])
Xd = np.c_[np.ones(4), xs]; w = np.linalg.solve(Xd.T@Xd, Xd.T@ys); pr = Xd@w; rs = ys-pr
sse = (rs**2).sum(); sst = ((ys-ys.mean())**2).sum()
homework('ml/regression', 'ml', 'Regression',
 'Fitting and reporting a line, feature scaling, and multicollinearity.',
 [
 problem('fit', 'Fit and report a line', ['least-squares-normal-equation', 'linear-regression'],
  'Fit y = θ₀ + θ₁x by least squares to (0, 1), (1, 3), (2, 4), (3, 8).',
  [
   num('Compute the least-squares slope θ₁.', w[1],
       ['For one feature, the slope is Σ(x − x̄)(y − ȳ) / Σ(x − x̄)².', 'x̄ = 1.5 and ȳ = 4; the numerator is 11 and the denominator 5.'], '11/5 = 2.2.', tol=1e-6),
   num('Compute the intercept θ₀.', w[0], ['The least-squares line passes through the point of means (x̄, ȳ).', 'θ₀ = ȳ − θ₁x̄.'], '4 − 2.2·1.5 = 0.7.', tol=1e-6),
   num('Compute the RMSE on these points (3 decimals).', np.sqrt(sse/4),
       ['Compute the four residuals y − ŷ, square them and average them over the n = 4 points.', 'Residuals 0.3, 0.1, −1.1, 0.7; then take the square root of the mean.'], f'sqrt(1.8/4) ≈ {r(np.sqrt(sse/4),3)}.',
       mistakes=[(sse/4, 'That is the mean squared error. Take the square root for RMSE.'), (np.sqrt(sse/2), 'That divides by n − 2, the residual standard error that statistics software calls "Root MSE". RMSE here divides by n, as on the Least Squares page.'), (np.sqrt(sse/3), 'That divides by n − 1. RMSE divides by n.')]),
   num('Compute the MAE.', np.abs(rs).mean(), ['MAE averages the absolute residuals.', 'Use the same four residuals, without squaring.'], f'(0.3 + 0.1 + 1.1 + 0.7)/4 = {r(np.abs(rs).mean(),3)}.', tol=1e-6),
   num('Compute R² (3 decimals).', 1-sse/sst, ['R² compares the squared error with that of always predicting the mean.', 'R² = 1 − SSE/SST, with SST = Σ(y − ȳ)².'], f'1 − 1.8/26 ≈ {r(1-sse/sst,3)}.',
       mistakes=[(sse/sst, 'That is SSE/SST, the unexplained fraction. R² is 1 minus it.')]),
  ],
  [step('x̄ = 1.5, ȳ = 4, Sxy = 11, Sxx = 5: θ₁ = 2.2, θ₀ = 0.7.'),
   step('Residuals 0.3, 0.1, −1.1, 0.7: SSE = 1.8, RMSE = sqrt(1.8/4) ≈ 0.671, MAE = 0.55.'),
   step('SST = 26, R² = 1 − 1.8/26 ≈ 0.931.')],
  'RMSE and MAE are in the units of y; R² compares with predicting the mean. Report them on test data, where R² can be negative.'),
 problem('scale', 'Scaling and the original units', ['feature-scaling'],
  'Floor area has training mean 100 m² and standard deviation 25 m². A model fitted on the standardized area z is ŷ = 300 + 40z (price in thousands).',
  [
   num('Compute z for an area of 150 m².', 2, ['Standardizing subtracts the mean and divides by the standard deviation.', '(150 − 100)/25.'], '(150 − 100)/25 = 2.', tol=0),
   num('What is the slope in the original units (thousands per m²)?', 1.6, ['Substitute z = (x − 100)/25 into the model.', '40z = (40/25)(x − 100).'], '40/25 = 1.6 per m².', tol=1e-6,
       mistakes=[(40, 'That is the change per standard deviation (25 m²). Convert to one m².'), (1000, 'Divide by the standard deviation, do not multiply.')]),
   num('What is the intercept in the original units?', 140, ['Expand 300 + 1.6(x − 100).', 'The constant part is 300 − 1.6·100.'], '300 − 160 = 140.', tol=0),
   num('Instead, you fit plain least squares on the raw area in m². What does that model predict for 150 m²?', 380,
       ['Standardizing is only a change of units for the feature. Does it change what plain least squares predicts?', 'Use your slope and intercept in original units, or the z-model with z = 2.'],
       '140 + 1.6·150 = 300 + 40·2 = 380: scaling does not change least-squares predictions, only the numbers you read off.', tol=0,
       mistakes=[(360, '300 + 40·1.5 mixes units: for 150 m² the standardized value is 2.')]),
   choice('The test set has mean area 110. Which mean do you use to standardize test rows?', '100, the training mean', ['110, the test mean', '105, the average of the two', 'None: test rows are not scaled'],
          ['The model learned what z = 0 means from the training data.'], 'Use the training statistics for every new row; otherwise the same area gets different z values.',
          {'110, the test mean': 'Then 110 m² would get z = 0 on the test set but z = 0.4 in training: the model sees shifted inputs.', 'None: test rows are not scaled': 'The model expects standardized inputs; raw areas would be off by a factor of 25.'}),
  ],
  [step('z = (150 − 100)/25 = 2.'),
   step('ŷ = 300 + 40(x − 100)/25 = 140 + 1.6x.'),
   step('A raw-units fit gives the same line: 140 + 1.6·150 = 380.'),
   step('Always standardize new data with the training mean and standard deviation.')],
  'Scaling does not change the predictions of plain least squares; it does change gradient descent\'s speed and the effect of ridge and lasso penalties.'),
 problem('collinear', 'Diagnose multicollinearity', ['multicollinearity', 'eigenvalues-eigenvectors'],
  'Two standardized features have correlation 0.8, so C = [[1, 0.8], [0.8, 1]].',
  [
   vec('Compute C·[1, −1].', [0.2, -0.2], ['Multiply row by row.', 'Row 1: 1·1 + 0.8·(−1).'], 'C[1, −1] = [0.2, −0.2] = 0.2·[1, −1]: an eigenvector with eigenvalue 0.2. The direction "feature 1 minus feature 2" is one the data barely see.', tol=1e-6),
   vec('Find both eigenvalues of C, largest first.', [1.8, 0.2], ['You just found one eigenvector. Try the other natural direction, [1, 1].', 'C[1, 1] = [1.8, 1.8].'], '1.8 (along [1, 1]) and 0.2 (along [1, −1]).', tol=1e-6,
       mistakes=[([0.2, 1.8], 'Largest first.')]),
   num('Compute the condition number κ.', 9, ['κ compares the largest and smallest eigenvalues.', 'κ = λ_max/λ_min.'], '1.8/0.2 = 9.', tol=1e-6),
   num('Compute each feature\'s VIF (3 decimals).', 1/(1-0.64), ['VIF_j = 1/(1 − R_j²), where R_j² is how well the other features predict feature j.', 'With two features, R² = ρ².'], '1/(1 − 0.64) ≈ 2.778.',
       mistakes=[(5, 'Use R² = ρ², not ρ.')]),
   vec('With ridge λ = 0.2, compute the new condition number and the shrink factor of the weak direction.', [2/0.4, 0.5],
       ['Ridge adds λ to every eigenvalue.', 'κ = (1.8 + 0.2)/(0.2 + 0.2); the shrink factor is λ₂/(λ₂ + λ).'], 'κ = 2.0/0.4 = 5 and shrink factor 0.2/0.4 = 0.5.', tol=1e-6,
       mistakes=[([9, 0.5], 'Ridge changes the condition number: add λ to both eigenvalues.')]),
  ],
  [step('C[1, −1] = 0.2·[1, −1] and C[1, 1] = 1.8·[1, 1], so the eigenvalues are 1.8 and 0.2 (in general 1 ± ρ); κ = 9.'),
   step('VIF = 1/(1 − 0.64) ≈ 2.78: each weight\'s variance is almost 3 times what it would be with uncorrelated features.'),
   step('Ridge with λ = 0.2: eigenvalues 2.0 and 0.4, κ = 5; the weak direction is shrunk by half.')],
  'Moderate correlation is harmless; VIFs above about 10 (the diabetes data reach 58) make individual weights unreliable.'),
 ])

# ---------------- Generalization and regularization ----------------
cv = np.array([0.30,0.26,0.34,0.28,0.32]); se = cv.std(ddof=1)/np.sqrt(5)
homework('ml/generalization-and-regularization', 'ml', 'Generalization and regularization',
 'Overfitting, bias and variance, ridge and lasso, and honest evaluation with validation, cross-validation and the bootstrap.',
 [
 problem('ridge', 'Ridge and lasso by hand', ['ridge-regularization', 'lasso'],
  'One feature, no intercept, n = 5 examples with Σx² = 10 and Σxy = 12.',
  [
   num('Compute the least-squares weight.', 1.2, ['Use the normal equation for one feature.', 'θ = Σxy / Σx².'], '12/10 = 1.2.', tol=1e-6),
   num('Compute the ridge weight with λ = 0.4, using the ridge system of the Ridge page.', 1.0, ['The page\'s ridge system adds nλ to Σx²: (Σx² + nλ)θ = Σxy.', 'nλ = 5·0.4 = 2.'], '12/(10 + 2) = 1.0.', tol=1e-6,
       mistakes=[(12/10.4, 'The page\'s ridge system adds nλ, not λ, to Σx².')]),
   num('A standardized feature has least-squares weight w = 0.9. Compute its lasso weight for λ = 0.3.', 0.6, ['The Lasso page gives the one-feature solution by soft-thresholding.', 'θ = sign(w)·max(|w| − λ, 0).'], '0.9 − 0.3 = 0.6.', tol=1e-6),
   num('From which λ onward is that lasso weight exactly 0?', 0.9, ['When does max(|w| − λ, 0) become 0?'  , 'When λ ≥ |w|.'], 'λ ≥ 0.9: lasso switches the feature off.', tol=1e-6),
   num('For the same standardized feature, the ridge weight is w/(1 + λ). Compute it at λ = 0.9 (3 decimals).', 0.9/1.9, ['Divide w by 1 + λ.', '0.9/1.9.'], f'{r(0.9/1.9,3)}: ridge only shrinks; it never reaches 0.',
       mistakes=[(0, 'That is lasso at λ = 0.9; ridge divides and never reaches 0.')]),
   choice('Why does lasso reach exactly 0 here while ridge does not?', 'Ridge divides by (1 + λ), which never makes a nonzero weight 0; lasso subtracts λ and stops at 0', ['Ridge uses a smaller λ', 'Lasso ignores the data when λ is large', 'Ridge weights are always above 1'],
          ['Compare the two formulas: which one can produce exactly 0?'], 'Subtracting a fixed amount and clipping at 0 (soft-thresholding) gives exact zeros; dividing never does. That is why lasso selects features.',
          {'Ridge uses a smaller λ': 'Both used λ = 0.9 here.'}),
  ],
  [step('Least squares: 12/10 = 1.2. Ridge: 12/(10 + 5·0.4) = 1.0.'),
   step('Lasso on a standardized feature: soft threshold 0.9 − 0.3 = 0.6, and 0 once λ ≥ 0.9.'),
   step('Ridge at λ = 0.9: 0.9/1.9 ≈ 0.474, still nonzero.')],
  'Ridge shrinks every weight a bit; lasso subtracts a fixed amount and stops at zero, which selects features.'),
 problem('bv', 'Bias, variance and the gap', ['model-complexity-generalization', 'bias-variance'],
  'Model A: training error 0.10, test error 0.55. Model B: training error 0.40, test error 0.45.',
  [
   vec('Compute the generalization gap (test − training) of A and of B.', [0.45, 0.05], ['Subtract the training error from the test error for each model.'  , 'A: 0.55 − 0.10.'], 'A: 0.45, B: 0.05.', tol=1e-6),
   choice('Which model would you deploy, and what is A\'s problem?', 'B; A overfits (low training error, much higher test error)', ['A, because its training error is lower', 'B; A underfits', 'Neither: both overfit'],
          ['Which model does better on data it has not seen?'], 'Test error decides. A\'s large gap is the signature of high variance (overfitting).',
          {'B; A underfits': 'Underfitting shows as high error on both sets; A fits its training data very well.', 'A, because its training error is lower': 'Training error rewards memorizing; the test error is what counts.'}),
   num('For another model, bias² = 0.05, variance = 0.10 and noise = 0.20. What is its expected squared test error?', 0.35, ['The bias-variance page decomposes the expected test error into three parts.', 'Add bias², variance and noise.'], '0.35.', tol=1e-6),
   choice('Which change mainly reduces variance without adding bias?', 'Collecting more training data', ['Using a more flexible model', 'Removing regularization', 'Adding more features'],
          ['What happens to the spread of fitted models when each is trained on more data?'], 'More data steadies the fit without restricting the model. Regularization also lowers variance but adds some bias.',
          {'Using a more flexible model': 'That lowers bias and usually raises variance.', 'Removing regularization': 'That lowers bias and raises variance.'}),
  ],
  [step('Gaps: A 0.45, B 0.05. Deploy B; A overfits.'),
   step('Expected error 0.05 + 0.10 + 0.20 = 0.35. The noise part cannot be removed by any model.'),
   step('More data lowers variance without adding bias.')],
  'Regularization, validation and cross-validation are all tools for managing this trade-off.'),
 problem('cvboot', 'Cross-validation and the bootstrap', ['train-validation-test', 'cross-validation', 'bootstrap'],
  'Five-fold cross-validation of one setting gives validation errors 0.30, 0.26, 0.34, 0.28, 0.32.',
  [
   num('Compute the CV score.', 0.30, ['The CV score averages the fold errors.', 'Sum the five errors and divide by 5.'], '1.50/5 = 0.30.', tol=1e-6),
   num('Compute its standard error: the sample standard deviation of the five errors (dividing by n − 1), divided by sqrt 5 (4 decimals).', se,
       ['Start from the deviations from the mean 0.30.', 'Deviations 0, −0.04, 0.04, −0.02, 0.02: sum of squares 0.004; divide by 4, take the root, then divide by sqrt 5.'], f'sd = sqrt(0.001) ≈ 0.0316; SE ≈ {r(se,4)}.', tol=0.0002,
       mistakes=[(np.std(cv)/np.sqrt(5), 'That uses the sd with n in the denominator; the prompt asks for n − 1.'), (cv.std(ddof=1), 'That is the sd of the folds; divide by sqrt 5 for the standard error of their mean.')]),
   choice('Four penalties have CV errors 0.300 (λ = 0.01, SE 0.014), 0.305 (λ = 0.1), 0.312 (λ = 1) and 0.360 (λ = 10). Which does the one-standard-error rule choose?', 'λ = 1', ['λ = 0.01', 'λ = 0.1', 'λ = 10'],
          ['The rule: among settings whose CV error is within one SE of the best, take the simplest, which is the most regularized (largest λ). See Train, Validation and Test.'],
          'The threshold is 0.300 + 0.014 = 0.314; λ = 1 is within it and is the most regularized such setting.',
          {'λ = 0.01': 'That has the lowest CV error, but the rule prefers the simplest model that is statistically as good.', 'λ = 0.1': 'λ = 0.1 is within one SE, but λ = 1 is also within it and is simpler.', 'λ = 10': '0.360 is above the threshold.'}),
   choice('Same CV errors, but now the best setting\'s SE is 0.004. Which λ does the rule choose?', 'λ = 0.01', ['λ = 0.1', 'λ = 1', 'λ = 10'],
          ['Recompute the threshold: best CV error plus one SE.'], 'The threshold is 0.304, and only λ = 0.01 is within it: when scores are less noisy, the data can tell the settings apart and the rule stays with the best.',
          {'λ = 0.1': '0.305 is above 0.300 + 0.004.', 'λ = 1': '0.312 is above the new threshold.'}),
   num('A bootstrap resample of n = 10 examples: what is the probability that a given example is left out (3 decimals)?', 0.9**10, ['Each of the n draws misses that example with probability 1 − 1/n.', 'The draws are independent: multiply.'], f'0.9¹⁰ ≈ {r(0.9**10,3)} (for large n, about 0.368).',
       mistakes=[(0.1, 'That is the chance one draw picks it. Being left out means all 10 draws miss it.')]),
  ],
  [step('CV = 0.30; sd = sqrt(0.004/4) ≈ 0.0316; SE ≈ 0.0141.'),
   step('One-SE rule: threshold 0.314, largest λ below it is 1. With SE 0.004 the threshold is 0.304, so λ = 0.01.'),
   step('P(left out) = 0.9¹⁰ ≈ 0.349.')],
  'Cross-validation chooses settings; the bootstrap tells you how much a number could change with different data. The diabetes project uses both.'),
 ])

# ---------------- Logistic regression ----------------
s0 = 0.5; h0 = sig(s0)
pos = [0.9,0.7,0.4]; neg = [0.8,0.3,0.2,0.1]; auc = np.mean([[p>n for n in neg] for p in pos])
pos2 = pos + [0.3]; auc2 = np.mean([[1 if p>n else 0.5 if p==n else 0 for n in neg] for p in pos2])
homework('ml/logistic-regression', 'ml', 'Logistic regression',
 'Probabilities from the sigmoid, the logistic loss and its gradient, and evaluating a classifier.',
 [
 problem('prob', 'Probability, loss and one gradient step', ['logistic-regression', 'logistic-loss'],
  'θ = [1, −2], θ₀ = 0.5. An example has x = [2, 1] and true label y = 0.',
  [
   num('Compute the score s.', 0.5, ['s = θ · x + θ₀.', '2 − 2 + 0.5.'], '2 − 2 + 0.5 = 0.5.', tol=1e-6),
   num('Compute the predicted probability h that y = 1 (3 decimals).', h0, ['h = σ(s).', 'σ(s) = 1/(1 + e^(−s)) and e^(−0.5) ≈ 0.6065.'], f'1/1.6065 ≈ {r(h0,3)}.'),
   num('Compute the logistic loss for y = 0 (3 decimals).', -np.log(1-h0), ['The loss is minus the log of the probability given to the true label.', 'For y = 0 that probability is 1 − h.'], f'−ln({r(1-h0,4)}) ≈ {r(-np.log(1-h0),3)}.',
       mistakes=[(-np.log(h0), 'That is the loss for y = 1. For y = 0 use the probability of class 0.')]),
   num('With learning rate 1, what is θ₀ after one gradient step (3 decimals)?', 0.5-h0, ['The Logistic Loss page gives ∂J/∂θ₀ = h − y.', 'θ₀ ← θ₀ − 1·(h − y).'], f'0.5 − {r(h0,4)} ≈ {r(0.5-h0,3)}: the score goes down, lowering the probability of the wrong class.',
       mistakes=[(0.5+h0, 'Gradient descent subtracts the gradient.')]),
   num('If the true label were y = 1 instead, what would θ₀ be after the same step (3 decimals)?', 1.5-h0, ['The gradient is still h − y, now with y = 1.', 'h − 1 is negative, so θ₀ goes up.'], f'0.5 − ({r(h0,4)} − 1) ≈ {r(1.5-h0,3)}. The update is "error times input": the sign of h − y decides the direction.',
       mistakes=[(0.5-h0, 'That is the step for y = 0; now h − y = h − 1.')]),
  ],
  [step(f's = 0.5, h = σ(0.5) ≈ {r(h0,4)}.'),
   step(f'Loss for y = 0: −ln(1 − h) ≈ {r(-np.log(1-h0),4)}.'),
   step(f'Gradient for θ₀: h − y. For y = 0: θ₀ ≈ {r(0.5-h0,4)}; for y = 1: θ₀ ≈ {r(1.5-h0,4)}.')],
  'The gradient (h − y)x has the same form as the perceptron and least-squares updates: error times input.'),
 problem('metrics', 'Read a confusion matrix', ['classification-metrics'],
  'A screening model on 200 patients: TP = 30, FN = 10, FP = 20, TN = 140.',
  [
   num('Accuracy.', 0.85, ['The fraction of all predictions that are correct.', '(TP + TN)/total.'], '(30 + 140)/200 = 0.85.', tol=1e-6),
   num('Precision.', 0.6, ['Of the patients the model flagged, what fraction are really positive?', 'TP/(TP + FP).'], '30/50 = 0.6.', tol=1e-6, mistakes=[(0.75, 'That is recall, which divides by the actual positives.')]),
   num('Recall.', 0.75, ['Of the patients who are really positive, what fraction did the model flag?', 'TP/(TP + FN).'], '30/40 = 0.75.', tol=1e-6, mistakes=[(0.6, 'That is precision, which divides by the flagged patients.')]),
   num('F1 (3 decimals).', 2*0.6*0.75/1.35, ['F1 is the harmonic mean of precision and recall.', '2PR/(P + R).'], '0.9/1.35 ≈ 0.667.',
       mistakes=[(0.675, 'That is the ordinary mean; F1 uses the harmonic mean.')]),
   choice('Always predicting "healthy" would score what accuracy?', '0.8, with recall 0', ['0.85', '0.5', '0.2'],
          ['How many patients are actually healthy?'], '160/200 = 0.8 while finding nobody: accuracy hides the misses.',
          {'0.2': 'That is the fraction of sick patients, all of whom this rule misses.'}),
  ],
  [step('Accuracy 170/200 = 0.85; precision 30/50 = 0.6; recall 30/40 = 0.75.'),
   step('F1 = 2·0.6·0.75/(0.6 + 0.75) ≈ 0.667.'),
   step('The trivial model gets 0.8 accuracy with recall 0.')],
  'Choose the metric that matches the cost of mistakes: recall for screening, precision when false alarms are expensive.'),
 problem('auc', 'AUC by counting pairs', ['roc-auc'],
  'Scores of positives: 0.9, 0.7, 0.4. Scores of negatives: 0.8, 0.3, 0.2, 0.1.',
  [
   num('How many positive-negative pairs are there?', 12, ['Each positive is paired with each negative.', '3 × 4.'], '3 × 4 = 12.', tol=0),
   num('In how many pairs does the positive score higher?', 10,
       ['Go positive by positive and count the negatives below it.', '0.9 beats all 4 negatives; continue with 0.7 and 0.4.'], '4 + 3 + 3 = 10.', tol=0),
   num('AUC (3 decimals).', auc, ['AUC is the fraction of pairs ranked correctly.', 'Correct pairs / all pairs.'], f'10/12 ≈ {r(auc,3)}.'),
   vec('At threshold 0.5, give the true positive rate and the false positive rate (3 decimals).', [2/3, 0.25],
       ['Count the positives and the negatives scored above 0.5.', 'Divide by the number of positives and of negatives respectively.'], 'TPR = 2/3 and FPR = 1/4: one point on the ROC curve.', tol=0.002,
       mistakes=[([0.25, 2/3], 'Order: true positive rate first.')]),
   num('Add a fourth positive with score 0.3. Compute the new AUC (3 decimals).', auc2,
       ['There are now 16 pairs. The new positive ties with one negative.', 'A tie counts as half a correct pair: 0.3 beats 0.2 and 0.1 and ties with 0.3.'], f'12.5/16 ≈ {r(auc2,3)}.',
       mistakes=[(0.75, 'The tie counts ½, not 0.'), (0.8125, 'The tie counts ½, not 1.')]),
  ],
  [step('12 pairs, 10 ranked correctly: AUC = 10/12 ≈ 0.833.'),
   step('Threshold 0.5: TPR 2/3, FPR 1/4.'),
   step('With the tie: (10 + 2 + 0.5)/16 = 0.781.')],
  'AUC is the probability that a random positive outranks a random negative. It ignores the threshold, which you still have to choose.'),
 ])

# ---------------- ML in production ----------------
homework('ml/ml-in-production', 'ml', 'ML in production',
 'Drift, retraining schedules, and turning costs into a decision threshold.',
 [
 problem('drift', 'How often to retrain?', ['ml-in-production'],
  'A model starts at 90% accuracy and loses 1 percentage point per month because the data drift. Retraining restores 90%.',
  [
   num('With retraining every 6 months, what is the average accuracy, in %?', 87, ['Accuracy falls linearly from 90 over each 6-month cycle; what is its average over the cycle?', 'The average of a linear decline is the value at the middle: A₀ − dT/2.'], '90 − 1·6/2 = 87%.', tol=0, unit='%',
       mistakes=[(0.87, 'Give the accuracy in percent, not as a fraction.'), (84, 'That is the accuracy just before retraining; the question asks for the average over the cycle.')]),
   num('And with retraining every 2 months, in %?', 89, ['Same reasoning with T = 2.', 'A₀ − dT/2.'], '90 − 1 = 89%.', tol=0, unit='%',
       mistakes=[(0.89, 'Give the accuracy in percent, not as a fraction.')]),
   choice('Customers\' ages shift upward, but for any given age the chance of churning is unchanged. What kind of shift is this?', 'Covariate shift', ['Concept drift', 'Label shift', 'No shift'],
          ['Which changed: P(x), P(y | x), or P(y)?'], 'The inputs\' distribution P(x) changed while P(y | x) stayed: covariate shift.',
          {'Concept drift': 'Concept drift means P(y | x) changes; here the chance of churning at each age is unchanged.', 'No shift': 'The input distribution did change.'}),
   choice('After a policy change, customers with the same profile now churn at a different rate. What kind of shift is this?', 'Concept drift', ['Covariate shift', 'Label shift', 'No shift'],
          ['The relationship between inputs and label changed.'], 'P(y | x) changed: concept drift, which requires retraining on new labelled data.',
          {'Covariate shift': 'The profiles are the same; what changed is how they relate to churn.'}),
   choice('The share of churners rises from 10% to 20%, but churners\' profiles look as before, and so do non-churners\'. What kind of shift is this?', 'Label shift', ['Covariate shift', 'Concept drift', 'No shift'],
          ['Which changed: P(y), or P(x | y)?'], 'The class balance P(y) moved while P(x | y) stayed: label shift. P(y | x) does change as a consequence, so predicted probabilities need recalibrating.',
          {'Concept drift': 'P(y | x) does change, but the cause is P(y): the class balance moved while P(x | y) stayed.'}),
  ],
  [step('Average accuracy over a cycle is A₀ − dT/2: 87% for T = 6 and 89% for T = 2.'),
   step('Inputs shift with P(y | x) fixed: covariate shift. P(y | x) changes: concept drift. P(y) changes with P(x | y) fixed: label shift.')],
  'Retraining more often costs money; the formula lets you weigh that cost against the accuracy you gain.'),
 problem('cost', 'From costs to a threshold', ['classification-metrics', 'ml-in-production'],
  'Missing a churner (FN) costs 5; a wasted retention offer (FP) costs 1. Assume an offer always keeps a customer who would have churned, and that the model\'s probabilities are calibrated.',
  [
   vec('For a customer with churn probability p = 0.25, give the expected cost of not flagging and of flagging.', [1.25, 0.75],
       ['Not flagging costs 5 if they churn. Flagging costs 1 if they would have stayed anyway.', 'Multiply each cost by the probability that it happens.'], 'Not flagging: 5·0.25 = 1.25. Flagging: 1·0.75 = 0.75. So flag.', tol=1e-6,
       mistakes=[([0.75, 1.25], 'Order: not flagging first.'), ([1.25, 0.25], 'Flagging costs 1 when the customer does not churn, which has probability 1 − p.')]),
   num('At what probability p are the two expected costs equal (3 decimals)?', 1/6,
       ['Write both expected costs as functions of p.', 'Not flagging costs 5p; flagging costs 1·(1 − p). Set them equal.'],
       'p = 1/6 ≈ 0.167: flag every customer above it. In general the threshold is C_FP/(C_FP + C_FN).',
       mistakes=[(0.2, 'That is the cost ratio; flagging costs only when the customer does not churn, with probability 1 − p.'), (5/6, 'You swapped the costs.'), (0.5, '0.5 is only right when both mistakes cost the same.')]),
   num('Each offer now costs 2. What is the new threshold (3 decimals)?', 2/7,
       ['Redo the break-even with the new cost of flagging.', 'Solve 5p = 2(1 − p).'], '2/7 ≈ 0.286: dearer offers mean you flag only more likely churners.',
       mistakes=[(1/6, 'The offer cost changed; redo the break-even.'), (0.4, 'That is 2/5, the cost ratio; include the 1 − p.')]),
   choice('Labels (who actually churned) arrive three months late. What can you monitor in the meantime?', 'The input distributions and the distribution of predicted probabilities',
          ['Accuracy on this week\'s customers', 'Nothing until labels arrive', 'The training loss'],
          ['Which quantities need no labels?'], 'Input and prediction drift (for example with PSI) can be measured immediately; accuracy has to wait for the labels.',
          {'Accuracy on this week\'s customers': 'Accuracy needs the labels, which arrive three months late.', 'The training loss': 'The training loss was fixed at training time; it says nothing about new data.'}),
  ],
  [step('At p = 0.25: not flagging 1.25, flagging 0.75: flag.'),
   step('Break-even: 5p = 1 − p gives p = 1/6. With offer cost 2: 5p = 2(1 − p) gives p = 2/7.', r'p^*=\frac{C_{FP}}{C_{FP}+C_{FN}}'),
   step('Without labels, watch input and prediction distributions (PSI).')],
  'Deployed models are judged by business costs, not by accuracy; the threshold is where the two expected costs are equal.'),
 ])
