from lib import *
sig = lambda s: 1/(1+np.exp(-s))

# ---------------- The learning problem ----------------
homework('ml/the-learning-problem', 'ml', 'The learning problem',
 'Framing a prediction task: the kind of learning, the features, and a workflow that does not fool you.',
 [
 problem('kinds', 'Name the problem', ['ml-landscape'],
  'For each task, pick the kind of machine learning.',
  [
   choice('Predict next month\'s electricity use (in kWh) of a household from past bills.', 'Supervised regression', ['Supervised classification', 'Unsupervised clustering', 'Reinforcement learning'],
          ['Is there a known answer in the training data? Is it a number or a category?'], 'Past bills give labelled examples, and the target is a number: regression.'),
   choice('Decide whether an email is spam, using emails that people already marked.', 'Supervised binary classification', ['Supervised regression', 'Unsupervised clustering', 'Reinforcement learning'],
          ['The labels are "spam" and "not spam".'], 'Labelled examples with two categories: binary classification.'),
   choice('Group shoppers into segments when nobody has labelled any segment.', 'Unsupervised clustering', ['Supervised classification', 'Supervised regression', 'Reinforcement learning'],
          ['There are no labels at all.'], 'With no labels, we look for structure: clustering.'),
   choice('A robot learns to walk by trying moves and receiving a reward for distance covered.', 'Reinforcement learning', ['Supervised regression', 'Unsupervised clustering', 'Supervised classification'],
          ['Nobody tells the robot the right move; it only gets a reward afterwards.'], 'Learning from rewards for actions is reinforcement learning.'),
  ],
  [step('Ask two questions: are there labels, and is the label a number or a category? Rewards for actions mean reinforcement learning.'),
   step('Electricity: labelled number (regression). Spam: labelled category (classification). Segments: no labels (clustering). Robot: rewards (reinforcement).')],
  'Naming the problem type fixes the loss (squared error for regression, logistic or hinge for classification) and the metrics you report.'),
 problem('features', 'Turning raw data into features', ['feature-representation'],
  'A table has two numeric columns (area, age) and one categorical column, colour, with values red, green, blue and white.',
  [
   vec('One-hot encode colour = green, with the columns in the order red, green, blue, white.', [0, 1, 0, 0],
       ['One-hot uses one column per category and puts a 1 in the column of the actual value.'], '[0, 1, 0, 0].', tol=0),
   num('How many feature columns are there after one-hot encoding colour (not counting an intercept)?', 6,
       ['Two numeric columns stay as they are.', 'Colour becomes one column per category.'], '2 + 4 = 6.', tol=0,
       mistakes=[(3, 'Colour does not stay one column: it becomes four.')]),
   choice('Why not encode the colours as 1, 2, 3, 4?', 'A linear model would treat white as "four times red" and green as halfway between red and blue, an order that does not exist',
          ['It uses less memory', 'Numbers cannot be categories', 'It is fine for any model'],
          ['What does θ · x do with a feature whose value goes up from 1 to 4?'], 'A single number imposes a fake order and fake distances. One-hot lets each category have its own weight.'),
  ],
  [step('green → [0, 1, 0, 0].'),
   step('Columns: area, age, and four colour indicators: 6.'),
   step('Integer codes impose an order and spacing that the categories do not have.')],
  'Feature design often matters more than the model: a linear model on good features beats a clever model on bad ones.'),
 problem('workflow', 'A workflow that does not fool you', ['ml-workflow'],
  'You have 1,000 labelled examples and split them 70% / 15% / 15% into training, validation and test sets.',
  [
   num('How many examples are in the training set?', 700, [], '70% of 1,000.', tol=0),
   choice('You want to standardize the features. Where should the means and standard deviations come from?', 'The training set only, then apply them unchanged to validation and test',
          ['All 1,000 examples', 'Each set separately', 'The test set, because that is what we care about'],
          ['Anything computed from the test set lets test information leak into the model.'],
          'Statistics from the training set only; using the other sets leaks information and makes the scores too optimistic.',
          {'All 1,000 examples': 'That includes the test rows, so their information leaks into training (data leakage).', 'Each set separately': 'Then the same raw value is scaled differently in each set, and the model sees shifted inputs.'}),
   choice('You tried 20 settings and chose the one with the best validation score. Which score should you report?', 'The test score of the chosen setting, computed once',
          ['The best validation score', 'The training score', 'The average of all 20 validation scores'],
          ['The validation set was used to choose, so its best score is biased upwards.'], 'Only data never used for choosing gives an honest estimate.'),
  ],
  [step('Training: 700, validation: 150, test: 150.'),
   step('Fit scaling on the training rows only.'),
   step('Report the test score once, after all choices are made.')],
  'Every end-to-end project on this site follows this order: lock the test set, choose on validation or cross-validation, report the test score once.'),
 ])

# ---------------- Linear classification ----------------
homework('ml/linear-classification', 'ml', 'Linear classification',
 'Linear classifiers, the perceptron, and its mistake bound.',
 [
 problem('hyperplane', 'Classify with a hyperplane', ['linear-classifier'],
  'A classifier predicts sign(θ · x + θ₀) with θ = [2, −1] and θ₀ = −1.',
  [
   num('Predict the label of x = [1, 0] (enter +1 or −1).', 1, ['Compute the score 2·1 − 1·0 − 1.'], 'Score 1 > 0, so +1.', tol=0),
   num('Predict the label of x = [0, 1].', -1, ['Score = 0 − 1 − 1.'], 'Score −2 < 0, so −1.', tol=0),
   num('Compute the distance from x = [1, 0] to the decision boundary (3 decimals).', 1/np.sqrt(5),
       ['distance = |θ · x + θ₀| / ||θ||.', '||θ|| = sqrt(4 + 1).'], f'1/sqrt 5 ≈ {r(1/np.sqrt(5),3)}.', mistakes=[(1, 'Divide the score by ||θ|| = sqrt 5 to get a distance.')]),
   choice('If you double θ and θ₀, what changes?', 'Nothing about the predictions or the boundary; only the scores double', ['The boundary moves', 'All predictions flip', 'The distance to the boundary doubles'],
          ['Does the sign of 2(θ · x + θ₀) differ from the sign of θ · x + θ₀?'], 'The boundary {θ · x + θ₀ = 0} is unchanged, and so is the distance |score|/||θ||. This is why margins are measured after dividing by ||θ||.'),
  ],
  [step('Scores: [1, 0] → 1 (class +1); [0, 1] → −2 (class −1).'),
   step('Distance of [1, 0]: |1|/sqrt 5 ≈ 0.447.'),
   step('Scaling (θ, θ₀) by 2 doubles the scores but keeps the boundary and distances.')],
  'Because scaling θ changes nothing, the SVM fixes the scale by asking for scores of at least 1 and then makes ||θ|| small.'),
 problem('perceptron', 'Run the perceptron by hand', ['perceptron', 'linear-classifier-through-origin'],
  'Data through the origin: x1 = [1, 2] with y = +1 and x2 = [2, −1] with y = −1. Start with θ = [0, 0], visit x1 then x2, and update when y(θ · x) ≤ 0.',
  [
   vec('What is θ after visiting x1?', [1, 2], ['y(θ · x1) = 0 ≤ 0: a mistake.', 'Update θ ← θ + y x1.'], 'θ = [1, 2].', tol=0),
   vec('What is θ after visiting x2?', [-1, 3],
       ['Check y(θ · x2) with θ = [1, 2].', 'θ · x2 = 2 − 2 = 0, so it is a mistake. Update with y = −1.'], '[1, 2] − [2, −1] = [−1, 3].', tol=0,
       mistakes=[([1, 2], 'θ · x2 = 0 and the rule updates when y(θ · x) ≤ 0, including 0.'), ([3, 1], 'y = −1, so subtract x2.')]),
   num('How many mistakes in total before a full pass with no mistakes?', 2,
       ['Run a second pass with θ = [−1, 3].'], 'Second pass: y(θ · x1) = 5 > 0 and y(θ · x2) = 5 > 0, so no more updates: 2 mistakes.', tol=0),
  ],
  [step('x1: 0 ≤ 0, update to [1, 2].'),
   step('x2: θ · x2 = 0, update to [1, 2] − [2, −1] = [−1, 3].'),
   step('Pass 2: both margins are 5 > 0. Converged after 2 mistakes.')],
  'The perceptron only moves when it is wrong, and each move adds or subtracts one example. The final θ is a sum of the mistaken examples.'),
 problem('bound', 'Check the mistake bound', ['perceptron-convergence', 'linear-separability'],
  'For the same two points, use θ* = [−1, 3] (the perceptron\'s answer) as a separator.',
  [
   num('Compute R² = max ||x||² over the two points.', 5, ['||[1, 2]||² = 5 and ||[2, −1]||² = 5.'], 'R² = 5.', tol=0),
   num('Compute the margin γ = min over points of y(θ* · x)/||θ*|| (3 decimals).', 5/np.sqrt(10),
       ['Both points have y(θ* · x) = 5.', '||θ*|| = sqrt 10.'], f'5/sqrt 10 ≈ {r(5/np.sqrt(10),3)}.'),
   num('Compute the bound (R/γ)² on the number of mistakes.', 2, ['R²/γ² = 5/2.5.'], 'The bound is 2, and the perceptron made exactly 2 mistakes: the bound is tight here.',
       mistakes=[(5/(5/np.sqrt(10)), 'Square the ratio: (R/γ)² = R²/γ².')]),
  ],
  [step('R² = 5; y(θ*·x) = 5 for both points and ||θ*|| = sqrt 10, so γ = 5/sqrt 10 ≈ 1.581.'),
   step('(R/γ)² = 5/2.5 = 2 mistakes at most, matching what we saw.')],
  'The bound says: wide margin relative to the data radius means few mistakes, whatever the dimension.'),
 ])

# ---------------- Losses and convexity ----------------
homework('ml/losses-and-convexity', 'ml', 'Losses and convexity',
 'Zero-one and hinge loss, the max-margin objective, and convexity.',
 [
 problem('losses', 'Zero-one versus hinge', ['empirical-risk-zero-one', 'hinge-loss', 'surrogate-losses'],
  'θ = [1, −1], no offset. Data: ([2, 0], +1), ([1, 1], +1), ([0, 1], −1), ([1, 0], −1). Let z = y(θ · x).',
  [
   vec('Compute z for the four points, in order.', [2, 0, 1, -1], ['z = y times the score.', 'Point 3: score −1, y = −1.'], 'z = [2, 0, 1, −1].', tol=0),
   num('Compute the zero-one risk (a point with z ≤ 0 counts as a mistake).', 0.5, ['Count the points with z ≤ 0 and divide by 4.'], 'Points 2 and 4: 2/4 = 0.5.',
       mistakes=[(0.25, 'z = 0 counts as a mistake: the point is on the boundary.')]),
   num('Compute the average hinge loss, max(0, 1 − z).', 0.75, ['Losses: max(0, 1 − 2), max(0, 1 − 0), ...'], '(0 + 1 + 0 + 2)/4 = 0.75.'),
   choice('Point 3 has z = 1. Its zero-one loss is 0. What is its hinge loss, and why?', '0: it is correct with a margin of at least 1', ['1: every point pays at least 1', '0.5: it is close to the boundary'],
          ['max(0, 1 − 1).'], 'Hinge loss is 0 once z ≥ 1. Points with 0 < z < 1 are correct but still pay a little, which pushes the boundary away from them.'),
  ],
  [step('z = [2, 0, 1, −1].'),
   step('Zero-one: two points with z ≤ 0, risk 0.5.'),
   step('Hinge: [0, 1, 0, 2], average 0.75. Hinge is a convex upper bound on zero-one loss.')],
  'The zero-one loss is flat almost everywhere, so it gives no gradient; the hinge loss is convex and says how wrong each point is.'),
 problem('svm', 'The max-margin objective', ['max-margin-svm'],
  'Same data and θ = [1, −1] as the previous problem.',
  [
   num('Compute J = (λ/2)||θ||² + average hinge loss with λ = 0.1.', 0.85, ['||θ||² = 2.', '(0.1/2)·2 = 0.1; add the average hinge loss 0.75.'], '0.1 + 0.75 = 0.85.'),
   num('Compute the margin width 2/||θ|| (3 decimals).', 2/np.sqrt(2), [], f'2/sqrt 2 ≈ {r(np.sqrt(2),3)}.'),
   choice('Increasing λ makes the optimal θ...', 'smaller, so the margin gets wider and more points may violate it', ['larger, so the margin gets narrower', 'unchanged', 'zero for any λ > 0'],
          ['λ multiplies ||θ||² in the objective.'], 'A stronger penalty shrinks ||θ||, and the margin 2/||θ|| widens, at the cost of more hinge loss.'),
  ],
  [step('J = 0.05·2 + 0.75 = 0.85.'),
   step('Margin width 2/||θ|| = sqrt 2 ≈ 1.414.'),
   step('Larger λ favours small ||θ||: wider margin, more violations tolerated.')],
  'λ trades a wide margin (simplicity) against fitting every point, the same trade as ridge regression.'),
 problem('convex', 'Is it convex?', ['convex-functions'],
  'A function is convex if the chord between any two points on its graph lies on or above the graph.',
  [
   choice('Which function is NOT convex on the real line?', 'x³', ['x²', '|x|', 'max(0, 1 − x)'],
          ['Check the second derivative where it exists.', '(x³)\'\' = 6x, which is negative for x < 0.'], 'x³ curves downward for x < 0. The others are convex (|x| and the hinge have corners but still lie below their chords).'),
   num('For f(x) = x², compute the chord value at the midpoint of x = 1 and x = 3, that is (f(1) + f(3))/2.', 5, [], '(1 + 9)/2 = 5, which is at least f(2) = 4, as convexity requires.'),
   choice('Why does convexity matter for training?', 'Every local minimum is a global minimum, so gradient descent cannot get stuck in a worse valley',
          ['Convex functions have no minimum', 'Convex functions are always differentiable', 'It makes the model more accurate'],
          ['Think about what can go wrong when a loss has several valleys.'], 'For a convex loss, any point where the (sub)gradient is zero is a global minimum.',
          {'Convex functions are always differentiable': '|x| is convex but has a corner at 0; that is why subgradients exist.'}),
  ],
  [step('x³ has negative second derivative for x < 0, so it is not convex.'),
   step('Chord at the midpoint: 5 ≥ f(2) = 4.'),
   step('Convex losses have no bad local minima.')],
  'Squared, hinge and logistic losses are convex in θ for linear models; neural network losses are not, which is why their training is harder.'),
 ])

# ---------------- Optimization ----------------
k1 = int(np.ceil(np.log(1e-3)/np.log(0.6))); k2 = int(np.ceil(np.log(1e-6)/np.log(1-1/40)))
homework('ml/optimization', 'ml', 'Optimization',
 'Gradient descent and its step size, conditioning, stochastic subgradient steps, and constraints.',
 [
 problem('step', 'Choose the step size', ['gradient-descent-method'],
  'Minimize J(θ) = 2(θ − 1)² by gradient descent from θ = 3.',
  [
   num('With α = 0.1, compute θ after one step.', 2.2, ['J\'(θ) = 4(θ − 1); at θ = 3 it is 8.'], '3 − 0.1·8 = 2.2.',
       mistakes=[(3.8, 'Gradient descent moves against the gradient: subtract α·J\'(θ).')]),
   num('Each step multiplies the distance to the minimum by the same factor. What is it for α = 0.1?', 0.6,
       ['θ − 1 ← (θ − 1) − α·4(θ − 1).'], '1 − 4α = 0.6.'),
   num('Above which α does gradient descent diverge?', 0.5, ['It diverges when |1 − 4α| > 1.', 'The curvature is L = 4, and the limit is 2/L.'], 'α > 2/L = 0.5.'),
   num('With α = 0.1, how many steps until the distance to the minimum is below 1/1000 of its start?', k1,
       ['Find the smallest k with 0.6ᵏ < 0.001.', 'k > ln(0.001)/ln(0.6).'], f'ln 0.001/ln 0.6 ≈ {r(np.log(1e-3)/np.log(0.6),2)}, so k = {k1}.', tol=0),
  ],
  [step('J\'(3) = 8, so θ = 3 − 0.8 = 2.2.'),
   step('Distance factor 1 − 4α = 0.6; divergence when α > 2/L = 0.5.'),
   step(f'0.6ᵏ < 10⁻³ needs k > 13.5, so {k1} steps.')],
  'The step size is set by the largest curvature L, and the speed by how the curvatures compare, as the next problem shows.'),
 problem('kappa', 'Conditioning decides the speed', ['gradient-descent-method', 'momentum'],
  'A quadratic loss has Hessian eigenvalues L = 20 and μ = 0.5.',
  [
   num('Compute the condition number κ = L/μ.', 40, [], '40.', tol=0),
   num('With α = 1/L, the slowest direction shrinks by 1 − μ/L per step. How many steps to shrink the error to 10⁻⁶ of its start?', k2,
       ['Solve (1 − 1/40)ᵏ < 10⁻⁶.', 'k > ln(10⁻⁶)/ln(0.975).'], f'k = {k2}, roughly κ ln(10⁶) ≈ 553.', tol=1),
   choice('Which change would reduce the number of steps the most?', 'Rescaling the features so the curvatures become similar', ['Using α = 3/L', 'Starting closer to zero', 'Using more data'],
          ['What would κ be if both curvatures were equal?'], 'With κ close to 1 gradient descent needs only a few steps; α = 3/L diverges. Momentum helps too, bringing the dependence down to about sqrt κ.',
          {'Using α = 3/L': 'Any α above 2/L diverges along the steepest direction.'}),
  ],
  [step('κ = 20/0.5 = 40.'),
   step(f'(0.975)ᵏ < 10⁻⁶ gives k = {k2}.'),
   step('Standardizing features lowers κ; momentum reduces the dependence to about sqrt κ.')],
  'The diabetes project measured this: κ = 464 predicted about 6,400 steps, and it took 5,883.'),
 problem('ssgd', 'One stochastic subgradient step', ['stochastic-subgradient-descent', 'subgradients'],
  'SVM with λ = 0.1 and step η = 0.5. Current θ = [0.5, 0]. The random example is x = [1, 1] with y = −1. The rule: θ ← (1 − ηλ)θ + η y x if y(θ · x) ≤ 1, otherwise θ ← (1 − ηλ)θ.',
  [
   num('Compute y(θ · x).', -0.5, [], '−1·(0.5 + 0) = −0.5.'),
   vec('Compute the new θ (3 decimals).', [0.95*0.5-0.5, -0.5],
       ['−0.5 ≤ 1, so use the first case.', '(1 − 0.05)·[0.5, 0] + 0.5·(−1)·[1, 1].'], '0.95·[0.5, 0] − [0.5, 0.5] = [−0.025, −0.5].', tol=0.001,
       mistakes=[([0.475, 0], 'This example violates the margin (−0.5 ≤ 1), so the hinge term also contributes η y x.'), ([0, -0.5], 'Do not forget the shrink factor (1 − ηλ) = 0.95 on the old θ.')]),
   choice('At z = y(θ · x) = 1 exactly, the hinge loss has a corner. Which slopes are valid subgradients of max(0, 1 − z) with respect to z there?', 'Any value between −1 and 0', ['Only 0', 'Only −1', 'Any real number'],
          ['On the left the slope is −1, on the right it is 0.'], 'At a corner of a convex function any slope between the left and right slopes is a subgradient.'),
  ],
  [step('y(θ · x) = −0.5 ≤ 1: the hinge is active.'),
   step('θ = 0.95[0.5, 0] + 0.5(−1)[1, 1] = [−0.025, −0.5].'),
   step('At the corner, subgradients fill the interval [−1, 0].')],
  'SSGD is cheap because each step uses one example; the (1 − ηλ) factor is the regularizer shrinking the weights.'),
 problem('lagrange', 'Minimize with a constraint', ['lagrange-multipliers'],
  'Minimize f(x, y) = x² + y² subject to x + 2y = 5. Use the page\'s convention ∇f + λ∇h = 0 with h(x, y) = x + 2y − 5.',
  [
   vec('Find the minimizer (x, y).', [1, 2],
       ['∇f + λ∇h = 0 gives 2x + λ = 0 and 2y + 2λ = 0.', 'So x = −λ/2 and y = −λ. Substitute into the constraint.'],
       'x + 2y = −λ/2 − 2λ = 5 gives λ = −2, so (x, y) = (1, 2).', tol=1e-6),
   num('What is λ with this convention?', -2, ['From 2x + λ = 0 with x = 1.'], 'λ = −2. (With the convention ∇f = λ∇h you would get +2; the sign depends on the convention.)', tol=0,
       mistakes=[(2, 'That is the value for the convention ∇f = λ∇h. With ∇f + λ∇h = 0 the sign flips.')]),
   num('What is the minimum value of f?', 5, [], '1 + 4 = 5: the squared distance from the origin to the line.', tol=0),
  ],
  [step('2x + λ = 0, 2y + 2λ = 0, x + 2y = 5.'),
   step('x = −λ/2, y = −λ; −λ/2 − 2λ = 5 gives λ = −2, so (1, 2).'),
   step('f(1, 2) = 5. Geometrically, (1, 2) is the point on the line closest to the origin, in the direction of the normal [1, 2].')],
  'The hard-margin SVM is solved with exactly these conditions, extended to inequality constraints.'),
 ])

# ---------------- Regression ----------------
xs = np.array([0,1,2,3.]); ys = np.array([1,3,4,8.])
Xd = np.c_[np.ones(4), xs]; w = np.linalg.solve(Xd.T@Xd, Xd.T@ys); pr = Xd@w; rs = ys-pr
sse = (rs**2).sum(); sst = ((ys-ys.mean())**2).sum()
homework('ml/regression', 'ml', 'Regression',
 'Fitting and reporting a line, feature scaling, and multicollinearity.',
 [
 problem('fit', 'Fit and report a line', ['linear-regression', 'least-squares-normal-equation'],
  'Fit y = θ₀ + θ₁x by least squares to (0, 1), (1, 3), (2, 4), (3, 8).',
  [
   num('Compute the slope θ₁ = Σ(x − x̄)(y − ȳ) / Σ(x − x̄)².', w[1],
       ['x̄ = 1.5 and ȳ = 4.', 'Σ(x − x̄)(y − ȳ) = (−1.5)(−3) + (−0.5)(−1) + (0.5)(0) + (1.5)(4).', 'That sum is 11; Σ(x − x̄)² = 5.'], '11/5 = 2.2.'),
   num('Compute the intercept θ₀ = ȳ − θ₁x̄.', w[0], [], '4 − 2.2·1.5 = 0.7.'),
   num('Compute the RMSE on these points (3 decimals).', np.sqrt(sse/4),
       ['Predictions: 0.7, 2.9, 5.1, 7.3.', 'Residuals: 0.3, 0.1, −1.1, 0.7; square, average, take the root.'], f'sqrt(1.8/4) ≈ {r(np.sqrt(sse/4),3)}.',
       mistakes=[(sse/4, 'That is the mean squared error. Take the square root for RMSE.')]),
   num('Compute the MAE.', np.abs(rs).mean(), ['Average the absolute residuals.'], f'(0.3 + 0.1 + 1.1 + 0.7)/4 = {r(np.abs(rs).mean(),3)}.'),
   num('Compute R² (3 decimals).', 1-sse/sst, ['R² = 1 − SSE/SST.', 'SSE = 1.8; SST = Σ(y − ȳ)² = 9 + 1 + 0 + 16.'], f'1 − 1.8/26 ≈ {r(1-sse/sst,3)}.'),
  ],
  [step('x̄ = 1.5, ȳ = 4, Sxy = 11, Sxx = 5: θ₁ = 2.2, θ₀ = 0.7.'),
   step('Residuals 0.3, 0.1, −1.1, 0.7: SSE = 1.8, RMSE ≈ 0.671, MAE = 0.55.'),
   step('SST = 26, R² = 1 − 1.8/26 ≈ 0.931.')],
  'RMSE and MAE are in the units of y; R² compares with predicting the mean. Report them on test data, where R² can be negative.'),
 problem('scale', 'Scaling and the original units', ['feature-scaling'],
  'Floor area has training mean 100 m² and standard deviation 25 m². A model fitted on the standardized area z is ŷ = 300 + 40z (price in thousands).',
  [
   num('Compute z for an area of 150 m².', 2, ['z = (x − mean)/sd.'], '(150 − 100)/25 = 2.', tol=0),
   num('What is the slope in the original units (thousands per m²)?', 1.6, ['z = (x − 100)/25, so 40z = (40/25)(x − 100).'], '40/25 = 1.6 per m².',
       mistakes=[(40, 'That is the change per standard deviation (25 m²). Divide by 25 for one m².'), (1000, 'Divide by the standard deviation, do not multiply.')]),
   num('What is the intercept in the original units?', 140, ['300 + 1.6(x − 100) = (300 − 160) + 1.6x.'], '300 − 160 = 140.', tol=0),
   choice('The test set has mean area 110. Which mean do you use to standardize test rows?', '100, the training mean', ['110, the test mean', 'The average of 100 and 110', 'No scaling for test rows'],
          ['The model learned what z = 0 means from the training data.'], 'Use the training statistics for every new row; otherwise the same area gets different z values.'),
  ],
  [step('z = (150 − 100)/25 = 2.'),
   step('ŷ = 300 + 40(x − 100)/25 = 140 + 1.6x.'),
   step('Always standardize new data with the training mean and standard deviation.')],
  'Scaling changes the numbers you see but not the predictions of plain least squares; it does change gradient descent\'s speed and the effect of ridge and lasso penalties.'),
 problem('collinear', 'Diagnose multicollinearity', ['multicollinearity'],
  'Two standardized features have correlation 0.8, so C = [[1, 0.8], [0.8, 1]].',
  [
   vec('Find the eigenvalues of C, largest first.', [1.8, 0.2], ['For [[1, ρ], [ρ, 1]] they are 1 ± ρ.'], '1.8 (along [1, 1]) and 0.2 (along [1, −1]).', tol=1e-6),
   num('Compute the condition number κ.', 9, [], '1.8/0.2 = 9.', tol=1e-6),
   num('Compute each feature\'s VIF (3 decimals).', 1/(1-0.64), ['VIF = 1/(1 − R²), and with two features R² = ρ².'], '1/(1 − 0.64) ≈ 2.778.',
       mistakes=[(5, 'Use R² = ρ² = 0.64, not ρ = 0.8.')]),
   vec('With ridge λ = 0.2, compute the new condition number and the shrink factor λ₂/(λ₂ + λ) of the weak direction.', [2/0.4, 0.5],
       ['Ridge adds λ to every eigenvalue.', 'κ = (1.8 + 0.2)/(0.2 + 0.2).'], 'κ = 2.0/0.4 = 5 and shrink factor 0.2/0.4 = 0.5.', tol=1e-6),
  ],
  [step('Eigenvalues 1 ± 0.8 = 1.8 and 0.2; κ = 9.'),
   step('VIF = 1/(1 − 0.64) ≈ 2.78: each weight\'s variance is almost 3 times what it would be with uncorrelated features.'),
   step('Ridge with λ = 0.2: eigenvalues 2.0 and 0.4, κ = 5; the weak direction is shrunk by half.')],
  'Moderate correlation is harmless; VIFs above about 10 (the diabetes data reach 58) make individual weights unreliable.'),
 ])

# ---------------- Generalization and regularization ----------------
cv = np.array([0.30,0.26,0.34,0.28,0.32]); se = cv.std(ddof=1)/np.sqrt(5)
homework('ml/generalization-and-regularization', 'ml', 'Generalization and regularization',
 'Overfitting, bias and variance, ridge and lasso, and honest evaluation with validation, cross-validation and the bootstrap.',
 [
 problem('ridge', 'Ridge and lasso by hand', ['ridge-regularization', 'lasso'],
  'One feature, no intercept, n = 5 examples with Σx² = 10 and Σxy = 12.',
  [
   num('Compute the least-squares weight.', 1.2, ['θ = Σxy / Σx².'], '12/10 = 1.2.'),
   num('Compute the ridge weight with λ = 0.4, using (Σx² + nλ)θ = Σxy.', 1.0, ['nλ = 5·0.4 = 2.'], '12/(10 + 2) = 1.0.',
       mistakes=[(12/10.4, 'The page\'s ridge system adds nλ = 2, not λ, to Σx².')]),
   num('For a standardized feature ((1/n)Σx² = 1) with least-squares weight w = 0.9, the lasso weight is sign(w)·max(|w| − λ, 0). Compute it for λ = 0.3.', 0.6, [], '0.9 − 0.3 = 0.6.'),
   num('For the same feature, from which λ onward is the lasso weight exactly 0?', 0.9, ['max(|w| − λ, 0) = 0 when λ ≥ |w|.'], 'λ ≥ 0.9: lasso switches the feature off, while ridge would only shrink it.'),
  ],
  [step('Least squares: 12/10 = 1.2. Ridge: 12/(10 + 5·0.4) = 1.0.'),
   step('Lasso on a standardized feature: soft threshold 0.9 − 0.3 = 0.6, and 0 once λ ≥ 0.9.')],
  'Ridge shrinks every weight a bit; lasso subtracts a fixed amount and stops at zero, which selects features.'),
 problem('bv', 'Bias, variance and the gap', ['model-complexity-generalization', 'bias-variance'],
  'Model A: training error 0.10, test error 0.55. Model B: training error 0.40, test error 0.45.',
  [
   vec('Compute the generalization gap (test − training) of A and of B.', [0.45, 0.05], [], 'A: 0.45, B: 0.05.', tol=1e-6),
   choice('Which model would you deploy, and what is A\'s problem?', 'B; A overfits (low training error, much higher test error)', ['A, because its training error is lower', 'B; A underfits', 'Neither: both overfit'],
          ['Which model does better on data it has not seen?'], 'Test error decides. A\'s large gap is the signature of high variance (overfitting).'),
   num('For another model, bias² = 0.05, variance = 0.10 and noise = 0.20. What is its expected squared test error?', 0.35, ['Expected test error = bias² + variance + noise.'], '0.35.'),
   choice('Which change mainly reduces variance without adding bias?', 'Collecting more training data', ['Using a more flexible model', 'Removing regularization', 'Training for fewer steps on the same data'],
          ['What happens to the spread of fitted models when each is trained on more data?'], 'More data steadies the fit without restricting the model. Regularization also lowers variance but adds some bias.'),
  ],
  [step('Gaps: A 0.45, B 0.05. Deploy B; A overfits.'),
   step('Expected error 0.05 + 0.10 + 0.20 = 0.35. The noise part (0.20) cannot be removed by any model.'),
   step('More data lowers variance without adding bias.')],
  'Regularization, validation and cross-validation are all tools for managing this trade-off.'),
 problem('cvboot', 'Cross-validation and the bootstrap', ['cross-validation', 'bootstrap', 'train-validation-test'],
  'Five-fold cross-validation of one setting gives validation errors 0.30, 0.26, 0.34, 0.28, 0.32.',
  [
   num('Compute the CV score (the average).', 0.30, [], '1.50/5 = 0.30.'),
   num('Compute its standard error, (sample sd with n − 1)/sqrt 5 (4 decimals).', se,
       ['Deviations from 0.30: 0, −0.04, 0.04, −0.02, 0.02.', 'Sum of squares 0.004; divide by 4, take the root, then divide by sqrt 5.'], f'sd = sqrt(0.001) ≈ 0.0316; SE ≈ {r(se,4)}.', tol=0.0005),
   choice('Four penalties have CV errors 0.300 (λ = 0.01, SE 0.014), 0.305 (λ = 0.1), 0.312 (λ = 1) and 0.360 (λ = 10). Which does the one-standard-error rule choose?', 'λ = 1', ['λ = 0.01', 'λ = 0.1', 'λ = 10'],
          ['Find the best score and add one SE: 0.300 + 0.014 = 0.314.', 'Among settings with CV ≤ 0.314, take the simplest (largest penalty).'],
          'λ = 1 is within one SE of the best and is the most regularized such setting.',
          {'λ = 0.01': 'That has the lowest CV error, but the rule prefers the simplest model that is statistically as good.'}),
   num('A bootstrap resample of n = 10 examples: what is the probability that a given example is left out (3 decimals)?', 0.9**10, ['Each of 10 draws misses it with probability 0.9.'], f'0.9¹⁰ ≈ {r(0.9**10,3)} (for large n, about 0.368).'),
  ],
  [step('CV = 0.30; sd = sqrt(0.004/4) ≈ 0.0316; SE ≈ 0.0141.'),
   step('One-SE rule: threshold 0.314, largest λ below it is 1.'),
   step('P(left out) = 0.9¹⁰ ≈ 0.349.')],
  'Cross-validation chooses settings; the bootstrap tells you how much a number could change with different data. The diabetes project uses both.'),
 ])

# ---------------- Logistic regression ----------------
s0 = 0.5; h0 = sig(s0)
pos = [0.9,0.7,0.4]; neg = [0.8,0.3,0.2,0.1]; auc = np.mean([[p>n for n in neg] for p in pos])
homework('ml/logistic-regression', 'ml', 'Logistic regression',
 'Probabilities from the sigmoid, the logistic loss and its gradient, and evaluating a classifier.',
 [
 problem('prob', 'Probability, loss and one gradient step', ['logistic-regression', 'logistic-loss'],
  'θ = [1, −2], θ₀ = 0.5. An example has x = [2, 1] and true label y = 0.',
  [
   num('Compute the score s = θ · x + θ₀.', 0.5, [], '2 − 2 + 0.5 = 0.5.'),
   num('Compute the predicted probability h = σ(s) (3 decimals).', h0, ['σ(s) = 1/(1 + e^(−s)).', 'e^(−0.5) ≈ 0.6065.'], f'1/1.6065 ≈ {r(h0,3)}.'),
   num('Compute the logistic loss for y = 0 (3 decimals).', -np.log(1-h0), ['For y = 0 the loss is −ln(1 − h).'], f'−ln({r(1-h0,4)}) ≈ {r(-np.log(1-h0),3)}.',
       mistakes=[(-np.log(h0), 'That is the loss for y = 1. For y = 0 use −ln(1 − h).')]),
   num('The gradient with respect to θ₀ is h − y. With learning rate 1, what is the new θ₀ (3 decimals)?', 0.5-h0, ['θ₀ ← θ₀ − 1·(h − y).'], f'0.5 − {r(h0,4)} ≈ {r(0.5-h0,3)}: the score goes down, lowering the probability of the wrong class.'),
  ],
  [step(f's = 0.5, h = σ(0.5) ≈ {r(h0,4)}.'),
   step(f'Loss for y = 0: −ln(1 − h) ≈ {r(-np.log(1-h0),4)}.'),
   step(f'Gradient: (h − y)x = {r(h0,4)}·[2, 1] for θ and {r(h0,4)} for θ₀; new θ₀ ≈ {r(0.5-h0,4)}.')],
  'The gradient (h − y)x has the same form as the perceptron and least-squares updates: error times input.'),
 problem('metrics', 'Read a confusion matrix', ['classification-metrics'],
  'A screening model on 200 patients: TP = 30, FN = 10, FP = 20, TN = 140.',
  [
   num('Accuracy.', 0.85, [], '(30 + 140)/200 = 0.85.'),
   num('Precision.', 0.6, ['TP/(TP + FP).'], '30/50 = 0.6.', mistakes=[(0.75, 'That is recall, TP/(TP + FN).')]),
   num('Recall.', 0.75, ['TP/(TP + FN).'], '30/40 = 0.75.', mistakes=[(0.6, 'That is precision, TP/(TP + FP).')]),
   num('F1 (3 decimals).', 2*0.6*0.75/1.35, ['Harmonic mean: 2PR/(P + R).'], '0.9/1.35 ≈ 0.667.'),
   choice('Always predicting "healthy" would score what accuracy?', '0.8, with recall 0', ['0.85', '0.5', '0.2'],
          ['There are 40 sick patients out of 200.'], '160/200 = 0.8 while finding nobody: accuracy hides the misses.'),
  ],
  [step('Accuracy 170/200 = 0.85; precision 30/50 = 0.6; recall 30/40 = 0.75.'),
   step('F1 = 2·0.6·0.75/(0.6 + 0.75) ≈ 0.667.'),
   step('The trivial model gets 0.8 accuracy with recall 0.')],
  'Choose the metric that matches the cost of mistakes: recall for screening, precision when false alarms are expensive.'),
 problem('auc', 'AUC by counting pairs', ['roc-auc'],
  'Scores of positives: 0.9, 0.7, 0.4. Scores of negatives: 0.8, 0.3, 0.2, 0.1.',
  [
   num('How many positive-negative pairs are there?', 12, [], '3 × 4 = 12.', tol=0),
   num('In how many pairs does the positive score higher?', 10,
       ['0.9 beats all 4 negatives.', '0.7 beats 0.3, 0.2 and 0.1; 0.4 beats 0.3, 0.2 and 0.1.'], '4 + 3 + 3 = 10.', tol=0),
   num('AUC (3 decimals).', auc, [], f'10/12 ≈ {r(auc,3)}.'),
   vec('At threshold 0.5, give the true positive rate and the false positive rate (3 decimals).', [2/3, 0.25],
       ['Positives above 0.5: 0.9 and 0.7.', 'Negatives above 0.5: 0.8.'], 'TPR = 2/3 and FPR = 1/4: one point on the ROC curve.', tol=0.005),
  ],
  [step('12 pairs, 10 ranked correctly: AUC = 10/12 ≈ 0.833.'),
   step('Threshold 0.5: TPR 2/3, FPR 1/4.')],
  'AUC is the probability that a random positive outranks a random negative. It ignores the threshold, which you still have to choose.'),
 ])

# ---------------- ML in production ----------------
homework('ml/ml-in-production', 'ml', 'ML in production',
 'Drift, retraining schedules, and turning costs into a decision threshold.',
 [
 problem('drift', 'How often to retrain?', ['ml-in-production'],
  'A model starts at 90% accuracy and loses 1 percentage point per month because the data drift. Retraining restores 90%.',
  [
   num('With retraining every 6 months, what is the average accuracy (A₀ − dT/2)?', 87, ['d = 1 point per month and T = 6.'], '90 − 1·6/2 = 87%.', tol=0),
   num('And with retraining every 2 months?', 89, [], '90 − 1 = 89%.', tol=0),
   choice('Customers\' ages shift upward, but for any given age the chance of churning is unchanged. What kind of shift is this?', 'Covariate shift', ['Concept drift', 'Label shift', 'No shift'],
          ['Which changed: P(x), P(y | x), or P(y)?'], 'The inputs\' distribution P(x) changed while P(y | x) stayed: covariate shift.'),
   choice('After a policy change, customers with the same profile now churn at a different rate. What kind of shift is this?', 'Concept drift', ['Covariate shift', 'Label shift', 'No shift'],
          ['The relationship between inputs and label changed.'], 'P(y | x) changed: concept drift, which requires retraining on new labelled data.'),
  ],
  [step('Average accuracy A₀ − dT/2: 87% for T = 6 and 89% for T = 2.'),
   step('Inputs shift with P(y | x) fixed: covariate shift. P(y | x) changes: concept drift.')],
  'Retraining more often costs money; the formula lets you weigh that cost against the accuracy you gain.'),
 problem('cost', 'From costs to a threshold', ['ml-in-production', 'classification-metrics'],
  'Missing a churner (FN) costs 5; a wasted retention offer (FP) costs 1. The model\'s probabilities are calibrated.',
  [
   num('Flag a customer when p > C_FP/(C_FP + C_FN). Compute this threshold (3 decimals).', 1/6, [], '1/6 ≈ 0.167.',
       mistakes=[(5/6, 'Swap the costs: the threshold is C_FP/(C_FP + C_FN).'), (0.5, '0.5 is only right when both mistakes cost the same.')]),
   vec('For a customer with p = 0.25, give the expected cost of not flagging and of flagging.', [1.25, 0.75],
       ['Not flagging costs 5 if they churn (probability 0.25).', 'Flagging costs 1 if they do not churn (probability 0.75).'], 'Not flagging: 5·0.25 = 1.25. Flagging: 1·0.75 = 0.75. So flag.', tol=1e-6),
   choice('Labels (who actually churned) arrive three months late. What can you monitor in the meantime?', 'The input distributions, for example with PSI, and the distribution of predicted probabilities',
          ['Accuracy on this week\'s customers', 'Nothing until labels arrive', 'The training loss'],
          ['Which quantities need no labels?'], 'Input and prediction drift can be measured immediately; accuracy has to wait for the labels.'),
  ],
  [step('Threshold 1/(1 + 5) ≈ 0.167.'),
   step('At p = 0.25: not flagging 1.25, flagging 0.75: flag.'),
   step('Without labels, watch input and prediction distributions (PSI).')],
  'Deployed models are judged by business costs, not by accuracy; the threshold is where the two expected costs are equal.'),
 ])
